<?php

namespace Misakstvanu\LaravelSkautis\Requests\Summary;

final class ExportPersonCloneInput
{
    public function __construct(
        public readonly ?int $id = null,
        public readonly ?int $idPerson = null,
        public readonly ?string $person = null,
        public readonly ?string $displayName = null,
        public readonly ?int $registrationYear = null,
        public readonly ?bool $functionFilter = null,
        public readonly ?bool $functionAnd = null,
        public readonly ?bool $qualificationAnd = null,
        public readonly ?int $ageFrom = null,
        public readonly ?int $ageTo = null,
        public readonly ?bool $viewDisplayName = null,
        public readonly ?bool $firstName = null,
        public readonly ?bool $lastName = null,
        public readonly ?bool $nickName = null,
        public readonly ?bool $maidenName = null,
        public readonly ?bool $birthday = null,
        public readonly ?bool $identificationNumber = null,
        public readonly ?bool $identificationNumberStart = null,
        public readonly ?bool $age = null,
        public readonly ?bool $sex = null,
        public readonly ?bool $isForeign = null,
        public readonly ?bool $street = null,
        public readonly ?bool $city = null,
        public readonly ?bool $postcode = null,
        public readonly ?bool $state = null,
        public readonly ?bool $postalFirstLine = null,
        public readonly ?bool $postalStreet = null,
        public readonly ?bool $postalCity = null,
        public readonly ?bool $postalPostcode = null,
        public readonly ?bool $postalState = null,
        public readonly ?bool $assurance = null,
        public readonly ?bool $assuranceCard = null,
        public readonly ?bool $allergy = null,
        public readonly ?bool $foodRestrictions = null,
        public readonly ?bool $drugs = null,
        public readonly ?bool $specialRequirements = null,
        public readonly ?bool $healthLimitation = null,
        public readonly ?bool $bodySkills = null,
        public readonly ?bool $functionOneColumn = null,
        public readonly ?bool $qualificationOneColumn = null,
        public readonly ?bool $membership = null,
        public readonly ?bool $membershipCategory = null,
        public readonly ?bool $membershipOneColumn = null,
        public readonly ?bool $username = null,
        public readonly ?bool $catalog = null,
        public readonly ?bool $journal = null,
        public readonly ?bool $journalRegistration = null,
        public readonly ?bool $journalAttachment = null,
        public readonly ?bool $isPublic = null,
        public readonly ?int $idUnit = null,
        public readonly ?string $sortName = null,
        public readonly ?bool $includeChild = null,
        public readonly ?string $string = null,
        public readonly ?int $int = null,
        public readonly ?bool $parentNote = null,
        public readonly ?bool $note = null,
        public readonly ?bool $registrationNumber = null,
        public readonly ?bool $yearFrom = null,
        public readonly ?bool $isUnitEnroll = null,
        public readonly ?bool $unitEnrollCondition = null,
        public readonly ?bool $allowDataStorage = null,
        public readonly ?bool $allowAudiovisual = null,
        public readonly ?bool $allowSocialNetwork = null,
        public readonly ?bool $allowMarketing = null,
        public readonly ?bool $school = null,
        public readonly ?bool $idCardValidTo = null,
        public readonly ?bool $idCardNumber = null,
        public readonly ?bool $parentFatherFirstName = null,
        public readonly ?bool $parentFatherLastName = null,
        public readonly ?bool $parentFatherPhone = null,
        public readonly ?bool $parentFatherMail = null,
        public readonly ?bool $parentFatherNote = null,
        public readonly ?bool $parentMotherFirstName = null,
        public readonly ?bool $parentMotherLastName = null,
        public readonly ?bool $parentMotherMail = null,
        public readonly ?bool $parentMotherPhone = null,
        public readonly ?bool $parentMotherNote = null,
        public readonly ?bool $parentOtherFirstName = null,
        public readonly ?bool $parentOtherLastName = null,
        public readonly ?bool $parentOtherMail = null,
        public readonly ?bool $parentOtherPhone = null,
        public readonly ?bool $parentOtherNote = null,
        public readonly ?bool $parentOtherParentType = null,
        public readonly ?bool $promiseChild = null,
        public readonly ?bool $promiseScout = null,
        public readonly ?bool $promiseOfficial = null,
        public readonly ?bool $trailProgress = null,
    ) {}

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(
            [
            'ID' => $this->id,
            'ID_Person' => $this->idPerson,
            'Person' => $this->person,
            'DisplayName' => $this->displayName,
            'RegistrationYear' => $this->registrationYear,
            'FunctionFilter' => $this->functionFilter,
            'FunctionAnd' => $this->functionAnd,
            'QualificationAnd' => $this->qualificationAnd,
            'AgeFrom' => $this->ageFrom,
            'AgeTo' => $this->ageTo,
            'ViewDisplayName' => $this->viewDisplayName,
            'FirstName' => $this->firstName,
            'LastName' => $this->lastName,
            'NickName' => $this->nickName,
            'MaidenName' => $this->maidenName,
            'Birthday' => $this->birthday,
            'IdentificationNumber' => $this->identificationNumber,
            'IdentificationNumberStart' => $this->identificationNumberStart,
            'Age' => $this->age,
            'Sex' => $this->sex,
            'IsForeign' => $this->isForeign,
            'Street' => $this->street,
            'City' => $this->city,
            'Postcode' => $this->postcode,
            'State' => $this->state,
            'PostalFirstLine' => $this->postalFirstLine,
            'PostalStreet' => $this->postalStreet,
            'PostalCity' => $this->postalCity,
            'PostalPostcode' => $this->postalPostcode,
            'PostalState' => $this->postalState,
            'Assurance' => $this->assurance,
            'AssuranceCard' => $this->assuranceCard,
            'Allergy' => $this->allergy,
            'FoodRestrictions' => $this->foodRestrictions,
            'Drugs' => $this->drugs,
            'SpecialRequirements' => $this->specialRequirements,
            'HealthLimitation' => $this->healthLimitation,
            'BodySkills' => $this->bodySkills,
            'FunctionOneColumn' => $this->functionOneColumn,
            'QualificationOneColumn' => $this->qualificationOneColumn,
            'Membership' => $this->membership,
            'MembershipCategory' => $this->membershipCategory,
            'MembershipOneColumn' => $this->membershipOneColumn,
            'Username' => $this->username,
            'Catalog' => $this->catalog,
            'Journal' => $this->journal,
            'JournalRegistration' => $this->journalRegistration,
            'JournalAttachment' => $this->journalAttachment,
            'IsPublic' => $this->isPublic,
            'ID_Unit' => $this->idUnit,
            'SortName' => $this->sortName,
            'IncludeChild' => $this->includeChild,
            'string' => $this->string,
            'int' => $this->int,
            'ParentNote' => $this->parentNote,
            'Note' => $this->note,
            'RegistrationNumber' => $this->registrationNumber,
            'YearFrom' => $this->yearFrom,
            'IsUnitEnroll' => $this->isUnitEnroll,
            'UnitEnrollCondition' => $this->unitEnrollCondition,
            'AllowDataStorage' => $this->allowDataStorage,
            'AllowAudiovisual' => $this->allowAudiovisual,
            'AllowSocialNetwork' => $this->allowSocialNetwork,
            'AllowMarketing' => $this->allowMarketing,
            'School' => $this->school,
            'IdCardValidTo' => $this->idCardValidTo,
            'IdCardNumber' => $this->idCardNumber,
            'ParentFatherFirstName' => $this->parentFatherFirstName,
            'ParentFatherLastName' => $this->parentFatherLastName,
            'ParentFatherPhone' => $this->parentFatherPhone,
            'ParentFatherMail' => $this->parentFatherMail,
            'ParentFatherNote' => $this->parentFatherNote,
            'ParentMotherFirstName' => $this->parentMotherFirstName,
            'ParentMotherLastName' => $this->parentMotherLastName,
            'ParentMotherMail' => $this->parentMotherMail,
            'ParentMotherPhone' => $this->parentMotherPhone,
            'ParentMotherNote' => $this->parentMotherNote,
            'ParentOtherFirstName' => $this->parentOtherFirstName,
            'ParentOtherLastName' => $this->parentOtherLastName,
            'ParentOtherMail' => $this->parentOtherMail,
            'ParentOtherPhone' => $this->parentOtherPhone,
            'ParentOtherNote' => $this->parentOtherNote,
            'ParentOtherParentType' => $this->parentOtherParentType,
            'PromiseChild' => $this->promiseChild,
            'PromiseScout' => $this->promiseScout,
            'PromiseOfficial' => $this->promiseOfficial,
            'TrailProgress' => $this->trailProgress,
            ],
            fn (mixed $v): bool => $v !== null,
        );
    }
}
