<?php

namespace Misakstvanu\LaravelSkautis\Responses\OrganizationUnit;

final class MemberCardInvoiceDetailOutput
{
    public function __construct(
        public readonly ?string $idLogin = null,
        public readonly ?int $id = null,
        public readonly ?int $idUnit = null,
        public readonly ?string $unit = null,
        public readonly ?string $registrationNumber = null,
        public readonly ?string $street = null,
        public readonly ?string $city = null,
        public readonly ?string $postcode = null,
        public readonly ?string $state = null,
        public readonly ?string $stateCode = null,
        public readonly ?string $iC = null,
        public readonly ?string $dIC = null,
        public readonly ?string $displayName = null,
        public readonly ?int $sequence = null,
        public readonly ?string $maturity = null,
        public readonly ?string $dateGenerating = null,
        public readonly ?float $totalPrice = null,
        public readonly ?float $totalPriceWithVat = null,
        public readonly ?float $price = null,
        public readonly ?float $priceBase = null,
        public readonly ?float $priceFirst = null,
        public readonly ?float $priceSecond = null,
        public readonly ?float $vatBase = null,
        public readonly ?float $vatFirst = null,
        public readonly ?float $vatSecond = null,
        public readonly ?int $idMemberCardInvoiceGenerate = null,
        public readonly ?string $idMemberCardInvoiceState = null,
        public readonly ?string $memberCardInvoiceState = null,
        public readonly ?int $idInvoiceGroup = null,
        public readonly ?string $invoiceGroupContractorIC = null,
        public readonly ?string $invoiceGroupContractorDIC = null,
        public readonly ?string $invoiceGroupContractorPhone = null,
        public readonly ?string $invoiceGroupContractorEmail = null,
        public readonly ?string $invoiceGroupWeb = null,
        public readonly ?string $invoiceGroupFileReference = null,
        public readonly ?string $invoiceGroupBankAccount = null,
        public readonly ?string $invoiceGroupBankCode = null,
        public readonly ?string $invoiceGroupBank = null,
        public readonly ?string $paymentType = null,
        public readonly ?string $dateTaxableSupply = null,
        public readonly ?string $qRCodeString = null,
        public readonly ?string $invoiceGroupContractor = null,
        public readonly ?string $invoiceGroupContractorAddress = null,
        public readonly ?string $invoiceBankAccount = null,
    ) {}

    public static function fromStdClass(\stdClass $obj): self
    {
        return new self(
            idLogin: isset($obj->{'ID_Login'}) ? (string) $obj->{'ID_Login'} : null,
            id: isset($obj->{'ID'}) ? (int) $obj->{'ID'} : null,
            idUnit: isset($obj->{'ID_Unit'}) ? (int) $obj->{'ID_Unit'} : null,
            unit: isset($obj->{'Unit'}) ? (string) $obj->{'Unit'} : null,
            registrationNumber: isset($obj->{'RegistrationNumber'}) ? (string) $obj->{'RegistrationNumber'} : null,
            street: isset($obj->{'Street'}) ? (string) $obj->{'Street'} : null,
            city: isset($obj->{'City'}) ? (string) $obj->{'City'} : null,
            postcode: isset($obj->{'Postcode'}) ? (string) $obj->{'Postcode'} : null,
            state: isset($obj->{'State'}) ? (string) $obj->{'State'} : null,
            stateCode: isset($obj->{'StateCode'}) ? (string) $obj->{'StateCode'} : null,
            iC: isset($obj->{'IC'}) ? (string) $obj->{'IC'} : null,
            dIC: isset($obj->{'DIC'}) ? (string) $obj->{'DIC'} : null,
            displayName: isset($obj->{'DisplayName'}) ? (string) $obj->{'DisplayName'} : null,
            sequence: isset($obj->{'Sequence'}) ? (int) $obj->{'Sequence'} : null,
            maturity: isset($obj->{'Maturity'}) ? (string) $obj->{'Maturity'} : null,
            dateGenerating: isset($obj->{'DateGenerating'}) ? (string) $obj->{'DateGenerating'} : null,
            totalPrice: isset($obj->{'TotalPrice'}) ? (float) $obj->{'TotalPrice'} : null,
            totalPriceWithVat: isset($obj->{'TotalPriceWithVat'}) ? (float) $obj->{'TotalPriceWithVat'} : null,
            price: isset($obj->{'Price'}) ? (float) $obj->{'Price'} : null,
            priceBase: isset($obj->{'PriceBase'}) ? (float) $obj->{'PriceBase'} : null,
            priceFirst: isset($obj->{'PriceFirst'}) ? (float) $obj->{'PriceFirst'} : null,
            priceSecond: isset($obj->{'PriceSecond'}) ? (float) $obj->{'PriceSecond'} : null,
            vatBase: isset($obj->{'VatBase'}) ? (float) $obj->{'VatBase'} : null,
            vatFirst: isset($obj->{'VatFirst'}) ? (float) $obj->{'VatFirst'} : null,
            vatSecond: isset($obj->{'VatSecond'}) ? (float) $obj->{'VatSecond'} : null,
            idMemberCardInvoiceGenerate: isset($obj->{'ID_MemberCardInvoiceGenerate'}) ? (int) $obj->{'ID_MemberCardInvoiceGenerate'} : null,
            idMemberCardInvoiceState: isset($obj->{'ID_MemberCardInvoiceState'}) ? (string) $obj->{'ID_MemberCardInvoiceState'} : null,
            memberCardInvoiceState: isset($obj->{'MemberCardInvoiceState'}) ? (string) $obj->{'MemberCardInvoiceState'} : null,
            idInvoiceGroup: isset($obj->{'ID_InvoiceGroup'}) ? (int) $obj->{'ID_InvoiceGroup'} : null,
            invoiceGroupContractorIC: isset($obj->{'InvoiceGroupContractorIC'}) ? (string) $obj->{'InvoiceGroupContractorIC'} : null,
            invoiceGroupContractorDIC: isset($obj->{'InvoiceGroupContractorDIC'}) ? (string) $obj->{'InvoiceGroupContractorDIC'} : null,
            invoiceGroupContractorPhone: isset($obj->{'InvoiceGroupContractorPhone'}) ? (string) $obj->{'InvoiceGroupContractorPhone'} : null,
            invoiceGroupContractorEmail: isset($obj->{'InvoiceGroupContractorEmail'}) ? (string) $obj->{'InvoiceGroupContractorEmail'} : null,
            invoiceGroupWeb: isset($obj->{'InvoiceGroupWeb'}) ? (string) $obj->{'InvoiceGroupWeb'} : null,
            invoiceGroupFileReference: isset($obj->{'InvoiceGroupFileReference'}) ? (string) $obj->{'InvoiceGroupFileReference'} : null,
            invoiceGroupBankAccount: isset($obj->{'InvoiceGroupBankAccount'}) ? (string) $obj->{'InvoiceGroupBankAccount'} : null,
            invoiceGroupBankCode: isset($obj->{'InvoiceGroupBankCode'}) ? (string) $obj->{'InvoiceGroupBankCode'} : null,
            invoiceGroupBank: isset($obj->{'InvoiceGroupBank'}) ? (string) $obj->{'InvoiceGroupBank'} : null,
            paymentType: isset($obj->{'PaymentType'}) ? (string) $obj->{'PaymentType'} : null,
            dateTaxableSupply: isset($obj->{'DateTaxableSupply'}) ? (string) $obj->{'DateTaxableSupply'} : null,
            qRCodeString: isset($obj->{'QRCodeString'}) ? (string) $obj->{'QRCodeString'} : null,
            invoiceGroupContractor: isset($obj->{'InvoiceGroupContractor'}) ? (string) $obj->{'InvoiceGroupContractor'} : null,
            invoiceGroupContractorAddress: isset($obj->{'InvoiceGroupContractorAddress'}) ? (string) $obj->{'InvoiceGroupContractorAddress'} : null,
            invoiceBankAccount: isset($obj->{'InvoiceBankAccount'}) ? (string) $obj->{'InvoiceBankAccount'} : null,
        );
    }
}
