<?php

namespace Misakstvanu\LaravelSkautis\Responses\OrganizationUnit;

final class MembershipApplicationDetailReportOutput
{
    public function __construct(
        public readonly ?int $id = null,
        public readonly ?bool $isAdult = null,
        public readonly ?string $dateFilled = null,
        public readonly ?string $dateFinished = null,
        public readonly ?bool $allowDataStorage = null,
        public readonly ?bool $allowAudiovisual = null,
        public readonly ?bool $allowSocialNetwork = null,
        public readonly ?bool $allowMarketing = null,
        public readonly ?string $personFinishedFirstName = null,
        public readonly ?string $personFinishedLastName = null,
        public readonly ?int $idUnit = null,
        public readonly ?string $unit = null,
        public readonly ?string $registrationNumber = null,
        public readonly ?string $unitStreet = null,
        public readonly ?string $unitCity = null,
        public readonly ?string $unitPostcode = null,
        public readonly ?string $unitState = null,
        public readonly ?string $unitIC = null,
        public readonly ?int $idUnitCentral = null,
        public readonly ?string $unitCentral = null,
        public readonly ?string $unitCentralRegistrationNumber = null,
        public readonly ?string $unitCentralStreet = null,
        public readonly ?string $unitCentralCity = null,
        public readonly ?string $unitCentralPostcode = null,
        public readonly ?string $unitCentralState = null,
        public readonly ?string $unitCentralIC = null,
        public readonly ?int $idPerson = null,
        public readonly ?string $person = null,
        public readonly ?string $firstName = null,
        public readonly ?string $lastName = null,
        public readonly ?string $idSex = null,
        public readonly ?string $sex = null,
        public readonly ?string $birthday = null,
        public readonly ?string $identificationCode = null,
        public readonly ?string $idCitizenship = null,
        public readonly ?string $citizenship = null,
        public readonly ?string $citizenshipCustom = null,
        public readonly ?bool $isForeign = null,
        public readonly ?string $maidenName = null,
        public readonly ?int $idDistrictBirth = null,
        public readonly ?string $districtBirth = null,
        public readonly ?string $birthCity = null,
        public readonly ?string $street = null,
        public readonly ?string $city = null,
        public readonly ?string $state = null,
        public readonly ?string $postcode = null,
        public readonly ?string $postalFirstLine = null,
        public readonly ?string $postalStreet = null,
        public readonly ?string $postalCity = null,
        public readonly ?string $postalState = null,
        public readonly ?string $postalPostcode = null,
        public readonly ?string $displayName = null,
        public readonly ?string $idContactType = null,
        public readonly ?string $contactType = null,
        public readonly ?string $value = null,
        public readonly ?string $idParentType = null,
        public readonly ?string $parentType = null,
    ) {}

    public static function fromStdClass(\stdClass $obj): self
    {
        return new self(
            id: isset($obj->{'ID'}) ? (int) $obj->{'ID'} : null,
            isAdult: isset($obj->{'IsAdult'}) ? (bool) $obj->{'IsAdult'} : null,
            dateFilled: isset($obj->{'DateFilled'}) ? (string) $obj->{'DateFilled'} : null,
            dateFinished: isset($obj->{'DateFinished'}) ? (string) $obj->{'DateFinished'} : null,
            allowDataStorage: isset($obj->{'AllowDataStorage'}) ? (bool) $obj->{'AllowDataStorage'} : null,
            allowAudiovisual: isset($obj->{'AllowAudiovisual'}) ? (bool) $obj->{'AllowAudiovisual'} : null,
            allowSocialNetwork: isset($obj->{'AllowSocialNetwork'}) ? (bool) $obj->{'AllowSocialNetwork'} : null,
            allowMarketing: isset($obj->{'AllowMarketing'}) ? (bool) $obj->{'AllowMarketing'} : null,
            personFinishedFirstName: isset($obj->{'PersonFinishedFirstName'}) ? (string) $obj->{'PersonFinishedFirstName'} : null,
            personFinishedLastName: isset($obj->{'PersonFinishedLastName'}) ? (string) $obj->{'PersonFinishedLastName'} : null,
            idUnit: isset($obj->{'ID_Unit'}) ? (int) $obj->{'ID_Unit'} : null,
            unit: isset($obj->{'Unit'}) ? (string) $obj->{'Unit'} : null,
            registrationNumber: isset($obj->{'RegistrationNumber'}) ? (string) $obj->{'RegistrationNumber'} : null,
            unitStreet: isset($obj->{'UnitStreet'}) ? (string) $obj->{'UnitStreet'} : null,
            unitCity: isset($obj->{'UnitCity'}) ? (string) $obj->{'UnitCity'} : null,
            unitPostcode: isset($obj->{'UnitPostcode'}) ? (string) $obj->{'UnitPostcode'} : null,
            unitState: isset($obj->{'UnitState'}) ? (string) $obj->{'UnitState'} : null,
            unitIC: isset($obj->{'UnitIC'}) ? (string) $obj->{'UnitIC'} : null,
            idUnitCentral: isset($obj->{'ID_UnitCentral'}) ? (int) $obj->{'ID_UnitCentral'} : null,
            unitCentral: isset($obj->{'UnitCentral'}) ? (string) $obj->{'UnitCentral'} : null,
            unitCentralRegistrationNumber: isset($obj->{'UnitCentralRegistrationNumber'}) ? (string) $obj->{'UnitCentralRegistrationNumber'} : null,
            unitCentralStreet: isset($obj->{'UnitCentralStreet'}) ? (string) $obj->{'UnitCentralStreet'} : null,
            unitCentralCity: isset($obj->{'UnitCentralCity'}) ? (string) $obj->{'UnitCentralCity'} : null,
            unitCentralPostcode: isset($obj->{'UnitCentralPostcode'}) ? (string) $obj->{'UnitCentralPostcode'} : null,
            unitCentralState: isset($obj->{'UnitCentralState'}) ? (string) $obj->{'UnitCentralState'} : null,
            unitCentralIC: isset($obj->{'UnitCentralIC'}) ? (string) $obj->{'UnitCentralIC'} : null,
            idPerson: isset($obj->{'ID_Person'}) ? (int) $obj->{'ID_Person'} : null,
            person: isset($obj->{'Person'}) ? (string) $obj->{'Person'} : null,
            firstName: isset($obj->{'FirstName'}) ? (string) $obj->{'FirstName'} : null,
            lastName: isset($obj->{'LastName'}) ? (string) $obj->{'LastName'} : null,
            idSex: isset($obj->{'ID_Sex'}) ? (string) $obj->{'ID_Sex'} : null,
            sex: isset($obj->{'Sex'}) ? (string) $obj->{'Sex'} : null,
            birthday: isset($obj->{'Birthday'}) ? (string) $obj->{'Birthday'} : null,
            identificationCode: isset($obj->{'IdentificationCode'}) ? (string) $obj->{'IdentificationCode'} : null,
            idCitizenship: isset($obj->{'ID_Citizenship'}) ? (string) $obj->{'ID_Citizenship'} : null,
            citizenship: isset($obj->{'Citizenship'}) ? (string) $obj->{'Citizenship'} : null,
            citizenshipCustom: isset($obj->{'CitizenshipCustom'}) ? (string) $obj->{'CitizenshipCustom'} : null,
            isForeign: isset($obj->{'IsForeign'}) ? (bool) $obj->{'IsForeign'} : null,
            maidenName: isset($obj->{'MaidenName'}) ? (string) $obj->{'MaidenName'} : null,
            idDistrictBirth: isset($obj->{'ID_DistrictBirth'}) ? (int) $obj->{'ID_DistrictBirth'} : null,
            districtBirth: isset($obj->{'DistrictBirth'}) ? (string) $obj->{'DistrictBirth'} : null,
            birthCity: isset($obj->{'BirthCity'}) ? (string) $obj->{'BirthCity'} : null,
            street: isset($obj->{'Street'}) ? (string) $obj->{'Street'} : null,
            city: isset($obj->{'City'}) ? (string) $obj->{'City'} : null,
            state: isset($obj->{'State'}) ? (string) $obj->{'State'} : null,
            postcode: isset($obj->{'Postcode'}) ? (string) $obj->{'Postcode'} : null,
            postalFirstLine: isset($obj->{'PostalFirstLine'}) ? (string) $obj->{'PostalFirstLine'} : null,
            postalStreet: isset($obj->{'PostalStreet'}) ? (string) $obj->{'PostalStreet'} : null,
            postalCity: isset($obj->{'PostalCity'}) ? (string) $obj->{'PostalCity'} : null,
            postalState: isset($obj->{'PostalState'}) ? (string) $obj->{'PostalState'} : null,
            postalPostcode: isset($obj->{'PostalPostcode'}) ? (string) $obj->{'PostalPostcode'} : null,
            displayName: isset($obj->{'DisplayName'}) ? (string) $obj->{'DisplayName'} : null,
            idContactType: isset($obj->{'ID_ContactType'}) ? (string) $obj->{'ID_ContactType'} : null,
            contactType: isset($obj->{'ContactType'}) ? (string) $obj->{'ContactType'} : null,
            value: isset($obj->{'Value'}) ? (string) $obj->{'Value'} : null,
            idParentType: isset($obj->{'ID_ParentType'}) ? (string) $obj->{'ID_ParentType'} : null,
            parentType: isset($obj->{'ParentType'}) ? (string) $obj->{'ParentType'} : null,
        );
    }
}
