<?php

namespace Misakstvanu\LaravelSkautis\Responses\OrganizationUnit;

final class MembershipApplicationDetailOutput
{
    public function __construct(
        public readonly ?string $idLogin = null,
        public readonly ?int $id = null,
        public readonly ?int $idUnit = null,
        public readonly ?string $unit = null,
        public readonly ?string $unitTitle = null,
        public readonly ?string $logoExtension = null,
        public readonly ?string $registrationNumber = null,
        public readonly ?int $idPerson = null,
        public readonly ?string $idMembershipApplicationState = null,
        public readonly ?string $membershipApplicationState = null,
        public readonly ?string $validTo = null,
        public readonly ?string $accessKey = null,
        public readonly ?bool $isValid = null,
        public readonly ?string $dateCreate = null,
        public readonly ?string $lastOpened = null,
        public readonly ?string $firstName = null,
        public readonly ?string $lastName = null,
        public readonly ?string $firstNameParent = null,
        public readonly ?string $lastNameParent = null,
        public readonly ?string $noteParent = null,
        public readonly ?string $parentNote = null,
        public readonly ?string $parentType = null,
        public readonly ?string $parentTypeCustom = null,
        public readonly ?string $firstNameParent2 = null,
        public readonly ?string $lastNameParent2 = null,
        public readonly ?string $noteParent2 = null,
        public readonly ?string $parent2Note = null,
        public readonly ?string $parentType2 = null,
        public readonly ?string $parentTypeCustom2 = null,
        public readonly ?bool $isAdult = null,
        public readonly ?string $dateFilled = null,
        public readonly ?string $dateFinished = null,
        public readonly ?string $person = null,
        public readonly ?string $birthday = null,
        public readonly ?string $identificationCode = null,
        public readonly ?string $phoneMainHelp = null,
        public readonly ?string $phoneMainPlaceholder = null,
        public readonly ?string $emailMainHelp = null,
        public readonly ?string $emailMainPlaceholder = null,
        public readonly ?string $dateState = null,
        public readonly ?string $reason = null,
        public readonly ?string $idSex = null,
        public readonly ?string $sex = null,
        public readonly ?bool $isForeign = null,
        public readonly ?string $maidenName = null,
        public readonly ?string $idCitizenship = null,
        public readonly ?string $citizenship = null,
        public readonly ?string $citizenshipCustom = null,
        public readonly ?int $idDistrictBirth = null,
        public readonly ?string $birthCity = null,
        public readonly ?string $districtBirth = null,
        public readonly ?string $degrees = null,
        public readonly ?string $idDegreeType1 = null,
        public readonly ?string $idDegreeType2 = null,
        public readonly ?string $idDegreeType3 = null,
        public readonly ?string $street = null,
        public readonly ?string $city = null,
        public readonly ?string $postalFirstLine = null,
        public readonly ?string $state = null,
        public readonly ?string $postcode = null,
        public readonly ?string $postalStreet = null,
        public readonly ?string $postalState = null,
        public readonly ?string $postalPostcode = null,
        public readonly ?string $postalCity = null,
        public readonly ?string $phoneParent = null,
        public readonly ?string $emailParent = null,
        public readonly ?string $phoneParent2 = null,
        public readonly ?string $emailParent2 = null,
        public readonly ?string $phone = null,
        public readonly ?string $email = null,
        public readonly ?string $insuranceNumber = null,
        public readonly ?string $allergy = null,
        public readonly ?string $foodRestrictions = null,
        public readonly ?string $drugs = null,
        public readonly ?string $specialRequirements = null,
        public readonly ?string $healthLimitation = null,
        public readonly ?string $bodySkills = null,
        public readonly ?bool $allowDataStorage = null,
        public readonly ?bool $allowAudiovisual = null,
        public readonly ?bool $allowSocialNetwork = null,
        public readonly ?bool $allowMarketing = null,
        public readonly ?int $idAssurance = null,
        public readonly ?string $assurance = null,
    ) {}

    public static function fromStdClass(\stdClass $obj): self
    {
        return new self(
            idLogin: isset($obj->{'ID_Login'}) ? (string) $obj->{'ID_Login'} : null,
            id: isset($obj->{'ID'}) ? (int) $obj->{'ID'} : null,
            idUnit: isset($obj->{'ID_Unit'}) ? (int) $obj->{'ID_Unit'} : null,
            unit: isset($obj->{'Unit'}) ? (string) $obj->{'Unit'} : null,
            unitTitle: isset($obj->{'UnitTitle'}) ? (string) $obj->{'UnitTitle'} : null,
            logoExtension: isset($obj->{'LogoExtension'}) ? (string) $obj->{'LogoExtension'} : null,
            registrationNumber: isset($obj->{'RegistrationNumber'}) ? (string) $obj->{'RegistrationNumber'} : null,
            idPerson: isset($obj->{'ID_Person'}) ? (int) $obj->{'ID_Person'} : null,
            idMembershipApplicationState: isset($obj->{'ID_MembershipApplicationState'}) ? (string) $obj->{'ID_MembershipApplicationState'} : null,
            membershipApplicationState: isset($obj->{'MembershipApplicationState'}) ? (string) $obj->{'MembershipApplicationState'} : null,
            validTo: isset($obj->{'ValidTo'}) ? (string) $obj->{'ValidTo'} : null,
            accessKey: isset($obj->{'AccessKey'}) ? (string) $obj->{'AccessKey'} : null,
            isValid: isset($obj->{'IsValid'}) ? (bool) $obj->{'IsValid'} : null,
            dateCreate: isset($obj->{'DateCreate'}) ? (string) $obj->{'DateCreate'} : null,
            lastOpened: isset($obj->{'LastOpened'}) ? (string) $obj->{'LastOpened'} : null,
            firstName: isset($obj->{'FirstName'}) ? (string) $obj->{'FirstName'} : null,
            lastName: isset($obj->{'LastName'}) ? (string) $obj->{'LastName'} : null,
            firstNameParent: isset($obj->{'FirstNameParent'}) ? (string) $obj->{'FirstNameParent'} : null,
            lastNameParent: isset($obj->{'LastNameParent'}) ? (string) $obj->{'LastNameParent'} : null,
            noteParent: isset($obj->{'NoteParent'}) ? (string) $obj->{'NoteParent'} : null,
            parentNote: isset($obj->{'ParentNote'}) ? (string) $obj->{'ParentNote'} : null,
            parentType: isset($obj->{'ParentType'}) ? (string) $obj->{'ParentType'} : null,
            parentTypeCustom: isset($obj->{'ParentTypeCustom'}) ? (string) $obj->{'ParentTypeCustom'} : null,
            firstNameParent2: isset($obj->{'FirstNameParent2'}) ? (string) $obj->{'FirstNameParent2'} : null,
            lastNameParent2: isset($obj->{'LastNameParent2'}) ? (string) $obj->{'LastNameParent2'} : null,
            noteParent2: isset($obj->{'NoteParent2'}) ? (string) $obj->{'NoteParent2'} : null,
            parent2Note: isset($obj->{'Parent2Note'}) ? (string) $obj->{'Parent2Note'} : null,
            parentType2: isset($obj->{'ParentType2'}) ? (string) $obj->{'ParentType2'} : null,
            parentTypeCustom2: isset($obj->{'ParentTypeCustom2'}) ? (string) $obj->{'ParentTypeCustom2'} : null,
            isAdult: isset($obj->{'IsAdult'}) ? (bool) $obj->{'IsAdult'} : null,
            dateFilled: isset($obj->{'DateFilled'}) ? (string) $obj->{'DateFilled'} : null,
            dateFinished: isset($obj->{'DateFinished'}) ? (string) $obj->{'DateFinished'} : null,
            person: isset($obj->{'Person'}) ? (string) $obj->{'Person'} : null,
            birthday: isset($obj->{'Birthday'}) ? (string) $obj->{'Birthday'} : null,
            identificationCode: isset($obj->{'IdentificationCode'}) ? (string) $obj->{'IdentificationCode'} : null,
            phoneMainHelp: isset($obj->{'PhoneMainHelp'}) ? (string) $obj->{'PhoneMainHelp'} : null,
            phoneMainPlaceholder: isset($obj->{'PhoneMainPlaceholder'}) ? (string) $obj->{'PhoneMainPlaceholder'} : null,
            emailMainHelp: isset($obj->{'EmailMainHelp'}) ? (string) $obj->{'EmailMainHelp'} : null,
            emailMainPlaceholder: isset($obj->{'EmailMainPlaceholder'}) ? (string) $obj->{'EmailMainPlaceholder'} : null,
            dateState: isset($obj->{'DateState'}) ? (string) $obj->{'DateState'} : null,
            reason: isset($obj->{'Reason'}) ? (string) $obj->{'Reason'} : null,
            idSex: isset($obj->{'ID_Sex'}) ? (string) $obj->{'ID_Sex'} : null,
            sex: isset($obj->{'Sex'}) ? (string) $obj->{'Sex'} : null,
            isForeign: isset($obj->{'IsForeign'}) ? (bool) $obj->{'IsForeign'} : null,
            maidenName: isset($obj->{'MaidenName'}) ? (string) $obj->{'MaidenName'} : null,
            idCitizenship: isset($obj->{'ID_Citizenship'}) ? (string) $obj->{'ID_Citizenship'} : null,
            citizenship: isset($obj->{'Citizenship'}) ? (string) $obj->{'Citizenship'} : null,
            citizenshipCustom: isset($obj->{'CitizenshipCustom'}) ? (string) $obj->{'CitizenshipCustom'} : null,
            idDistrictBirth: isset($obj->{'ID_DistrictBirth'}) ? (int) $obj->{'ID_DistrictBirth'} : null,
            birthCity: isset($obj->{'BirthCity'}) ? (string) $obj->{'BirthCity'} : null,
            districtBirth: isset($obj->{'DistrictBirth'}) ? (string) $obj->{'DistrictBirth'} : null,
            degrees: isset($obj->{'Degrees'}) ? (string) $obj->{'Degrees'} : null,
            idDegreeType1: isset($obj->{'ID_DegreeType1'}) ? (string) $obj->{'ID_DegreeType1'} : null,
            idDegreeType2: isset($obj->{'ID_DegreeType2'}) ? (string) $obj->{'ID_DegreeType2'} : null,
            idDegreeType3: isset($obj->{'ID_DegreeType3'}) ? (string) $obj->{'ID_DegreeType3'} : null,
            street: isset($obj->{'Street'}) ? (string) $obj->{'Street'} : null,
            city: isset($obj->{'City'}) ? (string) $obj->{'City'} : null,
            postalFirstLine: isset($obj->{'PostalFirstLine'}) ? (string) $obj->{'PostalFirstLine'} : null,
            state: isset($obj->{'State'}) ? (string) $obj->{'State'} : null,
            postcode: isset($obj->{'Postcode'}) ? (string) $obj->{'Postcode'} : null,
            postalStreet: isset($obj->{'PostalStreet'}) ? (string) $obj->{'PostalStreet'} : null,
            postalState: isset($obj->{'PostalState'}) ? (string) $obj->{'PostalState'} : null,
            postalPostcode: isset($obj->{'PostalPostcode'}) ? (string) $obj->{'PostalPostcode'} : null,
            postalCity: isset($obj->{'PostalCity'}) ? (string) $obj->{'PostalCity'} : null,
            phoneParent: isset($obj->{'PhoneParent'}) ? (string) $obj->{'PhoneParent'} : null,
            emailParent: isset($obj->{'EmailParent'}) ? (string) $obj->{'EmailParent'} : null,
            phoneParent2: isset($obj->{'PhoneParent2'}) ? (string) $obj->{'PhoneParent2'} : null,
            emailParent2: isset($obj->{'EmailParent2'}) ? (string) $obj->{'EmailParent2'} : null,
            phone: isset($obj->{'Phone'}) ? (string) $obj->{'Phone'} : null,
            email: isset($obj->{'Email'}) ? (string) $obj->{'Email'} : null,
            insuranceNumber: isset($obj->{'InsuranceNumber'}) ? (string) $obj->{'InsuranceNumber'} : null,
            allergy: isset($obj->{'Allergy'}) ? (string) $obj->{'Allergy'} : null,
            foodRestrictions: isset($obj->{'FoodRestrictions'}) ? (string) $obj->{'FoodRestrictions'} : null,
            drugs: isset($obj->{'Drugs'}) ? (string) $obj->{'Drugs'} : null,
            specialRequirements: isset($obj->{'SpecialRequirements'}) ? (string) $obj->{'SpecialRequirements'} : null,
            healthLimitation: isset($obj->{'HealthLimitation'}) ? (string) $obj->{'HealthLimitation'} : null,
            bodySkills: isset($obj->{'BodySkills'}) ? (string) $obj->{'BodySkills'} : null,
            allowDataStorage: isset($obj->{'AllowDataStorage'}) ? (bool) $obj->{'AllowDataStorage'} : null,
            allowAudiovisual: isset($obj->{'AllowAudiovisual'}) ? (bool) $obj->{'AllowAudiovisual'} : null,
            allowSocialNetwork: isset($obj->{'AllowSocialNetwork'}) ? (bool) $obj->{'AllowSocialNetwork'} : null,
            allowMarketing: isset($obj->{'AllowMarketing'}) ? (bool) $obj->{'AllowMarketing'} : null,
            idAssurance: isset($obj->{'ID_Assurance'}) ? (int) $obj->{'ID_Assurance'} : null,
            assurance: isset($obj->{'Assurance'}) ? (string) $obj->{'Assurance'} : null,
        );
    }
}
