<?php

namespace Misakstvanu\LaravelSkautis\Responses\OrganizationUnit;

final class OccupationDetailRealtyOutput
{
    public function __construct(
        public readonly ?int $id = null,
        public readonly ?string $idLogin = null,
        public readonly ?int $idUnit = null,
        public readonly ?string $unit = null,
        public readonly ?string $registrationNumber = null,
        public readonly ?int $idRealty = null,
        public readonly ?string $realty = null,
        public readonly ?int $idRealtyType = null,
        public readonly ?string $realtyType = null,
        public readonly ?bool $publish = null,
        public readonly ?string $note = null,
        public readonly ?bool $isBorrowable = null,
        public readonly ?int $idOccupationRent = null,
        public readonly ?string $displayName = null,
        public readonly ?int $capacity = null,
        public readonly ?string $capacityNote = null,
        public readonly ?string $person = null,
        public readonly ?string $email = null,
        public readonly ?string $phone = null,
        public readonly ?string $contactNote = null,
        public readonly ?string $web = null,
        public readonly ?string $requirementExtension = null,
        public readonly ?string $requirements = null,
        public readonly ?string $photoExtension = null,
        public readonly ?string $fotogallery = null,
        public readonly ?bool $isBookable = null,
        public readonly ?string $bookUrl = null,
        public readonly ?string $accommodationNote = null,
        public readonly ?bool $borrowableForeign = null,
        public readonly ?int $idRealtyCollection = null,
        public readonly ?string $realtyCollection = null,
        public readonly ?string $pointsOfInterest = null,
        public readonly ?string $transportDescription = null,
        public readonly ?string $idOwnerType = null,
        public readonly ?string $ownerType = null,
        public readonly ?int $idUnitRealty = null,
        public readonly ?string $unitRealty = null,
        public readonly ?string $registrationNumberRealty = null,
        public readonly ?string $allEquipment = null,
        public readonly ?string $allLanguages = null,
        public readonly ?string $allTags = null,
        public readonly ?string $allLocations = null,
        public readonly ?string $allTransport = null,
        public readonly ?int $idDocumentRequirement = null,
        public readonly ?int $idDocumentPhoto = null,
    ) {}

    public static function fromStdClass(\stdClass $obj): self
    {
        return new self(
            id: isset($obj->{'ID'}) ? (int) $obj->{'ID'} : null,
            idLogin: isset($obj->{'ID_Login'}) ? (string) $obj->{'ID_Login'} : null,
            idUnit: isset($obj->{'ID_Unit'}) ? (int) $obj->{'ID_Unit'} : null,
            unit: isset($obj->{'Unit'}) ? (string) $obj->{'Unit'} : null,
            registrationNumber: isset($obj->{'RegistrationNumber'}) ? (string) $obj->{'RegistrationNumber'} : null,
            idRealty: isset($obj->{'ID_Realty'}) ? (int) $obj->{'ID_Realty'} : null,
            realty: isset($obj->{'Realty'}) ? (string) $obj->{'Realty'} : null,
            idRealtyType: isset($obj->{'ID_RealtyType'}) ? (int) $obj->{'ID_RealtyType'} : null,
            realtyType: isset($obj->{'RealtyType'}) ? (string) $obj->{'RealtyType'} : null,
            publish: isset($obj->{'Publish'}) ? (bool) $obj->{'Publish'} : null,
            note: isset($obj->{'Note'}) ? (string) $obj->{'Note'} : null,
            isBorrowable: isset($obj->{'IsBorrowable'}) ? (bool) $obj->{'IsBorrowable'} : null,
            idOccupationRent: isset($obj->{'ID_OccupationRent'}) ? (int) $obj->{'ID_OccupationRent'} : null,
            displayName: isset($obj->{'DisplayName'}) ? (string) $obj->{'DisplayName'} : null,
            capacity: isset($obj->{'Capacity'}) ? (int) $obj->{'Capacity'} : null,
            capacityNote: isset($obj->{'CapacityNote'}) ? (string) $obj->{'CapacityNote'} : null,
            person: isset($obj->{'Person'}) ? (string) $obj->{'Person'} : null,
            email: isset($obj->{'Email'}) ? (string) $obj->{'Email'} : null,
            phone: isset($obj->{'Phone'}) ? (string) $obj->{'Phone'} : null,
            contactNote: isset($obj->{'ContactNote'}) ? (string) $obj->{'ContactNote'} : null,
            web: isset($obj->{'Web'}) ? (string) $obj->{'Web'} : null,
            requirementExtension: isset($obj->{'RequirementExtension'}) ? (string) $obj->{'RequirementExtension'} : null,
            requirements: isset($obj->{'Requirements'}) ? (string) $obj->{'Requirements'} : null,
            photoExtension: isset($obj->{'PhotoExtension'}) ? (string) $obj->{'PhotoExtension'} : null,
            fotogallery: isset($obj->{'Fotogallery'}) ? (string) $obj->{'Fotogallery'} : null,
            isBookable: isset($obj->{'IsBookable'}) ? (bool) $obj->{'IsBookable'} : null,
            bookUrl: isset($obj->{'BookUrl'}) ? (string) $obj->{'BookUrl'} : null,
            accommodationNote: isset($obj->{'AccommodationNote'}) ? (string) $obj->{'AccommodationNote'} : null,
            borrowableForeign: isset($obj->{'BorrowableForeign'}) ? (bool) $obj->{'BorrowableForeign'} : null,
            idRealtyCollection: isset($obj->{'ID_RealtyCollection'}) ? (int) $obj->{'ID_RealtyCollection'} : null,
            realtyCollection: isset($obj->{'RealtyCollection'}) ? (string) $obj->{'RealtyCollection'} : null,
            pointsOfInterest: isset($obj->{'PointsOfInterest'}) ? (string) $obj->{'PointsOfInterest'} : null,
            transportDescription: isset($obj->{'TransportDescription'}) ? (string) $obj->{'TransportDescription'} : null,
            idOwnerType: isset($obj->{'ID_OwnerType'}) ? (string) $obj->{'ID_OwnerType'} : null,
            ownerType: isset($obj->{'OwnerType'}) ? (string) $obj->{'OwnerType'} : null,
            idUnitRealty: isset($obj->{'ID_UnitRealty'}) ? (int) $obj->{'ID_UnitRealty'} : null,
            unitRealty: isset($obj->{'UnitRealty'}) ? (string) $obj->{'UnitRealty'} : null,
            registrationNumberRealty: isset($obj->{'RegistrationNumberRealty'}) ? (string) $obj->{'RegistrationNumberRealty'} : null,
            allEquipment: isset($obj->{'AllEquipment'}) ? (string) $obj->{'AllEquipment'} : null,
            allLanguages: isset($obj->{'AllLanguages'}) ? (string) $obj->{'AllLanguages'} : null,
            allTags: isset($obj->{'AllTags'}) ? (string) $obj->{'AllTags'} : null,
            allLocations: isset($obj->{'AllLocations'}) ? (string) $obj->{'AllLocations'} : null,
            allTransport: isset($obj->{'AllTransport'}) ? (string) $obj->{'AllTransport'} : null,
            idDocumentRequirement: isset($obj->{'ID_DocumentRequirement'}) ? (int) $obj->{'ID_DocumentRequirement'} : null,
            idDocumentPhoto: isset($obj->{'ID_DocumentPhoto'}) ? (int) $obj->{'ID_DocumentPhoto'} : null,
        );
    }
}
