<?php

namespace Misakstvanu\LaravelSkautis\Responses\OrganizationUnit;

final class OccupationRentDetailPublicApiOutput
{
    public function __construct(
        public readonly ?int $id = null,
        public readonly ?int $idOccupation = null,
        public readonly ?int $idRealty = null,
        public readonly ?int $idRealtyCollection = null,
        public readonly ?float $gpsLatitude = null,
        public readonly ?float $gpsLongitude = null,
        public readonly ?string $displayName = null,
        public readonly ?int $idRealtyType = null,
        public readonly ?string $realtyType = null,
        public readonly ?int $capacity = null,
        public readonly ?string $capacityNote = null,
        public readonly ?string $capacityType = null,
        public readonly ?string $email = null,
        public readonly ?string $street = null,
        public readonly ?string $city = null,
        public readonly ?string $postcode = null,
        public readonly ?string $contactPerson = null,
        public readonly ?string $contactPhone = null,
        public readonly ?string $contactNote = null,
        public readonly ?string $contactWeb = null,
        public readonly ?int $idDocumentRequirement = null,
        public readonly ?string $documentRequirement = null,
        public readonly ?string $requirementExtension = null,
        public readonly ?string $requirements = null,
        public readonly ?string $photogalleryUrl = null,
        public readonly ?string $calendarUrl = null,
        public readonly ?int $idDocumentRealty = null,
        public readonly ?int $idDocumentRealtyCollection = null,
        public readonly ?string $idLogin = null,
        public readonly ?int $idOccupationRent = null,
        public readonly ?string $occupationRent = null,
        public readonly ?string $idOccupationRentPriceType = null,
        public readonly ?string $occupationRentPriceType = null,
        public readonly ?int $basePrice = null,
        public readonly ?string $priceNote = null,
        public readonly ?int $scoutPrice = null,
        public readonly ?int $childPrice = null,
        public readonly ?string $realtyCollection = null,
        public readonly ?string $idRealtyLocation = null,
        public readonly ?string $realtyLocation = null,
        public readonly ?int $idOccupationEquipment = null,
        public readonly ?string $occupationEquipment = null,
        public readonly ?string $description = null,
        public readonly ?string $idOccupationLanguage = null,
        public readonly ?string $occupationLanguage = null,
        public readonly ?string $shortName = null,
        public readonly ?bool $isActive = null,
        public readonly ?string $phone = null,
        public readonly ?string $web = null,
        public readonly ?string $photoExtension = null,
        public readonly ?string $idTempFilePhotoExtension = null,
        public readonly ?string $fotogallery = null,
        public readonly ?string $idTempFileRequirementExtension = null,
        public readonly ?string $accommodationNote = null,
        public readonly ?bool $borrowableForeign = null,
        public readonly ?bool $isBookable = null,
        public readonly ?string $lastUpdate = null,
        public readonly ?string $person = null,
        public readonly ?int $idDocumentPhoto = null,
        public readonly ?int $idDocument = null,
        public readonly ?string $idTempFile = null,
    ) {}

    public static function fromStdClass(\stdClass $obj): self
    {
        return new self(
            id: isset($obj->{'ID'}) ? (int) $obj->{'ID'} : null,
            idOccupation: isset($obj->{'ID_Occupation'}) ? (int) $obj->{'ID_Occupation'} : null,
            idRealty: isset($obj->{'ID_Realty'}) ? (int) $obj->{'ID_Realty'} : null,
            idRealtyCollection: isset($obj->{'ID_RealtyCollection'}) ? (int) $obj->{'ID_RealtyCollection'} : null,
            gpsLatitude: isset($obj->{'GpsLatitude'}) ? (float) $obj->{'GpsLatitude'} : null,
            gpsLongitude: isset($obj->{'GpsLongitude'}) ? (float) $obj->{'GpsLongitude'} : null,
            displayName: isset($obj->{'DisplayName'}) ? (string) $obj->{'DisplayName'} : null,
            idRealtyType: isset($obj->{'ID_RealtyType'}) ? (int) $obj->{'ID_RealtyType'} : null,
            realtyType: isset($obj->{'RealtyType'}) ? (string) $obj->{'RealtyType'} : null,
            capacity: isset($obj->{'Capacity'}) ? (int) $obj->{'Capacity'} : null,
            capacityNote: isset($obj->{'CapacityNote'}) ? (string) $obj->{'CapacityNote'} : null,
            capacityType: isset($obj->{'CapacityType'}) ? (string) $obj->{'CapacityType'} : null,
            email: isset($obj->{'Email'}) ? (string) $obj->{'Email'} : null,
            street: isset($obj->{'Street'}) ? (string) $obj->{'Street'} : null,
            city: isset($obj->{'City'}) ? (string) $obj->{'City'} : null,
            postcode: isset($obj->{'Postcode'}) ? (string) $obj->{'Postcode'} : null,
            contactPerson: isset($obj->{'ContactPerson'}) ? (string) $obj->{'ContactPerson'} : null,
            contactPhone: isset($obj->{'ContactPhone'}) ? (string) $obj->{'ContactPhone'} : null,
            contactNote: isset($obj->{'ContactNote'}) ? (string) $obj->{'ContactNote'} : null,
            contactWeb: isset($obj->{'ContactWeb'}) ? (string) $obj->{'ContactWeb'} : null,
            idDocumentRequirement: isset($obj->{'ID_DocumentRequirement'}) ? (int) $obj->{'ID_DocumentRequirement'} : null,
            documentRequirement: isset($obj->{'DocumentRequirement'}) ? (string) $obj->{'DocumentRequirement'} : null,
            requirementExtension: isset($obj->{'RequirementExtension'}) ? (string) $obj->{'RequirementExtension'} : null,
            requirements: isset($obj->{'Requirements'}) ? (string) $obj->{'Requirements'} : null,
            photogalleryUrl: isset($obj->{'PhotogalleryUrl'}) ? (string) $obj->{'PhotogalleryUrl'} : null,
            calendarUrl: isset($obj->{'CalendarUrl'}) ? (string) $obj->{'CalendarUrl'} : null,
            idDocumentRealty: isset($obj->{'ID_DocumentRealty'}) ? (int) $obj->{'ID_DocumentRealty'} : null,
            idDocumentRealtyCollection: isset($obj->{'ID_DocumentRealtyCollection'}) ? (int) $obj->{'ID_DocumentRealtyCollection'} : null,
            idLogin: isset($obj->{'ID_Login'}) ? (string) $obj->{'ID_Login'} : null,
            idOccupationRent: isset($obj->{'ID_OccupationRent'}) ? (int) $obj->{'ID_OccupationRent'} : null,
            occupationRent: isset($obj->{'OccupationRent'}) ? (string) $obj->{'OccupationRent'} : null,
            idOccupationRentPriceType: isset($obj->{'ID_OccupationRentPriceType'}) ? (string) $obj->{'ID_OccupationRentPriceType'} : null,
            occupationRentPriceType: isset($obj->{'OccupationRentPriceType'}) ? (string) $obj->{'OccupationRentPriceType'} : null,
            basePrice: isset($obj->{'BasePrice'}) ? (int) $obj->{'BasePrice'} : null,
            priceNote: isset($obj->{'PriceNote'}) ? (string) $obj->{'PriceNote'} : null,
            scoutPrice: isset($obj->{'ScoutPrice'}) ? (int) $obj->{'ScoutPrice'} : null,
            childPrice: isset($obj->{'ChildPrice'}) ? (int) $obj->{'ChildPrice'} : null,
            realtyCollection: isset($obj->{'RealtyCollection'}) ? (string) $obj->{'RealtyCollection'} : null,
            idRealtyLocation: isset($obj->{'ID_RealtyLocation'}) ? (string) $obj->{'ID_RealtyLocation'} : null,
            realtyLocation: isset($obj->{'RealtyLocation'}) ? (string) $obj->{'RealtyLocation'} : null,
            idOccupationEquipment: isset($obj->{'ID_OccupationEquipment'}) ? (int) $obj->{'ID_OccupationEquipment'} : null,
            occupationEquipment: isset($obj->{'OccupationEquipment'}) ? (string) $obj->{'OccupationEquipment'} : null,
            description: isset($obj->{'Description'}) ? (string) $obj->{'Description'} : null,
            idOccupationLanguage: isset($obj->{'ID_OccupationLanguage'}) ? (string) $obj->{'ID_OccupationLanguage'} : null,
            occupationLanguage: isset($obj->{'OccupationLanguage'}) ? (string) $obj->{'OccupationLanguage'} : null,
            shortName: isset($obj->{'ShortName'}) ? (string) $obj->{'ShortName'} : null,
            isActive: isset($obj->{'IsActive'}) ? (bool) $obj->{'IsActive'} : null,
            phone: isset($obj->{'Phone'}) ? (string) $obj->{'Phone'} : null,
            web: isset($obj->{'Web'}) ? (string) $obj->{'Web'} : null,
            photoExtension: isset($obj->{'PhotoExtension'}) ? (string) $obj->{'PhotoExtension'} : null,
            idTempFilePhotoExtension: isset($obj->{'ID_TempFilePhotoExtension'}) ? (string) $obj->{'ID_TempFilePhotoExtension'} : null,
            fotogallery: isset($obj->{'Fotogallery'}) ? (string) $obj->{'Fotogallery'} : null,
            idTempFileRequirementExtension: isset($obj->{'ID_TempFileRequirementExtension'}) ? (string) $obj->{'ID_TempFileRequirementExtension'} : null,
            accommodationNote: isset($obj->{'AccommodationNote'}) ? (string) $obj->{'AccommodationNote'} : null,
            borrowableForeign: isset($obj->{'BorrowableForeign'}) ? (bool) $obj->{'BorrowableForeign'} : null,
            isBookable: isset($obj->{'IsBookable'}) ? (bool) $obj->{'IsBookable'} : null,
            lastUpdate: isset($obj->{'LastUpdate'}) ? (string) $obj->{'LastUpdate'} : null,
            person: isset($obj->{'Person'}) ? (string) $obj->{'Person'} : null,
            idDocumentPhoto: isset($obj->{'ID_DocumentPhoto'}) ? (int) $obj->{'ID_DocumentPhoto'} : null,
            idDocument: isset($obj->{'ID_Document'}) ? (int) $obj->{'ID_Document'} : null,
            idTempFile: isset($obj->{'ID_TempFile'}) ? (string) $obj->{'ID_TempFile'} : null,
        );
    }
}
