<?php

namespace Misakstvanu\LaravelSkautis\Responses\OrganizationUnit;

final class PersonChangeDetailOutput
{
    public function __construct(
        public readonly ?string $idLogin = null,
        public readonly ?int $id = null,
        public readonly ?int $idPerson = null,
        public readonly ?string $person = null,
        public readonly ?int $idUnit = null,
        public readonly ?string $unit = null,
        public readonly ?string $registrationNumber = null,
        public readonly ?string $code = null,
        public readonly ?string $validFrom = null,
        public readonly ?string $validTo = null,
        public readonly ?string $changed = null,
        public readonly ?string $finished = null,
        public readonly ?string $firstName = null,
        public readonly ?string $lastName = null,
        public readonly ?string $idSex = null,
        public readonly ?string $sex = null,
        public readonly ?string $birthday = null,
        public readonly ?string $identificationCode = null,
        public readonly ?bool $isForeign = null,
        public readonly ?string $address = null,
        public readonly ?string $street = null,
        public readonly ?string $city = null,
        public readonly ?string $postcode = null,
        public readonly ?string $state = null,
        public readonly ?string $postalFirstLine = null,
        public readonly ?string $postalAddress = null,
        public readonly ?string $postalStreet = null,
        public readonly ?string $postalCity = null,
        public readonly ?string $postalPostcode = null,
        public readonly ?string $postalState = null,
        public readonly ?string $phone = null,
        public readonly ?string $email = null,
        public readonly ?string $note = null,
        public readonly ?string $maidenName = null,
        public readonly ?string $idCitizenship = null,
        public readonly ?string $citizenship = null,
        public readonly ?string $citizenshipCustom = null,
        public readonly ?int $idDistrictBirth = null,
        public readonly ?string $districtBirth = null,
        public readonly ?string $birthCity = null,
        public readonly ?int $idPersonParentPerson = null,
        public readonly ?int $idPersonParent = null,
        public readonly ?string $idParentType = null,
        public readonly ?string $parentType = null,
        public readonly ?string $parentTypeCustom = null,
        public readonly ?string $firstNameParent = null,
        public readonly ?string $lastNameParent = null,
        public readonly ?string $parentPersonFirstName = null,
        public readonly ?string $parentPersonLastName = null,
        public readonly ?string $emailParent = null,
        public readonly ?string $phoneParent = null,
        public readonly ?string $noteParent = null,
        public readonly ?string $parentNote = null,
        public readonly ?int $idPersonParentPerson2 = null,
        public readonly ?int $idPersonParent2 = null,
        public readonly ?string $idParentType2 = null,
        public readonly ?string $parentType2 = null,
        public readonly ?string $parentTypeCustom2 = null,
        public readonly ?string $firstNameParent2 = null,
        public readonly ?string $lastNameParent2 = null,
        public readonly ?string $parent2PersonFirstName = null,
        public readonly ?string $parent2PersonLastName = null,
        public readonly ?string $emailParent2 = null,
        public readonly ?string $phoneParent2 = null,
        public readonly ?string $noteParent2 = null,
        public readonly ?string $parent2Note = null,
        public readonly ?int $idAssurance = null,
        public readonly ?string $assurance = null,
        public readonly ?string $insuranceNumber = null,
        public readonly ?string $allergy = null,
        public readonly ?string $foodRestrictions = null,
        public readonly ?string $drugs = null,
        public readonly ?string $specialRequirements = null,
        public readonly ?string $healthLimitation = null,
        public readonly ?string $bodySkills = null,
        public readonly ?string $school = null,
    ) {}

    public static function fromStdClass(\stdClass $obj): self
    {
        return new self(
            idLogin: isset($obj->{'ID_Login'}) ? (string) $obj->{'ID_Login'} : null,
            id: isset($obj->{'ID'}) ? (int) $obj->{'ID'} : null,
            idPerson: isset($obj->{'ID_Person'}) ? (int) $obj->{'ID_Person'} : null,
            person: isset($obj->{'Person'}) ? (string) $obj->{'Person'} : null,
            idUnit: isset($obj->{'ID_Unit'}) ? (int) $obj->{'ID_Unit'} : null,
            unit: isset($obj->{'Unit'}) ? (string) $obj->{'Unit'} : null,
            registrationNumber: isset($obj->{'RegistrationNumber'}) ? (string) $obj->{'RegistrationNumber'} : null,
            code: isset($obj->{'Code'}) ? (string) $obj->{'Code'} : null,
            validFrom: isset($obj->{'ValidFrom'}) ? (string) $obj->{'ValidFrom'} : null,
            validTo: isset($obj->{'ValidTo'}) ? (string) $obj->{'ValidTo'} : null,
            changed: isset($obj->{'Changed'}) ? (string) $obj->{'Changed'} : null,
            finished: isset($obj->{'Finished'}) ? (string) $obj->{'Finished'} : null,
            firstName: isset($obj->{'FirstName'}) ? (string) $obj->{'FirstName'} : null,
            lastName: isset($obj->{'LastName'}) ? (string) $obj->{'LastName'} : null,
            idSex: isset($obj->{'ID_Sex'}) ? (string) $obj->{'ID_Sex'} : null,
            sex: isset($obj->{'Sex'}) ? (string) $obj->{'Sex'} : null,
            birthday: isset($obj->{'Birthday'}) ? (string) $obj->{'Birthday'} : null,
            identificationCode: isset($obj->{'IdentificationCode'}) ? (string) $obj->{'IdentificationCode'} : null,
            isForeign: isset($obj->{'IsForeign'}) ? (bool) $obj->{'IsForeign'} : null,
            address: isset($obj->{'Address'}) ? (string) $obj->{'Address'} : null,
            street: isset($obj->{'Street'}) ? (string) $obj->{'Street'} : null,
            city: isset($obj->{'City'}) ? (string) $obj->{'City'} : null,
            postcode: isset($obj->{'Postcode'}) ? (string) $obj->{'Postcode'} : null,
            state: isset($obj->{'State'}) ? (string) $obj->{'State'} : null,
            postalFirstLine: isset($obj->{'PostalFirstLine'}) ? (string) $obj->{'PostalFirstLine'} : null,
            postalAddress: isset($obj->{'PostalAddress'}) ? (string) $obj->{'PostalAddress'} : null,
            postalStreet: isset($obj->{'PostalStreet'}) ? (string) $obj->{'PostalStreet'} : null,
            postalCity: isset($obj->{'PostalCity'}) ? (string) $obj->{'PostalCity'} : null,
            postalPostcode: isset($obj->{'PostalPostcode'}) ? (string) $obj->{'PostalPostcode'} : null,
            postalState: isset($obj->{'PostalState'}) ? (string) $obj->{'PostalState'} : null,
            phone: isset($obj->{'Phone'}) ? (string) $obj->{'Phone'} : null,
            email: isset($obj->{'Email'}) ? (string) $obj->{'Email'} : null,
            note: isset($obj->{'Note'}) ? (string) $obj->{'Note'} : null,
            maidenName: isset($obj->{'MaidenName'}) ? (string) $obj->{'MaidenName'} : null,
            idCitizenship: isset($obj->{'ID_Citizenship'}) ? (string) $obj->{'ID_Citizenship'} : null,
            citizenship: isset($obj->{'Citizenship'}) ? (string) $obj->{'Citizenship'} : null,
            citizenshipCustom: isset($obj->{'CitizenshipCustom'}) ? (string) $obj->{'CitizenshipCustom'} : null,
            idDistrictBirth: isset($obj->{'ID_DistrictBirth'}) ? (int) $obj->{'ID_DistrictBirth'} : null,
            districtBirth: isset($obj->{'DistrictBirth'}) ? (string) $obj->{'DistrictBirth'} : null,
            birthCity: isset($obj->{'BirthCity'}) ? (string) $obj->{'BirthCity'} : null,
            idPersonParentPerson: isset($obj->{'ID_PersonParentPerson'}) ? (int) $obj->{'ID_PersonParentPerson'} : null,
            idPersonParent: isset($obj->{'ID_PersonParent'}) ? (int) $obj->{'ID_PersonParent'} : null,
            idParentType: isset($obj->{'ID_ParentType'}) ? (string) $obj->{'ID_ParentType'} : null,
            parentType: isset($obj->{'ParentType'}) ? (string) $obj->{'ParentType'} : null,
            parentTypeCustom: isset($obj->{'ParentTypeCustom'}) ? (string) $obj->{'ParentTypeCustom'} : null,
            firstNameParent: isset($obj->{'FirstNameParent'}) ? (string) $obj->{'FirstNameParent'} : null,
            lastNameParent: isset($obj->{'LastNameParent'}) ? (string) $obj->{'LastNameParent'} : null,
            parentPersonFirstName: isset($obj->{'ParentPersonFirstName'}) ? (string) $obj->{'ParentPersonFirstName'} : null,
            parentPersonLastName: isset($obj->{'ParentPersonLastName'}) ? (string) $obj->{'ParentPersonLastName'} : null,
            emailParent: isset($obj->{'EmailParent'}) ? (string) $obj->{'EmailParent'} : null,
            phoneParent: isset($obj->{'PhoneParent'}) ? (string) $obj->{'PhoneParent'} : null,
            noteParent: isset($obj->{'NoteParent'}) ? (string) $obj->{'NoteParent'} : null,
            parentNote: isset($obj->{'ParentNote'}) ? (string) $obj->{'ParentNote'} : null,
            idPersonParentPerson2: isset($obj->{'ID_PersonParentPerson2'}) ? (int) $obj->{'ID_PersonParentPerson2'} : null,
            idPersonParent2: isset($obj->{'ID_PersonParent2'}) ? (int) $obj->{'ID_PersonParent2'} : null,
            idParentType2: isset($obj->{'ID_ParentType2'}) ? (string) $obj->{'ID_ParentType2'} : null,
            parentType2: isset($obj->{'ParentType2'}) ? (string) $obj->{'ParentType2'} : null,
            parentTypeCustom2: isset($obj->{'ParentTypeCustom2'}) ? (string) $obj->{'ParentTypeCustom2'} : null,
            firstNameParent2: isset($obj->{'FirstNameParent2'}) ? (string) $obj->{'FirstNameParent2'} : null,
            lastNameParent2: isset($obj->{'LastNameParent2'}) ? (string) $obj->{'LastNameParent2'} : null,
            parent2PersonFirstName: isset($obj->{'Parent2PersonFirstName'}) ? (string) $obj->{'Parent2PersonFirstName'} : null,
            parent2PersonLastName: isset($obj->{'Parent2PersonLastName'}) ? (string) $obj->{'Parent2PersonLastName'} : null,
            emailParent2: isset($obj->{'EmailParent2'}) ? (string) $obj->{'EmailParent2'} : null,
            phoneParent2: isset($obj->{'PhoneParent2'}) ? (string) $obj->{'PhoneParent2'} : null,
            noteParent2: isset($obj->{'NoteParent2'}) ? (string) $obj->{'NoteParent2'} : null,
            parent2Note: isset($obj->{'Parent2Note'}) ? (string) $obj->{'Parent2Note'} : null,
            idAssurance: isset($obj->{'ID_Assurance'}) ? (int) $obj->{'ID_Assurance'} : null,
            assurance: isset($obj->{'Assurance'}) ? (string) $obj->{'Assurance'} : null,
            insuranceNumber: isset($obj->{'InsuranceNumber'}) ? (string) $obj->{'InsuranceNumber'} : null,
            allergy: isset($obj->{'Allergy'}) ? (string) $obj->{'Allergy'} : null,
            foodRestrictions: isset($obj->{'FoodRestrictions'}) ? (string) $obj->{'FoodRestrictions'} : null,
            drugs: isset($obj->{'Drugs'}) ? (string) $obj->{'Drugs'} : null,
            specialRequirements: isset($obj->{'SpecialRequirements'}) ? (string) $obj->{'SpecialRequirements'} : null,
            healthLimitation: isset($obj->{'HealthLimitation'}) ? (string) $obj->{'HealthLimitation'} : null,
            bodySkills: isset($obj->{'BodySkills'}) ? (string) $obj->{'BodySkills'} : null,
            school: isset($obj->{'School'}) ? (string) $obj->{'School'} : null,
        );
    }
}
