<?php

namespace Misakstvanu\LaravelSkautis\Responses\OrganizationUnit;

final class PersonDetailOutput
{
    public function __construct(
        public readonly ?string $idLogin = null,
        public readonly ?int $id = null,
        public readonly ?string $displayName = null,
        public readonly ?string $degreeInFrontOf = null,
        public readonly ?string $degreeBehind = null,
        public readonly ?string $securityCode = null,
        public readonly ?string $identificationCode = null,
        public readonly ?bool $identificationCodeHasPermission = null,
        public readonly ?string $fullName = null,
        public readonly ?string $firstName = null,
        public readonly ?string $lastName = null,
        public readonly ?string $nickName = null,
        public readonly ?string $address = null,
        public readonly ?string $street = null,
        public readonly ?string $city = null,
        public readonly ?string $postcode = null,
        public readonly ?string $state = null,
        public readonly ?string $postalFirstLine = null,
        public readonly ?string $postalAddress = null,
        public readonly ?string $postalStreet = null,
        public readonly ?string $postalCity = null,
        public readonly ?string $postalPostcode = null,
        public readonly ?string $postalState = null,
        public readonly ?string $note = null,
        public readonly ?string $idSex = null,
        public readonly ?string $sex = null,
        public readonly ?string $birthday = null,
        public readonly ?int $birthdayYear = null,
        public readonly ?bool $isForeign = null,
        public readonly ?int $yearFrom = null,
        public readonly ?string $registrationNumber = null,
        public readonly ?int $idUser = null,
        public readonly ?bool $generateSecurityCode = null,
        public readonly ?bool $onlyValidate = null,
        public readonly ?string $photoExtension = null,
        public readonly ?string $photoContent = null,
        public readonly ?string $photoUpdate = null,
        public readonly ?string $maidenName = null,
        public readonly ?string $idPersonType = null,
        public readonly ?string $personType = null,
        public readonly ?string $email = null,
        public readonly ?string $school = null,
        public readonly ?bool $displayAdress = null,
        public readonly ?bool $displayBirthday = null,
        public readonly ?bool $displayEducation = null,
        public readonly ?bool $displayEducationSeminary = null,
        public readonly ?bool $displayFunction = null,
        public readonly ?bool $displayMembership = null,
        public readonly ?bool $displayOffer = null,
        public readonly ?bool $displayPostalAdress = null,
        public readonly ?bool $displaySchool = null,
        public readonly ?bool $displayQualification = null,
        public readonly ?bool $displayYearFrom = null,
        public readonly ?bool $catalogDisplay = null,
        public readonly ?int $catalogContactCount = null,
        public readonly ?int $idPersonContactGa = null,
        public readonly ?string $personContactGa = null,
        public readonly ?int $idMemberCard = null,
        public readonly ?int $photoX = null,
        public readonly ?int $photoY = null,
        public readonly ?int $photoSize = null,
        public readonly ?bool $isPostalAuthenticated = null,
        public readonly ?bool $isAddressAuthenticated = null,
        public readonly ?string $addressDistrict = null,
        public readonly ?string $postalDistrict = null,
        public readonly ?string $unitEnrollExtension = null,
        public readonly ?string $unitEnroll = null,
        public readonly ?bool $rejectDataStorage = null,
        public readonly ?bool $hasMembership = null,
        public readonly ?bool $isLegacyMemberRead = null,
        public readonly ?int $idPersonOther = null,
        public readonly ?bool $hasEnroll = null,
        public readonly ?string $phone = null,
        public readonly ?string $name = null,
        public readonly ?int $idPersonPhotoBig = null,
        public readonly ?int $idPersonPhotoMedium = null,
        public readonly ?int $idPersonPhotoNormal = null,
        public readonly ?int $idPersonPhotoSmall = null,
        public readonly ?bool $isForeignAddress = null,
        public readonly ?int $idUnitEnrollTempFile = null,
        public readonly ?string $emailParent = null,
        public readonly ?string $dateParentAgreement = null,
        public readonly ?string $firstNameParent = null,
        public readonly ?string $lastNameParent = null,
        public readonly ?bool $needParentAgreement = null,
        public readonly ?bool $isTwoFactorEnabled = null,
        public readonly ?string $twoFactorEnabled = null,
        public readonly ?int $idMembershipApplicationUnaccepted = null,
        public readonly ?string $parentCode = null,
        public readonly ?bool $isAdult = null,
        public readonly ?bool $canReadPersonBasic = null,
        public readonly ?int $age = null,
        public readonly ?bool $hasOldPhoto = null,
    ) {}

    public static function fromStdClass(\stdClass $obj): self
    {
        return new self(
            idLogin: isset($obj->{'ID_Login'}) ? (string) $obj->{'ID_Login'} : null,
            id: isset($obj->{'ID'}) ? (int) $obj->{'ID'} : null,
            displayName: isset($obj->{'DisplayName'}) ? (string) $obj->{'DisplayName'} : null,
            degreeInFrontOf: isset($obj->{'DegreeInFrontOf'}) ? (string) $obj->{'DegreeInFrontOf'} : null,
            degreeBehind: isset($obj->{'DegreeBehind'}) ? (string) $obj->{'DegreeBehind'} : null,
            securityCode: isset($obj->{'SecurityCode'}) ? (string) $obj->{'SecurityCode'} : null,
            identificationCode: isset($obj->{'IdentificationCode'}) ? (string) $obj->{'IdentificationCode'} : null,
            identificationCodeHasPermission: isset($obj->{'IdentificationCodeHasPermission'}) ? (bool) $obj->{'IdentificationCodeHasPermission'} : null,
            fullName: isset($obj->{'FullName'}) ? (string) $obj->{'FullName'} : null,
            firstName: isset($obj->{'FirstName'}) ? (string) $obj->{'FirstName'} : null,
            lastName: isset($obj->{'LastName'}) ? (string) $obj->{'LastName'} : null,
            nickName: isset($obj->{'NickName'}) ? (string) $obj->{'NickName'} : null,
            address: isset($obj->{'Address'}) ? (string) $obj->{'Address'} : null,
            street: isset($obj->{'Street'}) ? (string) $obj->{'Street'} : null,
            city: isset($obj->{'City'}) ? (string) $obj->{'City'} : null,
            postcode: isset($obj->{'Postcode'}) ? (string) $obj->{'Postcode'} : null,
            state: isset($obj->{'State'}) ? (string) $obj->{'State'} : null,
            postalFirstLine: isset($obj->{'PostalFirstLine'}) ? (string) $obj->{'PostalFirstLine'} : null,
            postalAddress: isset($obj->{'PostalAddress'}) ? (string) $obj->{'PostalAddress'} : null,
            postalStreet: isset($obj->{'PostalStreet'}) ? (string) $obj->{'PostalStreet'} : null,
            postalCity: isset($obj->{'PostalCity'}) ? (string) $obj->{'PostalCity'} : null,
            postalPostcode: isset($obj->{'PostalPostcode'}) ? (string) $obj->{'PostalPostcode'} : null,
            postalState: isset($obj->{'PostalState'}) ? (string) $obj->{'PostalState'} : null,
            note: isset($obj->{'Note'}) ? (string) $obj->{'Note'} : null,
            idSex: isset($obj->{'ID_Sex'}) ? (string) $obj->{'ID_Sex'} : null,
            sex: isset($obj->{'Sex'}) ? (string) $obj->{'Sex'} : null,
            birthday: isset($obj->{'Birthday'}) ? (string) $obj->{'Birthday'} : null,
            birthdayYear: isset($obj->{'BirthdayYear'}) ? (int) $obj->{'BirthdayYear'} : null,
            isForeign: isset($obj->{'IsForeign'}) ? (bool) $obj->{'IsForeign'} : null,
            yearFrom: isset($obj->{'YearFrom'}) ? (int) $obj->{'YearFrom'} : null,
            registrationNumber: isset($obj->{'RegistrationNumber'}) ? (string) $obj->{'RegistrationNumber'} : null,
            idUser: isset($obj->{'ID_User'}) ? (int) $obj->{'ID_User'} : null,
            generateSecurityCode: isset($obj->{'GenerateSecurityCode'}) ? (bool) $obj->{'GenerateSecurityCode'} : null,
            onlyValidate: isset($obj->{'OnlyValidate'}) ? (bool) $obj->{'OnlyValidate'} : null,
            photoExtension: isset($obj->{'PhotoExtension'}) ? (string) $obj->{'PhotoExtension'} : null,
            photoContent: isset($obj->{'PhotoContent'}) ? (string) $obj->{'PhotoContent'} : null,
            photoUpdate: isset($obj->{'PhotoUpdate'}) ? (string) $obj->{'PhotoUpdate'} : null,
            maidenName: isset($obj->{'MaidenName'}) ? (string) $obj->{'MaidenName'} : null,
            idPersonType: isset($obj->{'ID_PersonType'}) ? (string) $obj->{'ID_PersonType'} : null,
            personType: isset($obj->{'PersonType'}) ? (string) $obj->{'PersonType'} : null,
            email: isset($obj->{'Email'}) ? (string) $obj->{'Email'} : null,
            school: isset($obj->{'School'}) ? (string) $obj->{'School'} : null,
            displayAdress: isset($obj->{'DisplayAdress'}) ? (bool) $obj->{'DisplayAdress'} : null,
            displayBirthday: isset($obj->{'DisplayBirthday'}) ? (bool) $obj->{'DisplayBirthday'} : null,
            displayEducation: isset($obj->{'DisplayEducation'}) ? (bool) $obj->{'DisplayEducation'} : null,
            displayEducationSeminary: isset($obj->{'DisplayEducationSeminary'}) ? (bool) $obj->{'DisplayEducationSeminary'} : null,
            displayFunction: isset($obj->{'DisplayFunction'}) ? (bool) $obj->{'DisplayFunction'} : null,
            displayMembership: isset($obj->{'DisplayMembership'}) ? (bool) $obj->{'DisplayMembership'} : null,
            displayOffer: isset($obj->{'DisplayOffer'}) ? (bool) $obj->{'DisplayOffer'} : null,
            displayPostalAdress: isset($obj->{'DisplayPostalAdress'}) ? (bool) $obj->{'DisplayPostalAdress'} : null,
            displaySchool: isset($obj->{'DisplaySchool'}) ? (bool) $obj->{'DisplaySchool'} : null,
            displayQualification: isset($obj->{'DisplayQualification'}) ? (bool) $obj->{'DisplayQualification'} : null,
            displayYearFrom: isset($obj->{'DisplayYearFrom'}) ? (bool) $obj->{'DisplayYearFrom'} : null,
            catalogDisplay: isset($obj->{'CatalogDisplay'}) ? (bool) $obj->{'CatalogDisplay'} : null,
            catalogContactCount: isset($obj->{'CatalogContactCount'}) ? (int) $obj->{'CatalogContactCount'} : null,
            idPersonContactGa: isset($obj->{'ID_PersonContactGa'}) ? (int) $obj->{'ID_PersonContactGa'} : null,
            personContactGa: isset($obj->{'PersonContactGa'}) ? (string) $obj->{'PersonContactGa'} : null,
            idMemberCard: isset($obj->{'ID_MemberCard'}) ? (int) $obj->{'ID_MemberCard'} : null,
            photoX: isset($obj->{'PhotoX'}) ? (int) $obj->{'PhotoX'} : null,
            photoY: isset($obj->{'PhotoY'}) ? (int) $obj->{'PhotoY'} : null,
            photoSize: isset($obj->{'PhotoSize'}) ? (int) $obj->{'PhotoSize'} : null,
            isPostalAuthenticated: isset($obj->{'IsPostalAuthenticated'}) ? (bool) $obj->{'IsPostalAuthenticated'} : null,
            isAddressAuthenticated: isset($obj->{'IsAddressAuthenticated'}) ? (bool) $obj->{'IsAddressAuthenticated'} : null,
            addressDistrict: isset($obj->{'AddressDistrict'}) ? (string) $obj->{'AddressDistrict'} : null,
            postalDistrict: isset($obj->{'PostalDistrict'}) ? (string) $obj->{'PostalDistrict'} : null,
            unitEnrollExtension: isset($obj->{'UnitEnrollExtension'}) ? (string) $obj->{'UnitEnrollExtension'} : null,
            unitEnroll: isset($obj->{'UnitEnroll'}) ? (string) $obj->{'UnitEnroll'} : null,
            rejectDataStorage: isset($obj->{'RejectDataStorage'}) ? (bool) $obj->{'RejectDataStorage'} : null,
            hasMembership: isset($obj->{'HasMembership'}) ? (bool) $obj->{'HasMembership'} : null,
            isLegacyMemberRead: isset($obj->{'IsLegacyMemberRead'}) ? (bool) $obj->{'IsLegacyMemberRead'} : null,
            idPersonOther: isset($obj->{'ID_PersonOther'}) ? (int) $obj->{'ID_PersonOther'} : null,
            hasEnroll: isset($obj->{'HasEnroll'}) ? (bool) $obj->{'HasEnroll'} : null,
            phone: isset($obj->{'Phone'}) ? (string) $obj->{'Phone'} : null,
            name: isset($obj->{'Name'}) ? (string) $obj->{'Name'} : null,
            idPersonPhotoBig: isset($obj->{'ID_PersonPhotoBig'}) ? (int) $obj->{'ID_PersonPhotoBig'} : null,
            idPersonPhotoMedium: isset($obj->{'ID_PersonPhotoMedium'}) ? (int) $obj->{'ID_PersonPhotoMedium'} : null,
            idPersonPhotoNormal: isset($obj->{'ID_PersonPhotoNormal'}) ? (int) $obj->{'ID_PersonPhotoNormal'} : null,
            idPersonPhotoSmall: isset($obj->{'ID_PersonPhotoSmall'}) ? (int) $obj->{'ID_PersonPhotoSmall'} : null,
            isForeignAddress: isset($obj->{'IsForeignAddress'}) ? (bool) $obj->{'IsForeignAddress'} : null,
            idUnitEnrollTempFile: isset($obj->{'ID_UnitEnrollTempFile'}) ? (int) $obj->{'ID_UnitEnrollTempFile'} : null,
            emailParent: isset($obj->{'EmailParent'}) ? (string) $obj->{'EmailParent'} : null,
            dateParentAgreement: isset($obj->{'DateParentAgreement'}) ? (string) $obj->{'DateParentAgreement'} : null,
            firstNameParent: isset($obj->{'FirstNameParent'}) ? (string) $obj->{'FirstNameParent'} : null,
            lastNameParent: isset($obj->{'LastNameParent'}) ? (string) $obj->{'LastNameParent'} : null,
            needParentAgreement: isset($obj->{'NeedParentAgreement'}) ? (bool) $obj->{'NeedParentAgreement'} : null,
            isTwoFactorEnabled: isset($obj->{'IsTwoFactorEnabled'}) ? (bool) $obj->{'IsTwoFactorEnabled'} : null,
            twoFactorEnabled: isset($obj->{'TwoFactorEnabled'}) ? (string) $obj->{'TwoFactorEnabled'} : null,
            idMembershipApplicationUnaccepted: isset($obj->{'ID_MembershipApplicationUnaccepted'}) ? (int) $obj->{'ID_MembershipApplicationUnaccepted'} : null,
            parentCode: isset($obj->{'ParentCode'}) ? (string) $obj->{'ParentCode'} : null,
            isAdult: isset($obj->{'IsAdult'}) ? (bool) $obj->{'IsAdult'} : null,
            canReadPersonBasic: isset($obj->{'CanReadPersonBasic'}) ? (bool) $obj->{'CanReadPersonBasic'} : null,
            age: isset($obj->{'Age'}) ? (int) $obj->{'Age'} : null,
            hasOldPhoto: isset($obj->{'HasOldPhoto'}) ? (bool) $obj->{'HasOldPhoto'} : null,
        );
    }
}
