<?php

namespace Misakstvanu\LaravelSkautis\Responses\OrganizationUnit;

final class PersonOtherDetailOutput
{
    public function __construct(
        public readonly ?string $idLogin = null,
        public readonly ?int $id = null,
        public readonly ?int $idPerson = null,
        public readonly ?string $birthCity = null,
        public readonly ?string $idCitizenship = null,
        public readonly ?string $citizenship = null,
        public readonly ?string $citizenshipCustom = null,
        public readonly ?string $person = null,
        public readonly ?string $maidenName = null,
        public readonly ?int $idDistrictBirth = null,
        public readonly ?string $districtBirth = null,
        public readonly ?int $idAssurance = null,
        public readonly ?string $assurance = null,
        public readonly ?string $insuranceNumber = null,
        public readonly ?string $allergy = null,
        public readonly ?string $foodRestrictions = null,
        public readonly ?string $drugs = null,
        public readonly ?string $specialRequirements = null,
        public readonly ?string $healthLimitation = null,
        public readonly ?string $bodySkills = null,
        public readonly ?string $school = null,
        public readonly ?string $note = null,
        public readonly ?string $parentNote = null,
        public readonly ?bool $allowDataStorage = null,
        public readonly ?bool $allowAudiovisual = null,
        public readonly ?bool $allowSocialNetwork = null,
        public readonly ?bool $allowMarketing = null,
        public readonly ?string $dateChangeSocialNetwork = null,
        public readonly ?string $dateChangeMarketing = null,
        public readonly ?string $dateChangeDataStorage = null,
        public readonly ?string $dateChangeAudiovisual = null,
        public readonly ?bool $isRPS = null,
        public readonly ?bool $isEPS = null,
        public readonly ?bool $isEduParticipantExt = null,
        public readonly ?bool $onlyValidate = null,
        public readonly ?int $idEventCongress = null,
        public readonly ?string $idTempFileHealth = null,
        public readonly ?int $idDocumentHealth = null,
        public readonly ?string $idCardNumber = null,
        public readonly ?string $idCardValidTo = null,
        public readonly ?bool $isAdult = null,
        public readonly ?bool $isNonMemberWithGoogleServicesAccess = null,
        public readonly ?string $promiseChild = null,
        public readonly ?string $promiseScout = null,
        public readonly ?string $promiseOfficial = null,
        public readonly ?string $trailProgress = null,
    ) {}

    public static function fromStdClass(\stdClass $obj): self
    {
        return new self(
            idLogin: isset($obj->{'ID_Login'}) ? (string) $obj->{'ID_Login'} : null,
            id: isset($obj->{'ID'}) ? (int) $obj->{'ID'} : null,
            idPerson: isset($obj->{'ID_Person'}) ? (int) $obj->{'ID_Person'} : null,
            birthCity: isset($obj->{'BirthCity'}) ? (string) $obj->{'BirthCity'} : null,
            idCitizenship: isset($obj->{'ID_Citizenship'}) ? (string) $obj->{'ID_Citizenship'} : null,
            citizenship: isset($obj->{'Citizenship'}) ? (string) $obj->{'Citizenship'} : null,
            citizenshipCustom: isset($obj->{'CitizenshipCustom'}) ? (string) $obj->{'CitizenshipCustom'} : null,
            person: isset($obj->{'Person'}) ? (string) $obj->{'Person'} : null,
            maidenName: isset($obj->{'MaidenName'}) ? (string) $obj->{'MaidenName'} : null,
            idDistrictBirth: isset($obj->{'ID_DistrictBirth'}) ? (int) $obj->{'ID_DistrictBirth'} : null,
            districtBirth: isset($obj->{'DistrictBirth'}) ? (string) $obj->{'DistrictBirth'} : null,
            idAssurance: isset($obj->{'ID_Assurance'}) ? (int) $obj->{'ID_Assurance'} : null,
            assurance: isset($obj->{'Assurance'}) ? (string) $obj->{'Assurance'} : null,
            insuranceNumber: isset($obj->{'InsuranceNumber'}) ? (string) $obj->{'InsuranceNumber'} : null,
            allergy: isset($obj->{'Allergy'}) ? (string) $obj->{'Allergy'} : null,
            foodRestrictions: isset($obj->{'FoodRestrictions'}) ? (string) $obj->{'FoodRestrictions'} : null,
            drugs: isset($obj->{'Drugs'}) ? (string) $obj->{'Drugs'} : null,
            specialRequirements: isset($obj->{'SpecialRequirements'}) ? (string) $obj->{'SpecialRequirements'} : null,
            healthLimitation: isset($obj->{'HealthLimitation'}) ? (string) $obj->{'HealthLimitation'} : null,
            bodySkills: isset($obj->{'BodySkills'}) ? (string) $obj->{'BodySkills'} : null,
            school: isset($obj->{'School'}) ? (string) $obj->{'School'} : null,
            note: isset($obj->{'Note'}) ? (string) $obj->{'Note'} : null,
            parentNote: isset($obj->{'ParentNote'}) ? (string) $obj->{'ParentNote'} : null,
            allowDataStorage: isset($obj->{'AllowDataStorage'}) ? (bool) $obj->{'AllowDataStorage'} : null,
            allowAudiovisual: isset($obj->{'AllowAudiovisual'}) ? (bool) $obj->{'AllowAudiovisual'} : null,
            allowSocialNetwork: isset($obj->{'AllowSocialNetwork'}) ? (bool) $obj->{'AllowSocialNetwork'} : null,
            allowMarketing: isset($obj->{'AllowMarketing'}) ? (bool) $obj->{'AllowMarketing'} : null,
            dateChangeSocialNetwork: isset($obj->{'DateChangeSocialNetwork'}) ? (string) $obj->{'DateChangeSocialNetwork'} : null,
            dateChangeMarketing: isset($obj->{'DateChangeMarketing'}) ? (string) $obj->{'DateChangeMarketing'} : null,
            dateChangeDataStorage: isset($obj->{'DateChangeDataStorage'}) ? (string) $obj->{'DateChangeDataStorage'} : null,
            dateChangeAudiovisual: isset($obj->{'DateChangeAudiovisual'}) ? (string) $obj->{'DateChangeAudiovisual'} : null,
            isRPS: isset($obj->{'IsRPS'}) ? (bool) $obj->{'IsRPS'} : null,
            isEPS: isset($obj->{'IsEPS'}) ? (bool) $obj->{'IsEPS'} : null,
            isEduParticipantExt: isset($obj->{'IsEduParticipantExt'}) ? (bool) $obj->{'IsEduParticipantExt'} : null,
            onlyValidate: isset($obj->{'OnlyValidate'}) ? (bool) $obj->{'OnlyValidate'} : null,
            idEventCongress: isset($obj->{'ID_EventCongress'}) ? (int) $obj->{'ID_EventCongress'} : null,
            idTempFileHealth: isset($obj->{'ID_TempFileHealth'}) ? (string) $obj->{'ID_TempFileHealth'} : null,
            idDocumentHealth: isset($obj->{'ID_DocumentHealth'}) ? (int) $obj->{'ID_DocumentHealth'} : null,
            idCardNumber: isset($obj->{'IdCardNumber'}) ? (string) $obj->{'IdCardNumber'} : null,
            idCardValidTo: isset($obj->{'IdCardValidTo'}) ? (string) $obj->{'IdCardValidTo'} : null,
            isAdult: isset($obj->{'IsAdult'}) ? (bool) $obj->{'IsAdult'} : null,
            isNonMemberWithGoogleServicesAccess: isset($obj->{'IsNonMemberWithGoogleServicesAccess'}) ? (bool) $obj->{'IsNonMemberWithGoogleServicesAccess'} : null,
            promiseChild: isset($obj->{'PromiseChild'}) ? (string) $obj->{'PromiseChild'} : null,
            promiseScout: isset($obj->{'PromiseScout'}) ? (string) $obj->{'PromiseScout'} : null,
            promiseOfficial: isset($obj->{'PromiseOfficial'}) ? (string) $obj->{'PromiseOfficial'} : null,
            trailProgress: isset($obj->{'TrailProgress'}) ? (string) $obj->{'TrailProgress'} : null,
        );
    }
}
