<?php

namespace Misakstvanu\LaravelSkautis\Responses\OrganizationUnit;

final class RealtyDetailPhotoOutput
{
    public function __construct(
        public readonly ?string $idLogin = null,
        public readonly ?int $id = null,
        public readonly ?string $displayName = null,
        public readonly ?int $idRealtyType = null,
        public readonly ?string $realtyType = null,
        public readonly ?string $street = null,
        public readonly ?string $city = null,
        public readonly ?string $postcode = null,
        public readonly ?float $gpsLatitude = null,
        public readonly ?float $gpsLongitude = null,
        public readonly ?string $description = null,
        public readonly ?string $note = null,
        public readonly ?int $idRealtyCollection = null,
        public readonly ?string $realtyCollection = null,
        public readonly ?string $idOwnerType = null,
        public readonly ?string $ownerType = null,
        public readonly ?string $ownerTypeNote = null,
        public readonly ?bool $isPower = null,
        public readonly ?string $validTo = null,
        public readonly ?bool $isActive = null,
        public readonly ?string $photoExtension = null,
        public readonly ?string $photoFileContent = null,
        public readonly ?string $idTempFilePhoto = null,
        public readonly ?string $fotogalleryUrl = null,
        public readonly ?bool $isAddressAuthenticated = null,
        public readonly ?string $district = null,
        public readonly ?string $storage = null,
        public readonly ?int $idDocument = null,
        public readonly ?string $parcelNumber = null,
        public readonly ?string $registerCity = null,
        public readonly ?string $cadastralArea = null,
        public readonly ?int $lVNumber = null,
        public readonly ?int $acreage = null,
        public readonly ?string $parcelType = null,
        public readonly ?string $landType = null,
        public readonly ?string $unit = null,
        public readonly ?string $unitRegistrationNumber = null,
        public readonly ?float $realtyGpsLatitude = null,
        public readonly ?float $realtyGpsLongitude = null,
        public readonly ?int $coordinateX = null,
        public readonly ?int $coordinateY = null,
    ) {}

    public static function fromStdClass(\stdClass $obj): self
    {
        return new self(
            idLogin: isset($obj->{'ID_Login'}) ? (string) $obj->{'ID_Login'} : null,
            id: isset($obj->{'ID'}) ? (int) $obj->{'ID'} : null,
            displayName: isset($obj->{'DisplayName'}) ? (string) $obj->{'DisplayName'} : null,
            idRealtyType: isset($obj->{'ID_RealtyType'}) ? (int) $obj->{'ID_RealtyType'} : null,
            realtyType: isset($obj->{'RealtyType'}) ? (string) $obj->{'RealtyType'} : null,
            street: isset($obj->{'Street'}) ? (string) $obj->{'Street'} : null,
            city: isset($obj->{'City'}) ? (string) $obj->{'City'} : null,
            postcode: isset($obj->{'Postcode'}) ? (string) $obj->{'Postcode'} : null,
            gpsLatitude: isset($obj->{'GpsLatitude'}) ? (float) $obj->{'GpsLatitude'} : null,
            gpsLongitude: isset($obj->{'GpsLongitude'}) ? (float) $obj->{'GpsLongitude'} : null,
            description: isset($obj->{'Description'}) ? (string) $obj->{'Description'} : null,
            note: isset($obj->{'Note'}) ? (string) $obj->{'Note'} : null,
            idRealtyCollection: isset($obj->{'ID_RealtyCollection'}) ? (int) $obj->{'ID_RealtyCollection'} : null,
            realtyCollection: isset($obj->{'RealtyCollection'}) ? (string) $obj->{'RealtyCollection'} : null,
            idOwnerType: isset($obj->{'ID_OwnerType'}) ? (string) $obj->{'ID_OwnerType'} : null,
            ownerType: isset($obj->{'OwnerType'}) ? (string) $obj->{'OwnerType'} : null,
            ownerTypeNote: isset($obj->{'OwnerTypeNote'}) ? (string) $obj->{'OwnerTypeNote'} : null,
            isPower: isset($obj->{'IsPower'}) ? (bool) $obj->{'IsPower'} : null,
            validTo: isset($obj->{'ValidTo'}) ? (string) $obj->{'ValidTo'} : null,
            isActive: isset($obj->{'IsActive'}) ? (bool) $obj->{'IsActive'} : null,
            photoExtension: isset($obj->{'PhotoExtension'}) ? (string) $obj->{'PhotoExtension'} : null,
            photoFileContent: isset($obj->{'PhotoFileContent'}) ? (string) $obj->{'PhotoFileContent'} : null,
            idTempFilePhoto: isset($obj->{'ID_TempFilePhoto'}) ? (string) $obj->{'ID_TempFilePhoto'} : null,
            fotogalleryUrl: isset($obj->{'FotogalleryUrl'}) ? (string) $obj->{'FotogalleryUrl'} : null,
            isAddressAuthenticated: isset($obj->{'IsAddressAuthenticated'}) ? (bool) $obj->{'IsAddressAuthenticated'} : null,
            district: isset($obj->{'District'}) ? (string) $obj->{'District'} : null,
            storage: isset($obj->{'Storage'}) ? (string) $obj->{'Storage'} : null,
            idDocument: isset($obj->{'ID_Document'}) ? (int) $obj->{'ID_Document'} : null,
            parcelNumber: isset($obj->{'ParcelNumber'}) ? (string) $obj->{'ParcelNumber'} : null,
            registerCity: isset($obj->{'RegisterCity'}) ? (string) $obj->{'RegisterCity'} : null,
            cadastralArea: isset($obj->{'CadastralArea'}) ? (string) $obj->{'CadastralArea'} : null,
            lVNumber: isset($obj->{'LVNumber'}) ? (int) $obj->{'LVNumber'} : null,
            acreage: isset($obj->{'Acreage'}) ? (int) $obj->{'Acreage'} : null,
            parcelType: isset($obj->{'ParcelType'}) ? (string) $obj->{'ParcelType'} : null,
            landType: isset($obj->{'LandType'}) ? (string) $obj->{'LandType'} : null,
            unit: isset($obj->{'Unit'}) ? (string) $obj->{'Unit'} : null,
            unitRegistrationNumber: isset($obj->{'UnitRegistrationNumber'}) ? (string) $obj->{'UnitRegistrationNumber'} : null,
            realtyGpsLatitude: isset($obj->{'RealtyGpsLatitude'}) ? (float) $obj->{'RealtyGpsLatitude'} : null,
            realtyGpsLongitude: isset($obj->{'RealtyGpsLongitude'}) ? (float) $obj->{'RealtyGpsLongitude'} : null,
            coordinateX: isset($obj->{'CoordinateX'}) ? (int) $obj->{'CoordinateX'} : null,
            coordinateY: isset($obj->{'CoordinateY'}) ? (int) $obj->{'CoordinateY'} : null,
        );
    }
}
