<?php

namespace Misakstvanu\LaravelSkautis\Responses\OrganizationUnit;

final class RegistryDetailOutput
{
    public function __construct(
        public readonly ?string $idLogin = null,
        public readonly ?int $id = null,
        public readonly ?string $displayName = null,
        public readonly ?int $sequence = null,
        public readonly ?int $idUnit = null,
        public readonly ?string $unit = null,
        public readonly ?string $registrationNumber = null,
        public readonly ?string $iC = null,
        public readonly ?string $street = null,
        public readonly ?string $city = null,
        public readonly ?string $postcode = null,
        public readonly ?bool $isPropertyOwner = null,
        public readonly ?string $propertyAgreementExtension = null,
        public readonly ?string $unitOld = null,
        public readonly ?string $streetOld = null,
        public readonly ?string $cityOld = null,
        public readonly ?string $postcodeOld = null,
        public readonly ?bool $isPropertyOwnerOld = null,
        public readonly ?string $idRegistryObject = null,
        public readonly ?string $registryObject = null,
        public readonly ?string $idRegistryType = null,
        public readonly ?string $registryType = null,
        public readonly ?string $idRegistryState = null,
        public readonly ?string $registryState = null,
        public readonly ?int $oldHistoryObjectId = null,
        public readonly ?int $newHistoryObjectId = null,
        public readonly ?int $idPersonCreate = null,
        public readonly ?string $personCreate = null,
        public readonly ?string $dateCreate = null,
        public readonly ?int $idPersonUpdate = null,
        public readonly ?string $personUpdate = null,
        public readonly ?string $dateUpdate = null,
        public readonly ?int $idPersonSent = null,
        public readonly ?string $personSent = null,
        public readonly ?string $dateSent = null,
        public readonly ?int $idPersonClosed = null,
        public readonly ?string $personClosed = null,
        public readonly ?string $dateClosed = null,
        public readonly ?int $idPersonCancel = null,
        public readonly ?string $personCancel = null,
        public readonly ?string $dateCancel = null,
        public readonly ?string $cancelDecision = null,
        public readonly ?int $idFunction = null,
        public readonly ?int $idFunctionType = null,
        public readonly ?string $functionType = null,
        public readonly ?string $personFunction = null,
        public readonly ?string $personFunctionOld = null,
        public readonly ?string $account = null,
        public readonly ?bool $newAccount = null,
        public readonly ?int $idPersonFunction = null,
        public readonly ?int $idPersonFunctionOld = null,
        public readonly ?string $note = null,
        public readonly ?int $idPersonSolving = null,
        public readonly ?string $personSolving = null,
        public readonly ?string $dateSolving = null,
        public readonly ?int $idDocument = null,
        public readonly ?int $idStatement = null,
        public readonly ?int $statementYear = null,
        public readonly ?int $idDocumentStatement = null,
        public readonly ?string $decisionSeatChangeExtension = null,
        public readonly ?int $idDocumentDecision = null,
        public readonly ?int $idDocumentPropertyAgreement = null,
    ) {}

    public static function fromStdClass(\stdClass $obj): self
    {
        return new self(
            idLogin: isset($obj->{'ID_Login'}) ? (string) $obj->{'ID_Login'} : null,
            id: isset($obj->{'ID'}) ? (int) $obj->{'ID'} : null,
            displayName: isset($obj->{'DisplayName'}) ? (string) $obj->{'DisplayName'} : null,
            sequence: isset($obj->{'Sequence'}) ? (int) $obj->{'Sequence'} : null,
            idUnit: isset($obj->{'ID_Unit'}) ? (int) $obj->{'ID_Unit'} : null,
            unit: isset($obj->{'Unit'}) ? (string) $obj->{'Unit'} : null,
            registrationNumber: isset($obj->{'RegistrationNumber'}) ? (string) $obj->{'RegistrationNumber'} : null,
            iC: isset($obj->{'IC'}) ? (string) $obj->{'IC'} : null,
            street: isset($obj->{'Street'}) ? (string) $obj->{'Street'} : null,
            city: isset($obj->{'City'}) ? (string) $obj->{'City'} : null,
            postcode: isset($obj->{'Postcode'}) ? (string) $obj->{'Postcode'} : null,
            isPropertyOwner: isset($obj->{'IsPropertyOwner'}) ? (bool) $obj->{'IsPropertyOwner'} : null,
            propertyAgreementExtension: isset($obj->{'PropertyAgreementExtension'}) ? (string) $obj->{'PropertyAgreementExtension'} : null,
            unitOld: isset($obj->{'UnitOld'}) ? (string) $obj->{'UnitOld'} : null,
            streetOld: isset($obj->{'StreetOld'}) ? (string) $obj->{'StreetOld'} : null,
            cityOld: isset($obj->{'CityOld'}) ? (string) $obj->{'CityOld'} : null,
            postcodeOld: isset($obj->{'PostcodeOld'}) ? (string) $obj->{'PostcodeOld'} : null,
            isPropertyOwnerOld: isset($obj->{'IsPropertyOwnerOld'}) ? (bool) $obj->{'IsPropertyOwnerOld'} : null,
            idRegistryObject: isset($obj->{'ID_RegistryObject'}) ? (string) $obj->{'ID_RegistryObject'} : null,
            registryObject: isset($obj->{'RegistryObject'}) ? (string) $obj->{'RegistryObject'} : null,
            idRegistryType: isset($obj->{'ID_RegistryType'}) ? (string) $obj->{'ID_RegistryType'} : null,
            registryType: isset($obj->{'RegistryType'}) ? (string) $obj->{'RegistryType'} : null,
            idRegistryState: isset($obj->{'ID_RegistryState'}) ? (string) $obj->{'ID_RegistryState'} : null,
            registryState: isset($obj->{'RegistryState'}) ? (string) $obj->{'RegistryState'} : null,
            oldHistoryObjectId: isset($obj->{'OldHistoryObjectId'}) ? (int) $obj->{'OldHistoryObjectId'} : null,
            newHistoryObjectId: isset($obj->{'NewHistoryObjectId'}) ? (int) $obj->{'NewHistoryObjectId'} : null,
            idPersonCreate: isset($obj->{'ID_PersonCreate'}) ? (int) $obj->{'ID_PersonCreate'} : null,
            personCreate: isset($obj->{'PersonCreate'}) ? (string) $obj->{'PersonCreate'} : null,
            dateCreate: isset($obj->{'DateCreate'}) ? (string) $obj->{'DateCreate'} : null,
            idPersonUpdate: isset($obj->{'ID_PersonUpdate'}) ? (int) $obj->{'ID_PersonUpdate'} : null,
            personUpdate: isset($obj->{'PersonUpdate'}) ? (string) $obj->{'PersonUpdate'} : null,
            dateUpdate: isset($obj->{'DateUpdate'}) ? (string) $obj->{'DateUpdate'} : null,
            idPersonSent: isset($obj->{'ID_PersonSent'}) ? (int) $obj->{'ID_PersonSent'} : null,
            personSent: isset($obj->{'PersonSent'}) ? (string) $obj->{'PersonSent'} : null,
            dateSent: isset($obj->{'DateSent'}) ? (string) $obj->{'DateSent'} : null,
            idPersonClosed: isset($obj->{'ID_PersonClosed'}) ? (int) $obj->{'ID_PersonClosed'} : null,
            personClosed: isset($obj->{'PersonClosed'}) ? (string) $obj->{'PersonClosed'} : null,
            dateClosed: isset($obj->{'DateClosed'}) ? (string) $obj->{'DateClosed'} : null,
            idPersonCancel: isset($obj->{'ID_PersonCancel'}) ? (int) $obj->{'ID_PersonCancel'} : null,
            personCancel: isset($obj->{'PersonCancel'}) ? (string) $obj->{'PersonCancel'} : null,
            dateCancel: isset($obj->{'DateCancel'}) ? (string) $obj->{'DateCancel'} : null,
            cancelDecision: isset($obj->{'CancelDecision'}) ? (string) $obj->{'CancelDecision'} : null,
            idFunction: isset($obj->{'ID_Function'}) ? (int) $obj->{'ID_Function'} : null,
            idFunctionType: isset($obj->{'ID_FunctionType'}) ? (int) $obj->{'ID_FunctionType'} : null,
            functionType: isset($obj->{'FunctionType'}) ? (string) $obj->{'FunctionType'} : null,
            personFunction: isset($obj->{'PersonFunction'}) ? (string) $obj->{'PersonFunction'} : null,
            personFunctionOld: isset($obj->{'PersonFunctionOld'}) ? (string) $obj->{'PersonFunctionOld'} : null,
            account: isset($obj->{'Account'}) ? (string) $obj->{'Account'} : null,
            newAccount: isset($obj->{'NewAccount'}) ? (bool) $obj->{'NewAccount'} : null,
            idPersonFunction: isset($obj->{'ID_PersonFunction'}) ? (int) $obj->{'ID_PersonFunction'} : null,
            idPersonFunctionOld: isset($obj->{'ID_PersonFunctionOld'}) ? (int) $obj->{'ID_PersonFunctionOld'} : null,
            note: isset($obj->{'Note'}) ? (string) $obj->{'Note'} : null,
            idPersonSolving: isset($obj->{'ID_PersonSolving'}) ? (int) $obj->{'ID_PersonSolving'} : null,
            personSolving: isset($obj->{'PersonSolving'}) ? (string) $obj->{'PersonSolving'} : null,
            dateSolving: isset($obj->{'DateSolving'}) ? (string) $obj->{'DateSolving'} : null,
            idDocument: isset($obj->{'ID_Document'}) ? (int) $obj->{'ID_Document'} : null,
            idStatement: isset($obj->{'ID_Statement'}) ? (int) $obj->{'ID_Statement'} : null,
            statementYear: isset($obj->{'StatementYear'}) ? (int) $obj->{'StatementYear'} : null,
            idDocumentStatement: isset($obj->{'ID_DocumentStatement'}) ? (int) $obj->{'ID_DocumentStatement'} : null,
            decisionSeatChangeExtension: isset($obj->{'DecisionSeatChangeExtension'}) ? (string) $obj->{'DecisionSeatChangeExtension'} : null,
            idDocumentDecision: isset($obj->{'ID_DocumentDecision'}) ? (int) $obj->{'ID_DocumentDecision'} : null,
            idDocumentPropertyAgreement: isset($obj->{'ID_DocumentPropertyAgreement'}) ? (int) $obj->{'ID_DocumentPropertyAgreement'} : null,
        );
    }
}
