<?php

namespace Misakstvanu\LaravelSkautis\Responses\OrganizationUnit;

final class UnitDetailShopDiscountOutput
{
    public function __construct(
        public readonly ?string $idLogin = null,
        public readonly ?int $id = null,
        public readonly ?int $idGroup = null,
        public readonly ?int $idUnit = null,
        public readonly ?string $idUnitType = null,
        public readonly ?string $unitType = null,
        public readonly ?bool $containsMembers = null,
        public readonly ?int $commissionDeadline = null,
        public readonly ?string $displayName = null,
        public readonly ?string $sortName = null,
        public readonly ?string $registrationNumber = null,
        public readonly ?string $shortRegistrationNumber = null,
        public readonly ?string $location = null,
        public readonly ?string $locationNew = null,
        public readonly ?string $iC = null,
        public readonly ?bool $isVatPayer = null,
        public readonly ?string $dIC = null,
        public readonly ?string $fileReference = null,
        public readonly ?string $street = null,
        public readonly ?string $city = null,
        public readonly ?string $postcode = null,
        public readonly ?string $state = null,
        public readonly ?string $postalFirstLine = null,
        public readonly ?string $postalStreet = null,
        public readonly ?string $postalCity = null,
        public readonly ?string $postalPostcode = null,
        public readonly ?string $postalState = null,
        public readonly ?string $note = null,
        public readonly ?int $idTroopArt = null,
        public readonly ?string $troopArt = null,
        public readonly ?bool $canUpdateRegistrationNumber = null,
        public readonly ?string $logoContent = null,
        public readonly ?string $logoExtension = null,
        public readonly ?int $idDocumentLogo = null,
        public readonly ?bool $isUnitCancel = null,
        public readonly ?bool $journalParent = null,
        public readonly ?bool $changeFreeJournal = null,
        public readonly ?int $idUnitParent = null,
        public readonly ?bool $onlyValidate = null,
        public readonly ?bool $isPostalAuthenticated = null,
        public readonly ?bool $isAddressAuthenticated = null,
        public readonly ?string $addressDistrict = null,
        public readonly ?string $postalDistrict = null,
        public readonly ?string $newDisplayName = null,
        public readonly ?string $completeDisplayName = null,
        public readonly ?int $idPersonChangeName = null,
        public readonly ?string $personChangeName = null,
        public readonly ?string $dateChangeName = null,
        public readonly ?bool $isPropertyOwner = null,
        public readonly ?string $propertyAgreementExtension = null,
        public readonly ?string $idTempFilePropertyAgreement = null,
        public readonly ?string $propertyAgreementContent = null,
        public readonly ?string $troopArtKey = null,
        public readonly ?string $idJournalNovice = null,
        public readonly ?string $idJournalDeliveryType = null,
        public readonly ?string $fullDisplayName = null,
        public readonly ?int $idDocumentDecision = null,
        public readonly ?int $idDocumentPropertyAgreement = null,
        public readonly ?string $decisionSeatChangeExtension = null,
        public readonly ?string $shopDiscountBarcode = null,
        public readonly ?string $idTempFileSeatChange = null,
        public readonly ?string $idUnitFoundReason = null,
        public readonly ?string $unitFoundReason = null,
        public readonly ?string $unitFoundDescription = null,
        public readonly ?string $idTempFileUnitLogo = null,
    ) {}

    public static function fromStdClass(\stdClass $obj): self
    {
        return new self(
            idLogin: isset($obj->{'ID_Login'}) ? (string) $obj->{'ID_Login'} : null,
            id: isset($obj->{'ID'}) ? (int) $obj->{'ID'} : null,
            idGroup: isset($obj->{'ID_Group'}) ? (int) $obj->{'ID_Group'} : null,
            idUnit: isset($obj->{'ID_Unit'}) ? (int) $obj->{'ID_Unit'} : null,
            idUnitType: isset($obj->{'ID_UnitType'}) ? (string) $obj->{'ID_UnitType'} : null,
            unitType: isset($obj->{'UnitType'}) ? (string) $obj->{'UnitType'} : null,
            containsMembers: isset($obj->{'ContainsMembers'}) ? (bool) $obj->{'ContainsMembers'} : null,
            commissionDeadline: isset($obj->{'CommissionDeadline'}) ? (int) $obj->{'CommissionDeadline'} : null,
            displayName: isset($obj->{'DisplayName'}) ? (string) $obj->{'DisplayName'} : null,
            sortName: isset($obj->{'SortName'}) ? (string) $obj->{'SortName'} : null,
            registrationNumber: isset($obj->{'RegistrationNumber'}) ? (string) $obj->{'RegistrationNumber'} : null,
            shortRegistrationNumber: isset($obj->{'ShortRegistrationNumber'}) ? (string) $obj->{'ShortRegistrationNumber'} : null,
            location: isset($obj->{'Location'}) ? (string) $obj->{'Location'} : null,
            locationNew: isset($obj->{'LocationNew'}) ? (string) $obj->{'LocationNew'} : null,
            iC: isset($obj->{'IC'}) ? (string) $obj->{'IC'} : null,
            isVatPayer: isset($obj->{'IsVatPayer'}) ? (bool) $obj->{'IsVatPayer'} : null,
            dIC: isset($obj->{'DIC'}) ? (string) $obj->{'DIC'} : null,
            fileReference: isset($obj->{'FileReference'}) ? (string) $obj->{'FileReference'} : null,
            street: isset($obj->{'Street'}) ? (string) $obj->{'Street'} : null,
            city: isset($obj->{'City'}) ? (string) $obj->{'City'} : null,
            postcode: isset($obj->{'Postcode'}) ? (string) $obj->{'Postcode'} : null,
            state: isset($obj->{'State'}) ? (string) $obj->{'State'} : null,
            postalFirstLine: isset($obj->{'PostalFirstLine'}) ? (string) $obj->{'PostalFirstLine'} : null,
            postalStreet: isset($obj->{'PostalStreet'}) ? (string) $obj->{'PostalStreet'} : null,
            postalCity: isset($obj->{'PostalCity'}) ? (string) $obj->{'PostalCity'} : null,
            postalPostcode: isset($obj->{'PostalPostcode'}) ? (string) $obj->{'PostalPostcode'} : null,
            postalState: isset($obj->{'PostalState'}) ? (string) $obj->{'PostalState'} : null,
            note: isset($obj->{'Note'}) ? (string) $obj->{'Note'} : null,
            idTroopArt: isset($obj->{'ID_TroopArt'}) ? (int) $obj->{'ID_TroopArt'} : null,
            troopArt: isset($obj->{'TroopArt'}) ? (string) $obj->{'TroopArt'} : null,
            canUpdateRegistrationNumber: isset($obj->{'CanUpdateRegistrationNumber'}) ? (bool) $obj->{'CanUpdateRegistrationNumber'} : null,
            logoContent: isset($obj->{'LogoContent'}) ? (string) $obj->{'LogoContent'} : null,
            logoExtension: isset($obj->{'LogoExtension'}) ? (string) $obj->{'LogoExtension'} : null,
            idDocumentLogo: isset($obj->{'ID_DocumentLogo'}) ? (int) $obj->{'ID_DocumentLogo'} : null,
            isUnitCancel: isset($obj->{'IsUnitCancel'}) ? (bool) $obj->{'IsUnitCancel'} : null,
            journalParent: isset($obj->{'JournalParent'}) ? (bool) $obj->{'JournalParent'} : null,
            changeFreeJournal: isset($obj->{'ChangeFreeJournal'}) ? (bool) $obj->{'ChangeFreeJournal'} : null,
            idUnitParent: isset($obj->{'ID_UnitParent'}) ? (int) $obj->{'ID_UnitParent'} : null,
            onlyValidate: isset($obj->{'OnlyValidate'}) ? (bool) $obj->{'OnlyValidate'} : null,
            isPostalAuthenticated: isset($obj->{'IsPostalAuthenticated'}) ? (bool) $obj->{'IsPostalAuthenticated'} : null,
            isAddressAuthenticated: isset($obj->{'IsAddressAuthenticated'}) ? (bool) $obj->{'IsAddressAuthenticated'} : null,
            addressDistrict: isset($obj->{'AddressDistrict'}) ? (string) $obj->{'AddressDistrict'} : null,
            postalDistrict: isset($obj->{'PostalDistrict'}) ? (string) $obj->{'PostalDistrict'} : null,
            newDisplayName: isset($obj->{'NewDisplayName'}) ? (string) $obj->{'NewDisplayName'} : null,
            completeDisplayName: isset($obj->{'CompleteDisplayName'}) ? (string) $obj->{'CompleteDisplayName'} : null,
            idPersonChangeName: isset($obj->{'ID_PersonChangeName'}) ? (int) $obj->{'ID_PersonChangeName'} : null,
            personChangeName: isset($obj->{'PersonChangeName'}) ? (string) $obj->{'PersonChangeName'} : null,
            dateChangeName: isset($obj->{'DateChangeName'}) ? (string) $obj->{'DateChangeName'} : null,
            isPropertyOwner: isset($obj->{'IsPropertyOwner'}) ? (bool) $obj->{'IsPropertyOwner'} : null,
            propertyAgreementExtension: isset($obj->{'PropertyAgreementExtension'}) ? (string) $obj->{'PropertyAgreementExtension'} : null,
            idTempFilePropertyAgreement: isset($obj->{'ID_TempFilePropertyAgreement'}) ? (string) $obj->{'ID_TempFilePropertyAgreement'} : null,
            propertyAgreementContent: isset($obj->{'PropertyAgreementContent'}) ? (string) $obj->{'PropertyAgreementContent'} : null,
            troopArtKey: isset($obj->{'TroopArtKey'}) ? (string) $obj->{'TroopArtKey'} : null,
            idJournalNovice: isset($obj->{'ID_JournalNovice'}) ? (string) $obj->{'ID_JournalNovice'} : null,
            idJournalDeliveryType: isset($obj->{'ID_JournalDeliveryType'}) ? (string) $obj->{'ID_JournalDeliveryType'} : null,
            fullDisplayName: isset($obj->{'FullDisplayName'}) ? (string) $obj->{'FullDisplayName'} : null,
            idDocumentDecision: isset($obj->{'ID_DocumentDecision'}) ? (int) $obj->{'ID_DocumentDecision'} : null,
            idDocumentPropertyAgreement: isset($obj->{'ID_DocumentPropertyAgreement'}) ? (int) $obj->{'ID_DocumentPropertyAgreement'} : null,
            decisionSeatChangeExtension: isset($obj->{'DecisionSeatChangeExtension'}) ? (string) $obj->{'DecisionSeatChangeExtension'} : null,
            shopDiscountBarcode: isset($obj->{'ShopDiscountBarcode'}) ? (string) $obj->{'ShopDiscountBarcode'} : null,
            idTempFileSeatChange: isset($obj->{'ID_TempFileSeatChange'}) ? (string) $obj->{'ID_TempFileSeatChange'} : null,
            idUnitFoundReason: isset($obj->{'ID_UnitFoundReason'}) ? (string) $obj->{'ID_UnitFoundReason'} : null,
            unitFoundReason: isset($obj->{'UnitFoundReason'}) ? (string) $obj->{'UnitFoundReason'} : null,
            unitFoundDescription: isset($obj->{'UnitFoundDescription'}) ? (string) $obj->{'UnitFoundDescription'} : null,
            idTempFileUnitLogo: isset($obj->{'ID_TempFileUnitLogo'}) ? (string) $obj->{'ID_TempFileUnitLogo'} : null,
        );
    }
}
