<?php

namespace Misakstvanu\LaravelSkautis\Responses\Material;

final class WarehouseItemAllOutput
{
    public function __construct(
        public readonly ?int $id = null,
        public readonly ?string $displayName = null,
        public readonly ?int $idWarehouse = null,
        public readonly ?string $warehouse = null,
        public readonly ?string $idWarehouseItemCategory = null,
        public readonly ?string $warehouseItemCategory = null,
        public readonly ?string $inventoryNumber = null,
        public readonly ?string $description = null,
        public readonly ?string $photoExtension = null,
        public readonly ?string $purchaseDate = null,
        public readonly ?int $purchaseYear = null,
        public readonly ?string $idPurchaseType = null,
        public readonly ?string $purchaseType = null,
        public readonly ?string $purchaseNote = null,
        public readonly ?string $serialNumber = null,
        public readonly ?string $sails = null,
        public readonly ?string $accountNumber = null,
        public readonly ?float $purchasePrice = null,
        public readonly ?float $actualPrice = null,
        public readonly ?string $deletionDate = null,
        public readonly ?bool $isDiscarded = null,
        public readonly ?string $deletionNote = null,
        public readonly ?bool $eventRent = null,
        public readonly ?bool $unitRent = null,
        public readonly ?bool $commercialRent = null,
        public readonly ?float $rentPrice = null,
        public readonly ?string $rentNote = null,
        public readonly ?string $note = null,
        public readonly ?bool $inWarehouse = null,
        public readonly ?string $warehouseRentNote = null,
        public readonly ?string $inventoryDate = null,
        public readonly ?string $inventoryNote = null,
        public readonly ?string $warehouseTag = null,
        public readonly ?int $idDocument = null,
        public readonly ?string $storage = null,
        public readonly ?int $idDocumentSmall = null,
        public readonly ?int $idDocumentBig = null,
    ) {}

    public static function fromStdClass(\stdClass $obj): self
    {
        return new self(
            id: isset($obj->{'ID'}) ? (int) $obj->{'ID'} : null,
            displayName: isset($obj->{'DisplayName'}) ? (string) $obj->{'DisplayName'} : null,
            idWarehouse: isset($obj->{'ID_Warehouse'}) ? (int) $obj->{'ID_Warehouse'} : null,
            warehouse: isset($obj->{'Warehouse'}) ? (string) $obj->{'Warehouse'} : null,
            idWarehouseItemCategory: isset($obj->{'ID_WarehouseItemCategory'}) ? (string) $obj->{'ID_WarehouseItemCategory'} : null,
            warehouseItemCategory: isset($obj->{'WarehouseItemCategory'}) ? (string) $obj->{'WarehouseItemCategory'} : null,
            inventoryNumber: isset($obj->{'InventoryNumber'}) ? (string) $obj->{'InventoryNumber'} : null,
            description: isset($obj->{'Description'}) ? (string) $obj->{'Description'} : null,
            photoExtension: isset($obj->{'PhotoExtension'}) ? (string) $obj->{'PhotoExtension'} : null,
            purchaseDate: isset($obj->{'PurchaseDate'}) ? (string) $obj->{'PurchaseDate'} : null,
            purchaseYear: isset($obj->{'PurchaseYear'}) ? (int) $obj->{'PurchaseYear'} : null,
            idPurchaseType: isset($obj->{'ID_PurchaseType'}) ? (string) $obj->{'ID_PurchaseType'} : null,
            purchaseType: isset($obj->{'PurchaseType'}) ? (string) $obj->{'PurchaseType'} : null,
            purchaseNote: isset($obj->{'PurchaseNote'}) ? (string) $obj->{'PurchaseNote'} : null,
            serialNumber: isset($obj->{'SerialNumber'}) ? (string) $obj->{'SerialNumber'} : null,
            sails: isset($obj->{'Sails'}) ? (string) $obj->{'Sails'} : null,
            accountNumber: isset($obj->{'AccountNumber'}) ? (string) $obj->{'AccountNumber'} : null,
            purchasePrice: isset($obj->{'PurchasePrice'}) ? (float) $obj->{'PurchasePrice'} : null,
            actualPrice: isset($obj->{'ActualPrice'}) ? (float) $obj->{'ActualPrice'} : null,
            deletionDate: isset($obj->{'DeletionDate'}) ? (string) $obj->{'DeletionDate'} : null,
            isDiscarded: isset($obj->{'IsDiscarded'}) ? (bool) $obj->{'IsDiscarded'} : null,
            deletionNote: isset($obj->{'DeletionNote'}) ? (string) $obj->{'DeletionNote'} : null,
            eventRent: isset($obj->{'EventRent'}) ? (bool) $obj->{'EventRent'} : null,
            unitRent: isset($obj->{'UnitRent'}) ? (bool) $obj->{'UnitRent'} : null,
            commercialRent: isset($obj->{'CommercialRent'}) ? (bool) $obj->{'CommercialRent'} : null,
            rentPrice: isset($obj->{'RentPrice'}) ? (float) $obj->{'RentPrice'} : null,
            rentNote: isset($obj->{'RentNote'}) ? (string) $obj->{'RentNote'} : null,
            note: isset($obj->{'Note'}) ? (string) $obj->{'Note'} : null,
            inWarehouse: isset($obj->{'InWarehouse'}) ? (bool) $obj->{'InWarehouse'} : null,
            warehouseRentNote: isset($obj->{'WarehouseRentNote'}) ? (string) $obj->{'WarehouseRentNote'} : null,
            inventoryDate: isset($obj->{'InventoryDate'}) ? (string) $obj->{'InventoryDate'} : null,
            inventoryNote: isset($obj->{'InventoryNote'}) ? (string) $obj->{'InventoryNote'} : null,
            warehouseTag: isset($obj->{'WarehouseTag'}) ? (string) $obj->{'WarehouseTag'} : null,
            idDocument: isset($obj->{'ID_Document'}) ? (int) $obj->{'ID_Document'} : null,
            storage: isset($obj->{'Storage'}) ? (string) $obj->{'Storage'} : null,
            idDocumentSmall: isset($obj->{'ID_DocumentSmall'}) ? (int) $obj->{'ID_DocumentSmall'} : null,
            idDocumentBig: isset($obj->{'ID_DocumentBig'}) ? (int) $obj->{'ID_DocumentBig'} : null,
        );
    }
}
