<?php

namespace Misakstvanu\LaravelSkautis\Responses\Exports;

final class ExportGooogleAllOutput
{
    public function __construct(
        public readonly ?string $dateRun = null,
        public readonly ?string $changes = null,
        public readonly ?string $code = null,
        public readonly ?bool $isCodeChanged = null,
        public readonly ?string $displayName = null,
        public readonly ?bool $isDisplayNameChanged = null,
        public readonly ?string $firstLine = null,
        public readonly ?bool $isFirstLineChanged = null,
        public readonly ?string $secondLine = null,
        public readonly ?bool $isSecondLineChanged = null,
        public readonly ?string $city = null,
        public readonly ?bool $isCityChanged = null,
        public readonly ?string $district = null,
        public readonly ?bool $isDistrictChanged = null,
        public readonly ?string $state = null,
        public readonly ?bool $isStateChanged = null,
        public readonly ?string $country = null,
        public readonly ?bool $isCountryChanged = null,
        public readonly ?string $postcode = null,
        public readonly ?bool $isPostcodeChanged = null,
        public readonly ?string $mainPhone = null,
        public readonly ?bool $isMainPhoneChanged = null,
        public readonly ?string $homePage = null,
        public readonly ?bool $isHomePageChanged = null,
        public readonly ?string $category = null,
        public readonly ?bool $isCategoryChanged = null,
        public readonly ?string $businessHours = null,
        public readonly ?bool $isBusinessHoursChanged = null,
        public readonly ?float $latitude = null,
        public readonly ?bool $isLatitudeChanged = null,
        public readonly ?float $longitude = null,
        public readonly ?bool $isLongitudeChanged = null,
        public readonly ?string $picture = null,
        public readonly ?bool $isPictureChanged = null,
        public readonly ?string $description = null,
        public readonly ?bool $isDescriptionChanged = null,
        public readonly ?string $email = null,
        public readonly ?bool $isEmailChanged = null,
        public readonly ?string $alternativePhone = null,
        public readonly ?bool $isAlternativePhoneChanged = null,
        public readonly ?string $mobilePhone = null,
        public readonly ?bool $isMobilePhoneChanged = null,
        public readonly ?string $fax = null,
        public readonly ?bool $isFaxChanged = null,
        public readonly ?string $paymentType = null,
        public readonly ?bool $isPaymentTypeChanged = null,
        public readonly ?string $advertiseIcon = null,
        public readonly ?bool $isAdvertiseIconChanged = null,
        public readonly ?string $advertisePhone = null,
        public readonly ?bool $isAdvertisePhoneChanged = null,
        public readonly ?string $advertiseUrl = null,
        public readonly ?bool $isAdvertiseUrlChanged = null,
        public readonly ?string $outOfLength = null,
        public readonly ?string $notes = null,
    ) {}

    public static function fromStdClass(\stdClass $obj): self
    {
        return new self(
            dateRun: isset($obj->{'DateRun'}) ? (string) $obj->{'DateRun'} : null,
            changes: isset($obj->{'Changes'}) ? (string) $obj->{'Changes'} : null,
            code: isset($obj->{'Code'}) ? (string) $obj->{'Code'} : null,
            isCodeChanged: isset($obj->{'IsCodeChanged'}) ? (bool) $obj->{'IsCodeChanged'} : null,
            displayName: isset($obj->{'DisplayName'}) ? (string) $obj->{'DisplayName'} : null,
            isDisplayNameChanged: isset($obj->{'IsDisplayNameChanged'}) ? (bool) $obj->{'IsDisplayNameChanged'} : null,
            firstLine: isset($obj->{'FirstLine'}) ? (string) $obj->{'FirstLine'} : null,
            isFirstLineChanged: isset($obj->{'IsFirstLineChanged'}) ? (bool) $obj->{'IsFirstLineChanged'} : null,
            secondLine: isset($obj->{'SecondLine'}) ? (string) $obj->{'SecondLine'} : null,
            isSecondLineChanged: isset($obj->{'IsSecondLineChanged'}) ? (bool) $obj->{'IsSecondLineChanged'} : null,
            city: isset($obj->{'City'}) ? (string) $obj->{'City'} : null,
            isCityChanged: isset($obj->{'IsCityChanged'}) ? (bool) $obj->{'IsCityChanged'} : null,
            district: isset($obj->{'District'}) ? (string) $obj->{'District'} : null,
            isDistrictChanged: isset($obj->{'IsDistrictChanged'}) ? (bool) $obj->{'IsDistrictChanged'} : null,
            state: isset($obj->{'State'}) ? (string) $obj->{'State'} : null,
            isStateChanged: isset($obj->{'IsStateChanged'}) ? (bool) $obj->{'IsStateChanged'} : null,
            country: isset($obj->{'Country'}) ? (string) $obj->{'Country'} : null,
            isCountryChanged: isset($obj->{'IsCountryChanged'}) ? (bool) $obj->{'IsCountryChanged'} : null,
            postcode: isset($obj->{'Postcode'}) ? (string) $obj->{'Postcode'} : null,
            isPostcodeChanged: isset($obj->{'IsPostcodeChanged'}) ? (bool) $obj->{'IsPostcodeChanged'} : null,
            mainPhone: isset($obj->{'MainPhone'}) ? (string) $obj->{'MainPhone'} : null,
            isMainPhoneChanged: isset($obj->{'IsMainPhoneChanged'}) ? (bool) $obj->{'IsMainPhoneChanged'} : null,
            homePage: isset($obj->{'HomePage'}) ? (string) $obj->{'HomePage'} : null,
            isHomePageChanged: isset($obj->{'IsHomePageChanged'}) ? (bool) $obj->{'IsHomePageChanged'} : null,
            category: isset($obj->{'Category'}) ? (string) $obj->{'Category'} : null,
            isCategoryChanged: isset($obj->{'IsCategoryChanged'}) ? (bool) $obj->{'IsCategoryChanged'} : null,
            businessHours: isset($obj->{'BusinessHours'}) ? (string) $obj->{'BusinessHours'} : null,
            isBusinessHoursChanged: isset($obj->{'IsBusinessHoursChanged'}) ? (bool) $obj->{'IsBusinessHoursChanged'} : null,
            latitude: isset($obj->{'Latitude'}) ? (float) $obj->{'Latitude'} : null,
            isLatitudeChanged: isset($obj->{'IsLatitudeChanged'}) ? (bool) $obj->{'IsLatitudeChanged'} : null,
            longitude: isset($obj->{'Longitude'}) ? (float) $obj->{'Longitude'} : null,
            isLongitudeChanged: isset($obj->{'IsLongitudeChanged'}) ? (bool) $obj->{'IsLongitudeChanged'} : null,
            picture: isset($obj->{'Picture'}) ? (string) $obj->{'Picture'} : null,
            isPictureChanged: isset($obj->{'IsPictureChanged'}) ? (bool) $obj->{'IsPictureChanged'} : null,
            description: isset($obj->{'Description'}) ? (string) $obj->{'Description'} : null,
            isDescriptionChanged: isset($obj->{'IsDescriptionChanged'}) ? (bool) $obj->{'IsDescriptionChanged'} : null,
            email: isset($obj->{'Email'}) ? (string) $obj->{'Email'} : null,
            isEmailChanged: isset($obj->{'IsEmailChanged'}) ? (bool) $obj->{'IsEmailChanged'} : null,
            alternativePhone: isset($obj->{'AlternativePhone'}) ? (string) $obj->{'AlternativePhone'} : null,
            isAlternativePhoneChanged: isset($obj->{'IsAlternativePhoneChanged'}) ? (bool) $obj->{'IsAlternativePhoneChanged'} : null,
            mobilePhone: isset($obj->{'MobilePhone'}) ? (string) $obj->{'MobilePhone'} : null,
            isMobilePhoneChanged: isset($obj->{'IsMobilePhoneChanged'}) ? (bool) $obj->{'IsMobilePhoneChanged'} : null,
            fax: isset($obj->{'Fax'}) ? (string) $obj->{'Fax'} : null,
            isFaxChanged: isset($obj->{'IsFaxChanged'}) ? (bool) $obj->{'IsFaxChanged'} : null,
            paymentType: isset($obj->{'PaymentType'}) ? (string) $obj->{'PaymentType'} : null,
            isPaymentTypeChanged: isset($obj->{'IsPaymentTypeChanged'}) ? (bool) $obj->{'IsPaymentTypeChanged'} : null,
            advertiseIcon: isset($obj->{'AdvertiseIcon'}) ? (string) $obj->{'AdvertiseIcon'} : null,
            isAdvertiseIconChanged: isset($obj->{'IsAdvertiseIconChanged'}) ? (bool) $obj->{'IsAdvertiseIconChanged'} : null,
            advertisePhone: isset($obj->{'AdvertisePhone'}) ? (string) $obj->{'AdvertisePhone'} : null,
            isAdvertisePhoneChanged: isset($obj->{'IsAdvertisePhoneChanged'}) ? (bool) $obj->{'IsAdvertisePhoneChanged'} : null,
            advertiseUrl: isset($obj->{'AdvertiseUrl'}) ? (string) $obj->{'AdvertiseUrl'} : null,
            isAdvertiseUrlChanged: isset($obj->{'IsAdvertiseUrlChanged'}) ? (bool) $obj->{'IsAdvertiseUrlChanged'} : null,
            outOfLength: isset($obj->{'OutOfLength'}) ? (string) $obj->{'OutOfLength'} : null,
            notes: isset($obj->{'Notes'}) ? (string) $obj->{'Notes'} : null,
        );
    }
}
