<?php

namespace Misakstvanu\LaravelSkautis\Responses\Exports;

final class ExportSeznamChangesAllOutput
{
    public function __construct(
        public readonly ?string $dateRun = null,
        public readonly ?string $changes = null,
        public readonly ?string $displayName = null,
        public readonly ?string $lawType = null,
        public readonly ?string $iC = null,
        public readonly ?string $phone1 = null,
        public readonly ?string $phone1Type = null,
        public readonly ?string $phone2 = null,
        public readonly ?string $phone2Type = null,
        public readonly ?string $phone3 = null,
        public readonly ?string $phone3Type = null,
        public readonly ?string $email = null,
        public readonly ?string $url = null,
        public readonly ?string $city = null,
        public readonly ?string $cityPart = null,
        public readonly ?string $street = null,
        public readonly ?string $streetNumber = null,
        public readonly ?string $postcode = null,
        public readonly ?float $latitude = null,
        public readonly ?float $longitude = null,
        public readonly ?string $advertiseText = null,
        public readonly ?bool $isDisplayNameChanged = null,
        public readonly ?bool $isLawTypeChanged = null,
        public readonly ?bool $isICChanged = null,
        public readonly ?bool $isDICChanged = null,
        public readonly ?bool $isPhone1Changed = null,
        public readonly ?bool $isPhone1TypeChanged = null,
        public readonly ?bool $isPhone2Changed = null,
        public readonly ?bool $isPhone2TypeChanged = null,
        public readonly ?bool $isPhone3Changed = null,
        public readonly ?bool $isPhone3TypeChanged = null,
        public readonly ?bool $isEmailChanged = null,
        public readonly ?bool $isUrlChanged = null,
        public readonly ?bool $isCityChanged = null,
        public readonly ?bool $isCityPartChanged = null,
        public readonly ?bool $isStreetChanged = null,
        public readonly ?bool $isStreetNumberChanged = null,
        public readonly ?bool $isPostcodeChanged = null,
        public readonly ?bool $isLatitudeChanged = null,
        public readonly ?bool $isLongitudeChanged = null,
        public readonly ?bool $isAdvertiseTextChanged = null,
        public readonly ?string $notes = null,
        public readonly ?string $dIC = null,
    ) {}

    public static function fromStdClass(\stdClass $obj): self
    {
        return new self(
            dateRun: isset($obj->{'DateRun'}) ? (string) $obj->{'DateRun'} : null,
            changes: isset($obj->{'Changes'}) ? (string) $obj->{'Changes'} : null,
            displayName: isset($obj->{'DisplayName'}) ? (string) $obj->{'DisplayName'} : null,
            lawType: isset($obj->{'LawType'}) ? (string) $obj->{'LawType'} : null,
            iC: isset($obj->{'IC'}) ? (string) $obj->{'IC'} : null,
            phone1: isset($obj->{'Phone1'}) ? (string) $obj->{'Phone1'} : null,
            phone1Type: isset($obj->{'Phone1Type'}) ? (string) $obj->{'Phone1Type'} : null,
            phone2: isset($obj->{'Phone2'}) ? (string) $obj->{'Phone2'} : null,
            phone2Type: isset($obj->{'Phone2Type'}) ? (string) $obj->{'Phone2Type'} : null,
            phone3: isset($obj->{'Phone3'}) ? (string) $obj->{'Phone3'} : null,
            phone3Type: isset($obj->{'Phone3Type'}) ? (string) $obj->{'Phone3Type'} : null,
            email: isset($obj->{'Email'}) ? (string) $obj->{'Email'} : null,
            url: isset($obj->{'Url'}) ? (string) $obj->{'Url'} : null,
            city: isset($obj->{'City'}) ? (string) $obj->{'City'} : null,
            cityPart: isset($obj->{'CityPart'}) ? (string) $obj->{'CityPart'} : null,
            street: isset($obj->{'Street'}) ? (string) $obj->{'Street'} : null,
            streetNumber: isset($obj->{'StreetNumber'}) ? (string) $obj->{'StreetNumber'} : null,
            postcode: isset($obj->{'Postcode'}) ? (string) $obj->{'Postcode'} : null,
            latitude: isset($obj->{'Latitude'}) ? (float) $obj->{'Latitude'} : null,
            longitude: isset($obj->{'Longitude'}) ? (float) $obj->{'Longitude'} : null,
            advertiseText: isset($obj->{'AdvertiseText'}) ? (string) $obj->{'AdvertiseText'} : null,
            isDisplayNameChanged: isset($obj->{'IsDisplayNameChanged'}) ? (bool) $obj->{'IsDisplayNameChanged'} : null,
            isLawTypeChanged: isset($obj->{'IsLawTypeChanged'}) ? (bool) $obj->{'IsLawTypeChanged'} : null,
            isICChanged: isset($obj->{'IsICChanged'}) ? (bool) $obj->{'IsICChanged'} : null,
            isDICChanged: isset($obj->{'IsDICChanged'}) ? (bool) $obj->{'IsDICChanged'} : null,
            isPhone1Changed: isset($obj->{'IsPhone1Changed'}) ? (bool) $obj->{'IsPhone1Changed'} : null,
            isPhone1TypeChanged: isset($obj->{'IsPhone1TypeChanged'}) ? (bool) $obj->{'IsPhone1TypeChanged'} : null,
            isPhone2Changed: isset($obj->{'IsPhone2Changed'}) ? (bool) $obj->{'IsPhone2Changed'} : null,
            isPhone2TypeChanged: isset($obj->{'IsPhone2TypeChanged'}) ? (bool) $obj->{'IsPhone2TypeChanged'} : null,
            isPhone3Changed: isset($obj->{'IsPhone3Changed'}) ? (bool) $obj->{'IsPhone3Changed'} : null,
            isPhone3TypeChanged: isset($obj->{'IsPhone3TypeChanged'}) ? (bool) $obj->{'IsPhone3TypeChanged'} : null,
            isEmailChanged: isset($obj->{'IsEmailChanged'}) ? (bool) $obj->{'IsEmailChanged'} : null,
            isUrlChanged: isset($obj->{'IsUrlChanged'}) ? (bool) $obj->{'IsUrlChanged'} : null,
            isCityChanged: isset($obj->{'IsCityChanged'}) ? (bool) $obj->{'IsCityChanged'} : null,
            isCityPartChanged: isset($obj->{'IsCityPartChanged'}) ? (bool) $obj->{'IsCityPartChanged'} : null,
            isStreetChanged: isset($obj->{'IsStreetChanged'}) ? (bool) $obj->{'IsStreetChanged'} : null,
            isStreetNumberChanged: isset($obj->{'IsStreetNumberChanged'}) ? (bool) $obj->{'IsStreetNumberChanged'} : null,
            isPostcodeChanged: isset($obj->{'IsPostcodeChanged'}) ? (bool) $obj->{'IsPostcodeChanged'} : null,
            isLatitudeChanged: isset($obj->{'IsLatitudeChanged'}) ? (bool) $obj->{'IsLatitudeChanged'} : null,
            isLongitudeChanged: isset($obj->{'IsLongitudeChanged'}) ? (bool) $obj->{'IsLongitudeChanged'} : null,
            isAdvertiseTextChanged: isset($obj->{'IsAdvertiseTextChanged'}) ? (bool) $obj->{'IsAdvertiseTextChanged'} : null,
            notes: isset($obj->{'Notes'}) ? (string) $obj->{'Notes'} : null,
            dIC: isset($obj->{'DIC'}) ? (string) $obj->{'DIC'} : null,
        );
    }
}
