<?php

namespace Misakstvanu\LaravelSkautis\Requests\Grants;

final class GrantAttachmentUpdateInput
{
    public function __construct(
        public readonly ?int $id = null,
        public readonly ?bool $isReal = null,
        public readonly ?int $idGrant = null,
        public readonly ?int $idUser = null,
        public readonly ?int $idPerson = null,
        public readonly ?string $person = null,
        public readonly ?string $date = null,
        public readonly ?string $description = null,
        public readonly ?int $size = null,
        public readonly ?string $fileName = null,
        public readonly ?string $idFileType = null,
        public readonly ?string $fileType = null,
        public readonly ?string $extension = null,
        public readonly ?string $hash = null,
        public readonly ?string $fileNameExtension = null,
        public readonly ?string $idTempFile = null,
        public readonly ?string $tempFile = null,
        public readonly ?string $iconPath = null,
        public readonly ?string $idAttachmentType = null,
        public readonly ?string $attachmentType = null,
        public readonly ?string $backupFileName = null,
        public readonly ?string $backupExtension = null,
        public readonly ?string $idFileTypeBackup = null,
        public readonly ?string $backupFileType = null,
        public readonly ?string $backupIconPath = null,
        public readonly ?int $idGrantAttachment = null,
        public readonly ?bool $isAttached = null,
        public readonly ?bool $isCentralInsurance = null,
        public readonly ?bool $isDeposited = null,
        public readonly ?int $depositYear = null,
        public readonly ?string $note = null,
        public readonly ?string $code = null,
        public readonly ?string $idGrantType = null,
        public readonly ?string $grantType = null,
        public readonly ?string $help = null,
        public readonly ?string $displayName = null,
        public readonly ?int $idDocument = null,
        public readonly ?int $idDocumentBackup = null,
    ) {}

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(
            [
            'ID' => $this->id,
            'IsReal' => $this->isReal,
            'ID_Grant' => $this->idGrant,
            'ID_User' => $this->idUser,
            'ID_Person' => $this->idPerson,
            'Person' => $this->person,
            'Date' => $this->date,
            'Description' => $this->description,
            'Size' => $this->size,
            'FileName' => $this->fileName,
            'ID_FileType' => $this->idFileType,
            'FileType' => $this->fileType,
            'Extension' => $this->extension,
            'Hash' => $this->hash,
            'FileNameExtension' => $this->fileNameExtension,
            'ID_TempFile' => $this->idTempFile,
            'TempFile' => $this->tempFile,
            'IconPath' => $this->iconPath,
            'ID_AttachmentType' => $this->idAttachmentType,
            'AttachmentType' => $this->attachmentType,
            'BackupFileName' => $this->backupFileName,
            'BackupExtension' => $this->backupExtension,
            'ID_FileTypeBackup' => $this->idFileTypeBackup,
            'BackupFileType' => $this->backupFileType,
            'BackupIconPath' => $this->backupIconPath,
            'ID_GrantAttachment' => $this->idGrantAttachment,
            'IsAttached' => $this->isAttached,
            'IsCentralInsurance' => $this->isCentralInsurance,
            'IsDeposited' => $this->isDeposited,
            'DepositYear' => $this->depositYear,
            'Note' => $this->note,
            'Code' => $this->code,
            'ID_GrantType' => $this->idGrantType,
            'GrantType' => $this->grantType,
            'Help' => $this->help,
            'DisplayName' => $this->displayName,
            'ID_Document' => $this->idDocument,
            'ID_DocumentBackup' => $this->idDocumentBackup,
            ],
            fn (mixed $v): bool => $v !== null,
        );
    }
}
