<?php

namespace Misakstvanu\LaravelSkautis\Responses\Events;

final class CandidateDetailOutput
{
    public function __construct(
        public readonly ?string $idLogin = null,
        public readonly ?int $id = null,
        public readonly ?string $displayName = null,
        public readonly ?int $idEventCongress = null,
        public readonly ?string $eventCongress = null,
        public readonly ?string $idCandidateState = null,
        public readonly ?string $candidateState = null,
        public readonly ?string $stateDecision = null,
        public readonly ?int $idUserCreate = null,
        public readonly ?int $idPersonCreate = null,
        public readonly ?string $personCreate = null,
        public readonly ?string $dateCreate = null,
        public readonly ?int $idPerson = null,
        public readonly ?string $person = null,
        public readonly ?int $idCandidateWith = null,
        public readonly ?string $personWith = null,
        public readonly ?int $idEventCongressFunction = null,
        public readonly ?string $eventCongressFunction = null,
        public readonly ?string $functionType = null,
        public readonly ?bool $isCandidateWith = null,
        public readonly ?string $idTempFile = null,
        public readonly ?int $idDocument = null,
        public readonly ?string $additionalExperience = null,
        public readonly ?string $attachmentExtension = null,
        public readonly ?string $attachmentContent = null,
        public readonly ?string $career = null,
        public readonly ?string $suggesterName = null,
        public readonly ?string $suggesterFunction = null,
        public readonly ?string $suggesterDescription = null,
        public readonly ?string $presentation = null,
        public readonly ?string $success = null,
        public readonly ?string $agenda = null,
        public readonly ?string $problems = null,
        public readonly ?string $mainTask = null,
        public readonly ?int $votesCount = null,
        public readonly ?int $order = null,
        public readonly ?bool $isElected = null,
        public readonly ?string $unit = null,
        public readonly ?string $idUnitType = null,
        public readonly ?int $idPersonContact = null,
        public readonly ?int $idEducationSeminary = null,
        public readonly ?int $idFunction = null,
        public readonly ?int $idQualification = null,
        public readonly ?string $relation = null,
        public readonly ?string $description = null,
        public readonly ?int $yearFrom = null,
        public readonly ?int $yearTo = null,
    ) {}

    public static function fromStdClass(\stdClass $obj): self
    {
        return new self(
            idLogin: isset($obj->{'ID_Login'}) ? (string) $obj->{'ID_Login'} : null,
            id: isset($obj->{'ID'}) ? (int) $obj->{'ID'} : null,
            displayName: isset($obj->{'DisplayName'}) ? (string) $obj->{'DisplayName'} : null,
            idEventCongress: isset($obj->{'ID_EventCongress'}) ? (int) $obj->{'ID_EventCongress'} : null,
            eventCongress: isset($obj->{'EventCongress'}) ? (string) $obj->{'EventCongress'} : null,
            idCandidateState: isset($obj->{'ID_CandidateState'}) ? (string) $obj->{'ID_CandidateState'} : null,
            candidateState: isset($obj->{'CandidateState'}) ? (string) $obj->{'CandidateState'} : null,
            stateDecision: isset($obj->{'StateDecision'}) ? (string) $obj->{'StateDecision'} : null,
            idUserCreate: isset($obj->{'ID_UserCreate'}) ? (int) $obj->{'ID_UserCreate'} : null,
            idPersonCreate: isset($obj->{'ID_PersonCreate'}) ? (int) $obj->{'ID_PersonCreate'} : null,
            personCreate: isset($obj->{'PersonCreate'}) ? (string) $obj->{'PersonCreate'} : null,
            dateCreate: isset($obj->{'DateCreate'}) ? (string) $obj->{'DateCreate'} : null,
            idPerson: isset($obj->{'ID_Person'}) ? (int) $obj->{'ID_Person'} : null,
            person: isset($obj->{'Person'}) ? (string) $obj->{'Person'} : null,
            idCandidateWith: isset($obj->{'ID_CandidateWith'}) ? (int) $obj->{'ID_CandidateWith'} : null,
            personWith: isset($obj->{'PersonWith'}) ? (string) $obj->{'PersonWith'} : null,
            idEventCongressFunction: isset($obj->{'ID_EventCongressFunction'}) ? (int) $obj->{'ID_EventCongressFunction'} : null,
            eventCongressFunction: isset($obj->{'EventCongressFunction'}) ? (string) $obj->{'EventCongressFunction'} : null,
            functionType: isset($obj->{'FunctionType'}) ? (string) $obj->{'FunctionType'} : null,
            isCandidateWith: isset($obj->{'IsCandidateWith'}) ? (bool) $obj->{'IsCandidateWith'} : null,
            idTempFile: isset($obj->{'ID_TempFile'}) ? (string) $obj->{'ID_TempFile'} : null,
            idDocument: isset($obj->{'ID_Document'}) ? (int) $obj->{'ID_Document'} : null,
            additionalExperience: isset($obj->{'AdditionalExperience'}) ? (string) $obj->{'AdditionalExperience'} : null,
            attachmentExtension: isset($obj->{'AttachmentExtension'}) ? (string) $obj->{'AttachmentExtension'} : null,
            attachmentContent: isset($obj->{'AttachmentContent'}) ? (string) $obj->{'AttachmentContent'} : null,
            career: isset($obj->{'Career'}) ? (string) $obj->{'Career'} : null,
            suggesterName: isset($obj->{'SuggesterName'}) ? (string) $obj->{'SuggesterName'} : null,
            suggesterFunction: isset($obj->{'SuggesterFunction'}) ? (string) $obj->{'SuggesterFunction'} : null,
            suggesterDescription: isset($obj->{'SuggesterDescription'}) ? (string) $obj->{'SuggesterDescription'} : null,
            presentation: isset($obj->{'Presentation'}) ? (string) $obj->{'Presentation'} : null,
            success: isset($obj->{'Success'}) ? (string) $obj->{'Success'} : null,
            agenda: isset($obj->{'Agenda'}) ? (string) $obj->{'Agenda'} : null,
            problems: isset($obj->{'Problems'}) ? (string) $obj->{'Problems'} : null,
            mainTask: isset($obj->{'MainTask'}) ? (string) $obj->{'MainTask'} : null,
            votesCount: isset($obj->{'VotesCount'}) ? (int) $obj->{'VotesCount'} : null,
            order: isset($obj->{'Order'}) ? (int) $obj->{'Order'} : null,
            isElected: isset($obj->{'IsElected'}) ? (bool) $obj->{'IsElected'} : null,
            unit: isset($obj->{'Unit'}) ? (string) $obj->{'Unit'} : null,
            idUnitType: isset($obj->{'ID_UnitType'}) ? (string) $obj->{'ID_UnitType'} : null,
            idPersonContact: isset($obj->{'ID_PersonContact'}) ? (int) $obj->{'ID_PersonContact'} : null,
            idEducationSeminary: isset($obj->{'ID_EducationSeminary'}) ? (int) $obj->{'ID_EducationSeminary'} : null,
            idFunction: isset($obj->{'ID_Function'}) ? (int) $obj->{'ID_Function'} : null,
            idQualification: isset($obj->{'ID_Qualification'}) ? (int) $obj->{'ID_Qualification'} : null,
            relation: isset($obj->{'Relation'}) ? (string) $obj->{'Relation'} : null,
            description: isset($obj->{'Description'}) ? (string) $obj->{'Description'} : null,
            yearFrom: isset($obj->{'YearFrom'}) ? (int) $obj->{'YearFrom'} : null,
            yearTo: isset($obj->{'YearTo'}) ? (int) $obj->{'YearTo'} : null,
        );
    }
}
