<?php

namespace Misakstvanu\LaravelSkautis\Responses\Events;

final class EventGeneralDetailOutput
{
    public function __construct(
        public readonly ?string $idLogin = null,
        public readonly ?int $id = null,
        public readonly ?int $idGroup = null,
        public readonly ?string $idEventType = null,
        public readonly ?int $idUserCreate = null,
        public readonly ?string $dateCreate = null,
        public readonly ?string $displayName = null,
        public readonly ?int $idUnit = null,
        public readonly ?string $unit = null,
        public readonly ?string $registrationNumber = null,
        public readonly ?string $startDate = null,
        public readonly ?string $endDate = null,
        public readonly ?int $totalDays = null,
        public readonly ?float $gpsLatitude = null,
        public readonly ?string $gpsLatitudeText = null,
        public readonly ?float $gpsLongitude = null,
        public readonly ?string $gpsLongitudeText = null,
        public readonly ?string $location = null,
        public readonly ?string $note = null,
        public readonly ?string $cancelDecision = null,
        public readonly ?int $idEvent = null,
        public readonly ?string $event = null,
        public readonly ?string $idEventGeneralState = null,
        public readonly ?string $eventGeneralState = null,
        public readonly ?int $idUnitEducative = null,
        public readonly ?string $unitEducative = null,
        public readonly ?string $unitEducativeRegistrationNumber = null,
        public readonly ?int $idEventGeneralType = null,
        public readonly ?string $eventGeneralType = null,
        public readonly ?int $idEventGeneralScope = null,
        public readonly ?string $eventGeneralScope = null,
        public readonly ?string $street = null,
        public readonly ?string $postcode = null,
        public readonly ?string $region = null,
        public readonly ?string $state = null,
        public readonly ?int $foreignParticipants = null,
        public readonly ?int $leaderParticipants = null,
        public readonly ?int $assistantParticipants = null,
        public readonly ?bool $isStatisticAutoComputed = null,
        public readonly ?int $childDays = null,
        public readonly ?int $personDays = null,
        public readonly ?string $target = null,
        public readonly ?string $program = null,
        public readonly ?int $idPersonClosed = null,
        public readonly ?string $personClosed = null,
        public readonly ?string $dateClosed = null,
        public readonly ?int $int = null,
        public readonly ?string $eventSpecificationType = null,
        public readonly ?bool $isAutoComputedDays = null,
        public readonly ?int $totalParticipants = null,
    ) {}

    public static function fromStdClass(\stdClass $obj): self
    {
        return new self(
            idLogin: isset($obj->{'ID_Login'}) ? (string) $obj->{'ID_Login'} : null,
            id: isset($obj->{'ID'}) ? (int) $obj->{'ID'} : null,
            idGroup: isset($obj->{'ID_Group'}) ? (int) $obj->{'ID_Group'} : null,
            idEventType: isset($obj->{'ID_EventType'}) ? (string) $obj->{'ID_EventType'} : null,
            idUserCreate: isset($obj->{'ID_UserCreate'}) ? (int) $obj->{'ID_UserCreate'} : null,
            dateCreate: isset($obj->{'DateCreate'}) ? (string) $obj->{'DateCreate'} : null,
            displayName: isset($obj->{'DisplayName'}) ? (string) $obj->{'DisplayName'} : null,
            idUnit: isset($obj->{'ID_Unit'}) ? (int) $obj->{'ID_Unit'} : null,
            unit: isset($obj->{'Unit'}) ? (string) $obj->{'Unit'} : null,
            registrationNumber: isset($obj->{'RegistrationNumber'}) ? (string) $obj->{'RegistrationNumber'} : null,
            startDate: isset($obj->{'StartDate'}) ? (string) $obj->{'StartDate'} : null,
            endDate: isset($obj->{'EndDate'}) ? (string) $obj->{'EndDate'} : null,
            totalDays: isset($obj->{'TotalDays'}) ? (int) $obj->{'TotalDays'} : null,
            gpsLatitude: isset($obj->{'GpsLatitude'}) ? (float) $obj->{'GpsLatitude'} : null,
            gpsLatitudeText: isset($obj->{'GpsLatitudeText'}) ? (string) $obj->{'GpsLatitudeText'} : null,
            gpsLongitude: isset($obj->{'GpsLongitude'}) ? (float) $obj->{'GpsLongitude'} : null,
            gpsLongitudeText: isset($obj->{'GpsLongitudeText'}) ? (string) $obj->{'GpsLongitudeText'} : null,
            location: isset($obj->{'Location'}) ? (string) $obj->{'Location'} : null,
            note: isset($obj->{'Note'}) ? (string) $obj->{'Note'} : null,
            cancelDecision: isset($obj->{'CancelDecision'}) ? (string) $obj->{'CancelDecision'} : null,
            idEvent: isset($obj->{'ID_Event'}) ? (int) $obj->{'ID_Event'} : null,
            event: isset($obj->{'Event'}) ? (string) $obj->{'Event'} : null,
            idEventGeneralState: isset($obj->{'ID_EventGeneralState'}) ? (string) $obj->{'ID_EventGeneralState'} : null,
            eventGeneralState: isset($obj->{'EventGeneralState'}) ? (string) $obj->{'EventGeneralState'} : null,
            idUnitEducative: isset($obj->{'ID_UnitEducative'}) ? (int) $obj->{'ID_UnitEducative'} : null,
            unitEducative: isset($obj->{'UnitEducative'}) ? (string) $obj->{'UnitEducative'} : null,
            unitEducativeRegistrationNumber: isset($obj->{'UnitEducativeRegistrationNumber'}) ? (string) $obj->{'UnitEducativeRegistrationNumber'} : null,
            idEventGeneralType: isset($obj->{'ID_EventGeneralType'}) ? (int) $obj->{'ID_EventGeneralType'} : null,
            eventGeneralType: isset($obj->{'EventGeneralType'}) ? (string) $obj->{'EventGeneralType'} : null,
            idEventGeneralScope: isset($obj->{'ID_EventGeneralScope'}) ? (int) $obj->{'ID_EventGeneralScope'} : null,
            eventGeneralScope: isset($obj->{'EventGeneralScope'}) ? (string) $obj->{'EventGeneralScope'} : null,
            street: isset($obj->{'Street'}) ? (string) $obj->{'Street'} : null,
            postcode: isset($obj->{'Postcode'}) ? (string) $obj->{'Postcode'} : null,
            region: isset($obj->{'Region'}) ? (string) $obj->{'Region'} : null,
            state: isset($obj->{'State'}) ? (string) $obj->{'State'} : null,
            foreignParticipants: isset($obj->{'ForeignParticipants'}) ? (int) $obj->{'ForeignParticipants'} : null,
            leaderParticipants: isset($obj->{'LeaderParticipants'}) ? (int) $obj->{'LeaderParticipants'} : null,
            assistantParticipants: isset($obj->{'AssistantParticipants'}) ? (int) $obj->{'AssistantParticipants'} : null,
            isStatisticAutoComputed: isset($obj->{'IsStatisticAutoComputed'}) ? (bool) $obj->{'IsStatisticAutoComputed'} : null,
            childDays: isset($obj->{'ChildDays'}) ? (int) $obj->{'ChildDays'} : null,
            personDays: isset($obj->{'PersonDays'}) ? (int) $obj->{'PersonDays'} : null,
            target: isset($obj->{'Target'}) ? (string) $obj->{'Target'} : null,
            program: isset($obj->{'Program'}) ? (string) $obj->{'Program'} : null,
            idPersonClosed: isset($obj->{'ID_PersonClosed'}) ? (int) $obj->{'ID_PersonClosed'} : null,
            personClosed: isset($obj->{'PersonClosed'}) ? (string) $obj->{'PersonClosed'} : null,
            dateClosed: isset($obj->{'DateClosed'}) ? (string) $obj->{'DateClosed'} : null,
            int: isset($obj->{'int'}) ? (int) $obj->{'int'} : null,
            eventSpecificationType: isset($obj->{'EventSpecificationType'}) ? (string) $obj->{'EventSpecificationType'} : null,
            isAutoComputedDays: isset($obj->{'IsAutoComputedDays'}) ? (bool) $obj->{'IsAutoComputedDays'} : null,
            totalParticipants: isset($obj->{'TotalParticipants'}) ? (int) $obj->{'TotalParticipants'} : null,
        );
    }
}
