<?php

namespace Misakstvanu\LaravelSkautis\Responses\Events;

final class EventEducationAllOutput
{
    public function __construct(
        public readonly ?int $id = null,
        public readonly ?string $displayName = null,
        public readonly ?string $displayNameCombined = null,
        public readonly ?int $idEvent = null,
        public readonly ?string $event = null,
        public readonly ?string $idEventEducationState = null,
        public readonly ?string $eventEducationState = null,
        public readonly ?string $web = null,
        public readonly ?string $emailContact = null,
        public readonly ?string $phoneContact = null,
        public readonly ?string $dateApproved = null,
        public readonly ?float $grant = null,
        public readonly ?string $idGrantType = null,
        public readonly ?string $grantType = null,
        public readonly ?string $idGrantAdvanceType = null,
        public readonly ?string $grantAdvanceType = null,
        public readonly ?string $dateClosed = null,
        public readonly ?int $idPersonClosed = null,
        public readonly ?string $personClosed = null,
        public readonly ?string $logoFileName = null,
        public readonly ?int $idDocumentLogo = null,
        public readonly ?int $idDocumentLogoPreview = null,
        public readonly ?int $idDocumentLogoMiniature = null,
        public readonly ?string $propagationFileName1 = null,
        public readonly ?string $propagationFileName2 = null,
        public readonly ?string $propagationFileName3 = null,
        public readonly ?bool $loginSkautis = null,
        public readonly ?string $loginLocation = null,
        public readonly ?string $description = null,
        public readonly ?string $datePublished = null,
        public readonly ?string $dateWaitingForOrganizerApprove = null,
        public readonly ?string $dateWaitingForReporterApprove = null,
        public readonly ?string $dateWaitingForHKVS = null,
        public readonly ?string $dateGrantRequest = null,
        public readonly ?string $dateGrantConfirm = null,
        public readonly ?string $dateDepositSent = null,
        public readonly ?string $dateBillPaid = null,
        public readonly ?string $dateRestGrantSent = null,
        public readonly ?string $registrationDeadline = null,
        public readonly ?int $capacityCourse = null,
        public readonly ?int $capacitySubstitute = null,
        public readonly ?int $idEventEducationType = null,
        public readonly ?string $idEventEducationGroup = null,
        public readonly ?string $eventEducationType = null,
        public readonly ?string $eventEducationGroup = null,
        public readonly ?string $startDate = null,
        public readonly ?string $endDate = null,
        public readonly ?string $projectExtension = null,
        public readonly ?string $finalReportExtension = null,
        public readonly ?bool $areExamsApproved = null,
        public readonly ?string $disapproveNote = null,
        public readonly ?string $waterApproved = null,
        public readonly ?string $waterDisapproveNote = null,
        public readonly ?bool $isWaterman = null,
        public readonly ?string $publicized = null,
        public readonly ?string $rejectionNote = null,
        public readonly ?int $idEventEducationCourse = null,
        public readonly ?string $eventEducationCourse = null,
        public readonly ?string $loginFrom = null,
        public readonly ?string $loginTo = null,
        public readonly ?int $idEventEducationCourseEnrollReminder = null,
    ) {}

    public static function fromStdClass(\stdClass $obj): self
    {
        return new self(
            id: isset($obj->{'ID'}) ? (int) $obj->{'ID'} : null,
            displayName: isset($obj->{'DisplayName'}) ? (string) $obj->{'DisplayName'} : null,
            displayNameCombined: isset($obj->{'DisplayNameCombined'}) ? (string) $obj->{'DisplayNameCombined'} : null,
            idEvent: isset($obj->{'ID_Event'}) ? (int) $obj->{'ID_Event'} : null,
            event: isset($obj->{'Event'}) ? (string) $obj->{'Event'} : null,
            idEventEducationState: isset($obj->{'ID_EventEducationState'}) ? (string) $obj->{'ID_EventEducationState'} : null,
            eventEducationState: isset($obj->{'EventEducationState'}) ? (string) $obj->{'EventEducationState'} : null,
            web: isset($obj->{'Web'}) ? (string) $obj->{'Web'} : null,
            emailContact: isset($obj->{'EmailContact'}) ? (string) $obj->{'EmailContact'} : null,
            phoneContact: isset($obj->{'PhoneContact'}) ? (string) $obj->{'PhoneContact'} : null,
            dateApproved: isset($obj->{'DateApproved'}) ? (string) $obj->{'DateApproved'} : null,
            grant: isset($obj->{'Grant'}) ? (float) $obj->{'Grant'} : null,
            idGrantType: isset($obj->{'ID_GrantType'}) ? (string) $obj->{'ID_GrantType'} : null,
            grantType: isset($obj->{'GrantType'}) ? (string) $obj->{'GrantType'} : null,
            idGrantAdvanceType: isset($obj->{'ID_GrantAdvanceType'}) ? (string) $obj->{'ID_GrantAdvanceType'} : null,
            grantAdvanceType: isset($obj->{'GrantAdvanceType'}) ? (string) $obj->{'GrantAdvanceType'} : null,
            dateClosed: isset($obj->{'DateClosed'}) ? (string) $obj->{'DateClosed'} : null,
            idPersonClosed: isset($obj->{'ID_PersonClosed'}) ? (int) $obj->{'ID_PersonClosed'} : null,
            personClosed: isset($obj->{'PersonClosed'}) ? (string) $obj->{'PersonClosed'} : null,
            logoFileName: isset($obj->{'LogoFileName'}) ? (string) $obj->{'LogoFileName'} : null,
            idDocumentLogo: isset($obj->{'ID_DocumentLogo'}) ? (int) $obj->{'ID_DocumentLogo'} : null,
            idDocumentLogoPreview: isset($obj->{'ID_DocumentLogoPreview'}) ? (int) $obj->{'ID_DocumentLogoPreview'} : null,
            idDocumentLogoMiniature: isset($obj->{'ID_DocumentLogoMiniature'}) ? (int) $obj->{'ID_DocumentLogoMiniature'} : null,
            propagationFileName1: isset($obj->{'PropagationFileName1'}) ? (string) $obj->{'PropagationFileName1'} : null,
            propagationFileName2: isset($obj->{'PropagationFileName2'}) ? (string) $obj->{'PropagationFileName2'} : null,
            propagationFileName3: isset($obj->{'PropagationFileName3'}) ? (string) $obj->{'PropagationFileName3'} : null,
            loginSkautis: isset($obj->{'LoginSkautis'}) ? (bool) $obj->{'LoginSkautis'} : null,
            loginLocation: isset($obj->{'LoginLocation'}) ? (string) $obj->{'LoginLocation'} : null,
            description: isset($obj->{'Description'}) ? (string) $obj->{'Description'} : null,
            datePublished: isset($obj->{'DatePublished'}) ? (string) $obj->{'DatePublished'} : null,
            dateWaitingForOrganizerApprove: isset($obj->{'DateWaitingForOrganizerApprove'}) ? (string) $obj->{'DateWaitingForOrganizerApprove'} : null,
            dateWaitingForReporterApprove: isset($obj->{'DateWaitingForReporterApprove'}) ? (string) $obj->{'DateWaitingForReporterApprove'} : null,
            dateWaitingForHKVS: isset($obj->{'DateWaitingForHKVS'}) ? (string) $obj->{'DateWaitingForHKVS'} : null,
            dateGrantRequest: isset($obj->{'DateGrantRequest'}) ? (string) $obj->{'DateGrantRequest'} : null,
            dateGrantConfirm: isset($obj->{'DateGrantConfirm'}) ? (string) $obj->{'DateGrantConfirm'} : null,
            dateDepositSent: isset($obj->{'DateDepositSent'}) ? (string) $obj->{'DateDepositSent'} : null,
            dateBillPaid: isset($obj->{'DateBillPaid'}) ? (string) $obj->{'DateBillPaid'} : null,
            dateRestGrantSent: isset($obj->{'DateRestGrantSent'}) ? (string) $obj->{'DateRestGrantSent'} : null,
            registrationDeadline: isset($obj->{'RegistrationDeadline'}) ? (string) $obj->{'RegistrationDeadline'} : null,
            capacityCourse: isset($obj->{'CapacityCourse'}) ? (int) $obj->{'CapacityCourse'} : null,
            capacitySubstitute: isset($obj->{'CapacitySubstitute'}) ? (int) $obj->{'CapacitySubstitute'} : null,
            idEventEducationType: isset($obj->{'ID_EventEducationType'}) ? (int) $obj->{'ID_EventEducationType'} : null,
            idEventEducationGroup: isset($obj->{'ID_EventEducationGroup'}) ? (string) $obj->{'ID_EventEducationGroup'} : null,
            eventEducationType: isset($obj->{'EventEducationType'}) ? (string) $obj->{'EventEducationType'} : null,
            eventEducationGroup: isset($obj->{'EventEducationGroup'}) ? (string) $obj->{'EventEducationGroup'} : null,
            startDate: isset($obj->{'StartDate'}) ? (string) $obj->{'StartDate'} : null,
            endDate: isset($obj->{'EndDate'}) ? (string) $obj->{'EndDate'} : null,
            projectExtension: isset($obj->{'ProjectExtension'}) ? (string) $obj->{'ProjectExtension'} : null,
            finalReportExtension: isset($obj->{'FinalReportExtension'}) ? (string) $obj->{'FinalReportExtension'} : null,
            areExamsApproved: isset($obj->{'AreExamsApproved'}) ? (bool) $obj->{'AreExamsApproved'} : null,
            disapproveNote: isset($obj->{'DisapproveNote'}) ? (string) $obj->{'DisapproveNote'} : null,
            waterApproved: isset($obj->{'WaterApproved'}) ? (string) $obj->{'WaterApproved'} : null,
            waterDisapproveNote: isset($obj->{'WaterDisapproveNote'}) ? (string) $obj->{'WaterDisapproveNote'} : null,
            isWaterman: isset($obj->{'IsWaterman'}) ? (bool) $obj->{'IsWaterman'} : null,
            publicized: isset($obj->{'Publicized'}) ? (string) $obj->{'Publicized'} : null,
            rejectionNote: isset($obj->{'RejectionNote'}) ? (string) $obj->{'RejectionNote'} : null,
            idEventEducationCourse: isset($obj->{'ID_EventEducationCourse'}) ? (int) $obj->{'ID_EventEducationCourse'} : null,
            eventEducationCourse: isset($obj->{'EventEducationCourse'}) ? (string) $obj->{'EventEducationCourse'} : null,
            loginFrom: isset($obj->{'LoginFrom'}) ? (string) $obj->{'LoginFrom'} : null,
            loginTo: isset($obj->{'LoginTo'}) ? (string) $obj->{'LoginTo'} : null,
            idEventEducationCourseEnrollReminder: isset($obj->{'ID_EventEducationCourseEnrollReminder'}) ? (int) $obj->{'ID_EventEducationCourseEnrollReminder'} : null,
        );
    }
}
