<?php

namespace Misakstvanu\LaravelSkautis\Responses\Events;

final class EventCampDetailOutput
{
    public function __construct(
        public readonly ?string $idLogin = null,
        public readonly ?int $id = null,
        public readonly ?int $idGroup = null,
        public readonly ?string $idEventType = null,
        public readonly ?int $idUserCreate = null,
        public readonly ?string $dateCreate = null,
        public readonly ?string $displayName = null,
        public readonly ?int $idUnit = null,
        public readonly ?string $unit = null,
        public readonly ?string $registrationNumber = null,
        public readonly ?string $startDate = null,
        public readonly ?string $endDate = null,
        public readonly ?float $gpsLatitude = null,
        public readonly ?string $gpsLatitudeText = null,
        public readonly ?float $gpsLongitude = null,
        public readonly ?string $gpsLongitudeText = null,
        public readonly ?string $location = null,
        public readonly ?string $note = null,
        public readonly ?string $cancelDecision = null,
        public readonly ?int $idEvent = null,
        public readonly ?string $idEventCampState = null,
        public readonly ?string $eventCampState = null,
        public readonly ?string $mobileContact = null,
        public readonly ?string $mobileContactDisplay = null,
        public readonly ?string $registrationDeadline = null,
        public readonly ?int $idRegion = null,
        public readonly ?string $region = null,
        public readonly ?string $postcode = null,
        public readonly ?bool $isFloodArea = null,
        public readonly ?bool $isAutoComputed = null,
        public readonly ?int $idPersonApproved = null,
        public readonly ?string $personApproved = null,
        public readonly ?string $dateApproved = null,
        public readonly ?int $idPersonApprovedParent = null,
        public readonly ?string $personApprovedParent = null,
        public readonly ?string $dateApprovedParent = null,
        public readonly ?string $dateApprovedExecutive = null,
        public readonly ?int $totalDays = null,
        public readonly ?bool $isRecovering = null,
        public readonly ?string $campType = null,
        public readonly ?string $string = null,
        public readonly ?string $units = null,
        public readonly ?int $estimateChild = null,
        public readonly ?int $estimateAdult = null,
        public readonly ?int $estimateAdultYoung = null,
        public readonly ?int $estimateCount = null,
        public readonly ?int $estimateChildDays = null,
        public readonly ?int $estimatePersonDays = null,
        public readonly ?bool $isAutoComputedDays = null,
        public readonly ?float $realTotalCost = null,
        public readonly ?bool $isRealTotalCostAutoComputed = null,
        public readonly ?bool $isRealAutoComputed = null,
        public readonly ?bool $isRealAutoComputedDays = null,
        public readonly ?int $idPersonReal = null,
        public readonly ?string $personReal = null,
        public readonly ?string $dateReal = null,
        public readonly ?int $realAdult = null,
        public readonly ?int $realAdultYoung = null,
        public readonly ?int $realChild = null,
        public readonly ?int $realCount = null,
        public readonly ?int $realChildDays = null,
        public readonly ?int $realPersonDays = null,
        public readonly ?bool $hasEstimateStatement = null,
        public readonly ?int $idPersonLeader = null,
        public readonly ?string $personLeader = null,
        public readonly ?string $personLeaderFirstName = null,
        public readonly ?string $personLeaderLastName = null,
        public readonly ?string $personLeaderCivilName = null,
        public readonly ?string $leaderPhone = null,
        public readonly ?string $leaderPhoneDisplay = null,
        public readonly ?string $leaderEmail = null,
        public readonly ?string $leaderEmailDisplay = null,
        public readonly ?string $leaderCity = null,
        public readonly ?string $unitLocation = null,
        public readonly ?string $personStatutory = null,
        public readonly ?float $profit = null,
        public readonly ?float $profitComputed = null,
        public readonly ?float $profitComputedEstimation = null,
        public readonly ?int $idCampPlace = null,
        public readonly ?string $campPlace = null,
        public readonly ?bool $isOnlineLogin = null,
        public readonly ?bool $canUpdate = null,
        public readonly ?bool $canUpdateReal = null,
        public readonly ?int $adultYoung = null,
        public readonly ?bool $isRealVisible = null,
    ) {}

    public static function fromStdClass(\stdClass $obj): self
    {
        return new self(
            idLogin: isset($obj->{'ID_Login'}) ? (string) $obj->{'ID_Login'} : null,
            id: isset($obj->{'ID'}) ? (int) $obj->{'ID'} : null,
            idGroup: isset($obj->{'ID_Group'}) ? (int) $obj->{'ID_Group'} : null,
            idEventType: isset($obj->{'ID_EventType'}) ? (string) $obj->{'ID_EventType'} : null,
            idUserCreate: isset($obj->{'ID_UserCreate'}) ? (int) $obj->{'ID_UserCreate'} : null,
            dateCreate: isset($obj->{'DateCreate'}) ? (string) $obj->{'DateCreate'} : null,
            displayName: isset($obj->{'DisplayName'}) ? (string) $obj->{'DisplayName'} : null,
            idUnit: isset($obj->{'ID_Unit'}) ? (int) $obj->{'ID_Unit'} : null,
            unit: isset($obj->{'Unit'}) ? (string) $obj->{'Unit'} : null,
            registrationNumber: isset($obj->{'RegistrationNumber'}) ? (string) $obj->{'RegistrationNumber'} : null,
            startDate: isset($obj->{'StartDate'}) ? (string) $obj->{'StartDate'} : null,
            endDate: isset($obj->{'EndDate'}) ? (string) $obj->{'EndDate'} : null,
            gpsLatitude: isset($obj->{'GpsLatitude'}) ? (float) $obj->{'GpsLatitude'} : null,
            gpsLatitudeText: isset($obj->{'GpsLatitudeText'}) ? (string) $obj->{'GpsLatitudeText'} : null,
            gpsLongitude: isset($obj->{'GpsLongitude'}) ? (float) $obj->{'GpsLongitude'} : null,
            gpsLongitudeText: isset($obj->{'GpsLongitudeText'}) ? (string) $obj->{'GpsLongitudeText'} : null,
            location: isset($obj->{'Location'}) ? (string) $obj->{'Location'} : null,
            note: isset($obj->{'Note'}) ? (string) $obj->{'Note'} : null,
            cancelDecision: isset($obj->{'CancelDecision'}) ? (string) $obj->{'CancelDecision'} : null,
            idEvent: isset($obj->{'ID_Event'}) ? (int) $obj->{'ID_Event'} : null,
            idEventCampState: isset($obj->{'ID_EventCampState'}) ? (string) $obj->{'ID_EventCampState'} : null,
            eventCampState: isset($obj->{'EventCampState'}) ? (string) $obj->{'EventCampState'} : null,
            mobileContact: isset($obj->{'MobileContact'}) ? (string) $obj->{'MobileContact'} : null,
            mobileContactDisplay: isset($obj->{'MobileContactDisplay'}) ? (string) $obj->{'MobileContactDisplay'} : null,
            registrationDeadline: isset($obj->{'RegistrationDeadline'}) ? (string) $obj->{'RegistrationDeadline'} : null,
            idRegion: isset($obj->{'ID_Region'}) ? (int) $obj->{'ID_Region'} : null,
            region: isset($obj->{'Region'}) ? (string) $obj->{'Region'} : null,
            postcode: isset($obj->{'Postcode'}) ? (string) $obj->{'Postcode'} : null,
            isFloodArea: isset($obj->{'IsFloodArea'}) ? (bool) $obj->{'IsFloodArea'} : null,
            isAutoComputed: isset($obj->{'IsAutoComputed'}) ? (bool) $obj->{'IsAutoComputed'} : null,
            idPersonApproved: isset($obj->{'ID_PersonApproved'}) ? (int) $obj->{'ID_PersonApproved'} : null,
            personApproved: isset($obj->{'PersonApproved'}) ? (string) $obj->{'PersonApproved'} : null,
            dateApproved: isset($obj->{'DateApproved'}) ? (string) $obj->{'DateApproved'} : null,
            idPersonApprovedParent: isset($obj->{'ID_PersonApprovedParent'}) ? (int) $obj->{'ID_PersonApprovedParent'} : null,
            personApprovedParent: isset($obj->{'PersonApprovedParent'}) ? (string) $obj->{'PersonApprovedParent'} : null,
            dateApprovedParent: isset($obj->{'DateApprovedParent'}) ? (string) $obj->{'DateApprovedParent'} : null,
            dateApprovedExecutive: isset($obj->{'DateApprovedExecutive'}) ? (string) $obj->{'DateApprovedExecutive'} : null,
            totalDays: isset($obj->{'TotalDays'}) ? (int) $obj->{'TotalDays'} : null,
            isRecovering: isset($obj->{'IsRecovering'}) ? (bool) $obj->{'IsRecovering'} : null,
            campType: isset($obj->{'CampType'}) ? (string) $obj->{'CampType'} : null,
            string: isset($obj->{'string'}) ? (string) $obj->{'string'} : null,
            units: isset($obj->{'Units'}) ? (string) $obj->{'Units'} : null,
            estimateChild: isset($obj->{'EstimateChild'}) ? (int) $obj->{'EstimateChild'} : null,
            estimateAdult: isset($obj->{'EstimateAdult'}) ? (int) $obj->{'EstimateAdult'} : null,
            estimateAdultYoung: isset($obj->{'EstimateAdultYoung'}) ? (int) $obj->{'EstimateAdultYoung'} : null,
            estimateCount: isset($obj->{'EstimateCount'}) ? (int) $obj->{'EstimateCount'} : null,
            estimateChildDays: isset($obj->{'EstimateChildDays'}) ? (int) $obj->{'EstimateChildDays'} : null,
            estimatePersonDays: isset($obj->{'EstimatePersonDays'}) ? (int) $obj->{'EstimatePersonDays'} : null,
            isAutoComputedDays: isset($obj->{'IsAutoComputedDays'}) ? (bool) $obj->{'IsAutoComputedDays'} : null,
            realTotalCost: isset($obj->{'RealTotalCost'}) ? (float) $obj->{'RealTotalCost'} : null,
            isRealTotalCostAutoComputed: isset($obj->{'IsRealTotalCostAutoComputed'}) ? (bool) $obj->{'IsRealTotalCostAutoComputed'} : null,
            isRealAutoComputed: isset($obj->{'IsRealAutoComputed'}) ? (bool) $obj->{'IsRealAutoComputed'} : null,
            isRealAutoComputedDays: isset($obj->{'IsRealAutoComputedDays'}) ? (bool) $obj->{'IsRealAutoComputedDays'} : null,
            idPersonReal: isset($obj->{'ID_PersonReal'}) ? (int) $obj->{'ID_PersonReal'} : null,
            personReal: isset($obj->{'PersonReal'}) ? (string) $obj->{'PersonReal'} : null,
            dateReal: isset($obj->{'DateReal'}) ? (string) $obj->{'DateReal'} : null,
            realAdult: isset($obj->{'RealAdult'}) ? (int) $obj->{'RealAdult'} : null,
            realAdultYoung: isset($obj->{'RealAdultYoung'}) ? (int) $obj->{'RealAdultYoung'} : null,
            realChild: isset($obj->{'RealChild'}) ? (int) $obj->{'RealChild'} : null,
            realCount: isset($obj->{'RealCount'}) ? (int) $obj->{'RealCount'} : null,
            realChildDays: isset($obj->{'RealChildDays'}) ? (int) $obj->{'RealChildDays'} : null,
            realPersonDays: isset($obj->{'RealPersonDays'}) ? (int) $obj->{'RealPersonDays'} : null,
            hasEstimateStatement: isset($obj->{'HasEstimateStatement'}) ? (bool) $obj->{'HasEstimateStatement'} : null,
            idPersonLeader: isset($obj->{'ID_PersonLeader'}) ? (int) $obj->{'ID_PersonLeader'} : null,
            personLeader: isset($obj->{'PersonLeader'}) ? (string) $obj->{'PersonLeader'} : null,
            personLeaderFirstName: isset($obj->{'PersonLeaderFirstName'}) ? (string) $obj->{'PersonLeaderFirstName'} : null,
            personLeaderLastName: isset($obj->{'PersonLeaderLastName'}) ? (string) $obj->{'PersonLeaderLastName'} : null,
            personLeaderCivilName: isset($obj->{'PersonLeaderCivilName'}) ? (string) $obj->{'PersonLeaderCivilName'} : null,
            leaderPhone: isset($obj->{'LeaderPhone'}) ? (string) $obj->{'LeaderPhone'} : null,
            leaderPhoneDisplay: isset($obj->{'LeaderPhoneDisplay'}) ? (string) $obj->{'LeaderPhoneDisplay'} : null,
            leaderEmail: isset($obj->{'LeaderEmail'}) ? (string) $obj->{'LeaderEmail'} : null,
            leaderEmailDisplay: isset($obj->{'LeaderEmailDisplay'}) ? (string) $obj->{'LeaderEmailDisplay'} : null,
            leaderCity: isset($obj->{'LeaderCity'}) ? (string) $obj->{'LeaderCity'} : null,
            unitLocation: isset($obj->{'UnitLocation'}) ? (string) $obj->{'UnitLocation'} : null,
            personStatutory: isset($obj->{'PersonStatutory'}) ? (string) $obj->{'PersonStatutory'} : null,
            profit: isset($obj->{'Profit'}) ? (float) $obj->{'Profit'} : null,
            profitComputed: isset($obj->{'ProfitComputed'}) ? (float) $obj->{'ProfitComputed'} : null,
            profitComputedEstimation: isset($obj->{'ProfitComputedEstimation'}) ? (float) $obj->{'ProfitComputedEstimation'} : null,
            idCampPlace: isset($obj->{'ID_CampPlace'}) ? (int) $obj->{'ID_CampPlace'} : null,
            campPlace: isset($obj->{'CampPlace'}) ? (string) $obj->{'CampPlace'} : null,
            isOnlineLogin: isset($obj->{'IsOnlineLogin'}) ? (bool) $obj->{'IsOnlineLogin'} : null,
            canUpdate: isset($obj->{'CanUpdate'}) ? (bool) $obj->{'CanUpdate'} : null,
            canUpdateReal: isset($obj->{'CanUpdateReal'}) ? (bool) $obj->{'CanUpdateReal'} : null,
            adultYoung: isset($obj->{'AdultYoung'}) ? (int) $obj->{'AdultYoung'} : null,
            isRealVisible: isset($obj->{'IsRealVisible'}) ? (bool) $obj->{'IsRealVisible'} : null,
        );
    }
}
