<?php

namespace Misakstvanu\LaravelSkautis\Responses\Events;

final class EventEducationLetterRequestAllExportOutput
{
    public function __construct(
        public readonly ?int $id = null,
        public readonly ?string $personReporter = null,
        public readonly ?string $personReporterDegreeFront = null,
        public readonly ?string $personReporterDegreeBehind = null,
        public readonly ?string $personCommissionLeader = null,
        public readonly ?string $personCommissionLeaderDegreeFront = null,
        public readonly ?string $personCommissionLeaderDegreeBehind = null,
        public readonly ?string $personChiefMale = null,
        public readonly ?string $personChiefMaleDegreeFront = null,
        public readonly ?string $personChiefMaleDegreeBehind = null,
        public readonly ?string $personChiefFemale = null,
        public readonly ?string $personChiefFemaleDegreeFront = null,
        public readonly ?string $personChiefFemaleDegreeBehind = null,
        public readonly ?string $personLeader = null,
        public readonly ?string $personLeaderDegreeFront = null,
        public readonly ?string $personLeaderDegreeBehind = null,
        public readonly ?string $personGarant = null,
        public readonly ?string $personGarantDegreeFront = null,
        public readonly ?string $personGarantDegreeBehind = null,
        public readonly ?string $person = null,
        public readonly ?string $personDegreeFront = null,
        public readonly ?string $personDegreeBehind = null,
        public readonly ?string $personBirthday = null,
        public readonly ?string $personSex = null,
        public readonly ?string $date = null,
        public readonly ?string $letterNumber = null,
        public readonly ?int $idEventEducationExam = null,
        public readonly ?string $dateExam = null,
        public readonly ?string $key = null,
        public readonly ?string $idEventEducationGroup = null,
        public readonly ?string $eventEducationGroup = null,
        public readonly ?int $idQualificationType = null,
        public readonly ?string $qualificationType = null,
        public readonly ?int $idEventEducationType = null,
        public readonly ?string $eventEducationType = null,
        public readonly ?string $eventEducation = null,
        public readonly ?string $organizer = null,
        public readonly ?string $organizerRegistrationNumber = null,
        public readonly ?bool $isExam = null,
        public readonly ?string $dateGenerated = null,
    ) {}

    public static function fromStdClass(\stdClass $obj): self
    {
        return new self(
            id: isset($obj->{'ID'}) ? (int) $obj->{'ID'} : null,
            personReporter: isset($obj->{'PersonReporter'}) ? (string) $obj->{'PersonReporter'} : null,
            personReporterDegreeFront: isset($obj->{'PersonReporterDegreeFront'}) ? (string) $obj->{'PersonReporterDegreeFront'} : null,
            personReporterDegreeBehind: isset($obj->{'PersonReporterDegreeBehind'}) ? (string) $obj->{'PersonReporterDegreeBehind'} : null,
            personCommissionLeader: isset($obj->{'PersonCommissionLeader'}) ? (string) $obj->{'PersonCommissionLeader'} : null,
            personCommissionLeaderDegreeFront: isset($obj->{'PersonCommissionLeaderDegreeFront'}) ? (string) $obj->{'PersonCommissionLeaderDegreeFront'} : null,
            personCommissionLeaderDegreeBehind: isset($obj->{'PersonCommissionLeaderDegreeBehind'}) ? (string) $obj->{'PersonCommissionLeaderDegreeBehind'} : null,
            personChiefMale: isset($obj->{'PersonChiefMale'}) ? (string) $obj->{'PersonChiefMale'} : null,
            personChiefMaleDegreeFront: isset($obj->{'PersonChiefMaleDegreeFront'}) ? (string) $obj->{'PersonChiefMaleDegreeFront'} : null,
            personChiefMaleDegreeBehind: isset($obj->{'PersonChiefMaleDegreeBehind'}) ? (string) $obj->{'PersonChiefMaleDegreeBehind'} : null,
            personChiefFemale: isset($obj->{'PersonChiefFemale'}) ? (string) $obj->{'PersonChiefFemale'} : null,
            personChiefFemaleDegreeFront: isset($obj->{'PersonChiefFemaleDegreeFront'}) ? (string) $obj->{'PersonChiefFemaleDegreeFront'} : null,
            personChiefFemaleDegreeBehind: isset($obj->{'PersonChiefFemaleDegreeBehind'}) ? (string) $obj->{'PersonChiefFemaleDegreeBehind'} : null,
            personLeader: isset($obj->{'PersonLeader'}) ? (string) $obj->{'PersonLeader'} : null,
            personLeaderDegreeFront: isset($obj->{'PersonLeaderDegreeFront'}) ? (string) $obj->{'PersonLeaderDegreeFront'} : null,
            personLeaderDegreeBehind: isset($obj->{'PersonLeaderDegreeBehind'}) ? (string) $obj->{'PersonLeaderDegreeBehind'} : null,
            personGarant: isset($obj->{'PersonGarant'}) ? (string) $obj->{'PersonGarant'} : null,
            personGarantDegreeFront: isset($obj->{'PersonGarantDegreeFront'}) ? (string) $obj->{'PersonGarantDegreeFront'} : null,
            personGarantDegreeBehind: isset($obj->{'PersonGarantDegreeBehind'}) ? (string) $obj->{'PersonGarantDegreeBehind'} : null,
            person: isset($obj->{'Person'}) ? (string) $obj->{'Person'} : null,
            personDegreeFront: isset($obj->{'PersonDegreeFront'}) ? (string) $obj->{'PersonDegreeFront'} : null,
            personDegreeBehind: isset($obj->{'PersonDegreeBehind'}) ? (string) $obj->{'PersonDegreeBehind'} : null,
            personBirthday: isset($obj->{'PersonBirthday'}) ? (string) $obj->{'PersonBirthday'} : null,
            personSex: isset($obj->{'PersonSex'}) ? (string) $obj->{'PersonSex'} : null,
            date: isset($obj->{'Date'}) ? (string) $obj->{'Date'} : null,
            letterNumber: isset($obj->{'LetterNumber'}) ? (string) $obj->{'LetterNumber'} : null,
            idEventEducationExam: isset($obj->{'ID_EventEducationExam'}) ? (int) $obj->{'ID_EventEducationExam'} : null,
            dateExam: isset($obj->{'DateExam'}) ? (string) $obj->{'DateExam'} : null,
            key: isset($obj->{'Key'}) ? (string) $obj->{'Key'} : null,
            idEventEducationGroup: isset($obj->{'ID_EventEducationGroup'}) ? (string) $obj->{'ID_EventEducationGroup'} : null,
            eventEducationGroup: isset($obj->{'EventEducationGroup'}) ? (string) $obj->{'EventEducationGroup'} : null,
            idQualificationType: isset($obj->{'ID_QualificationType'}) ? (int) $obj->{'ID_QualificationType'} : null,
            qualificationType: isset($obj->{'QualificationType'}) ? (string) $obj->{'QualificationType'} : null,
            idEventEducationType: isset($obj->{'ID_EventEducationType'}) ? (int) $obj->{'ID_EventEducationType'} : null,
            eventEducationType: isset($obj->{'EventEducationType'}) ? (string) $obj->{'EventEducationType'} : null,
            eventEducation: isset($obj->{'EventEducation'}) ? (string) $obj->{'EventEducation'} : null,
            organizer: isset($obj->{'Organizer'}) ? (string) $obj->{'Organizer'} : null,
            organizerRegistrationNumber: isset($obj->{'OrganizerRegistrationNumber'}) ? (string) $obj->{'OrganizerRegistrationNumber'} : null,
            isExam: isset($obj->{'IsExam'}) ? (bool) $obj->{'IsExam'} : null,
            dateGenerated: isset($obj->{'DateGenerated'}) ? (string) $obj->{'DateGenerated'} : null,
        );
    }
}
