<?php

namespace Misakstvanu\LaravelSkautis\Responses\Events;

final class EventEducationLetterRequestAllAttachmentExportOutput
{
    public function __construct(
        public readonly ?int $id = null,
        public readonly ?string $personReporter = null,
        public readonly ?string $personReporterFunctionType = null,
        public readonly ?string $personCommissionLeader = null,
        public readonly ?string $personCommissionLeaderFunctionType = null,
        public readonly ?string $personMajorCaptainWaterScouts = null,
        public readonly ?string $personMajorCaptainWaterScoutsFunctionType = null,
        public readonly ?string $personChiefMale = null,
        public readonly ?string $personChiefMaleFunctionType = null,
        public readonly ?string $personChiefFemale = null,
        public readonly ?string $personChiefFemaleFunctionType = null,
        public readonly ?string $personLeader = null,
        public readonly ?string $personLeaderFunctionType = null,
        public readonly ?string $personGarant = null,
        public readonly ?string $person = null,
        public readonly ?string $personBirthday = null,
        public readonly ?string $personSex = null,
        public readonly ?string $displayAdress = null,
        public readonly ?string $date = null,
        public readonly ?string $letterNumber = null,
        public readonly ?int $idEventEducationExam = null,
        public readonly ?string $dateExam = null,
        public readonly ?string $key = null,
        public readonly ?string $idEventEducationGroup = null,
        public readonly ?string $eventEducationGroup = null,
        public readonly ?int $idQualificationType = null,
        public readonly ?string $qualificationType = null,
        public readonly ?int $idEventEducationType = null,
        public readonly ?string $eventEducationType = null,
        public readonly ?string $eventEducation = null,
        public readonly ?string $organizer = null,
        public readonly ?string $organizerRegistrationNumber = null,
        public readonly ?bool $isExam = null,
        public readonly ?string $qualificationTypeKey = null,
        public readonly ?string $unitAddres = null,
        public readonly ?string $unitICO = null,
        public readonly ?string $location = null,
        public readonly ?string $dateGenerated = null,
    ) {}

    public static function fromStdClass(\stdClass $obj): self
    {
        return new self(
            id: isset($obj->{'ID'}) ? (int) $obj->{'ID'} : null,
            personReporter: isset($obj->{'PersonReporter'}) ? (string) $obj->{'PersonReporter'} : null,
            personReporterFunctionType: isset($obj->{'PersonReporterFunctionType'}) ? (string) $obj->{'PersonReporterFunctionType'} : null,
            personCommissionLeader: isset($obj->{'PersonCommissionLeader'}) ? (string) $obj->{'PersonCommissionLeader'} : null,
            personCommissionLeaderFunctionType: isset($obj->{'PersonCommissionLeaderFunctionType'}) ? (string) $obj->{'PersonCommissionLeaderFunctionType'} : null,
            personMajorCaptainWaterScouts: isset($obj->{'PersonMajorCaptainWaterScouts'}) ? (string) $obj->{'PersonMajorCaptainWaterScouts'} : null,
            personMajorCaptainWaterScoutsFunctionType: isset($obj->{'PersonMajorCaptainWaterScoutsFunctionType'}) ? (string) $obj->{'PersonMajorCaptainWaterScoutsFunctionType'} : null,
            personChiefMale: isset($obj->{'PersonChiefMale'}) ? (string) $obj->{'PersonChiefMale'} : null,
            personChiefMaleFunctionType: isset($obj->{'PersonChiefMaleFunctionType'}) ? (string) $obj->{'PersonChiefMaleFunctionType'} : null,
            personChiefFemale: isset($obj->{'PersonChiefFemale'}) ? (string) $obj->{'PersonChiefFemale'} : null,
            personChiefFemaleFunctionType: isset($obj->{'PersonChiefFemaleFunctionType'}) ? (string) $obj->{'PersonChiefFemaleFunctionType'} : null,
            personLeader: isset($obj->{'PersonLeader'}) ? (string) $obj->{'PersonLeader'} : null,
            personLeaderFunctionType: isset($obj->{'PersonLeaderFunctionType'}) ? (string) $obj->{'PersonLeaderFunctionType'} : null,
            personGarant: isset($obj->{'PersonGarant'}) ? (string) $obj->{'PersonGarant'} : null,
            person: isset($obj->{'Person'}) ? (string) $obj->{'Person'} : null,
            personBirthday: isset($obj->{'PersonBirthday'}) ? (string) $obj->{'PersonBirthday'} : null,
            personSex: isset($obj->{'PersonSex'}) ? (string) $obj->{'PersonSex'} : null,
            displayAdress: isset($obj->{'DisplayAdress'}) ? (string) $obj->{'DisplayAdress'} : null,
            date: isset($obj->{'Date'}) ? (string) $obj->{'Date'} : null,
            letterNumber: isset($obj->{'LetterNumber'}) ? (string) $obj->{'LetterNumber'} : null,
            idEventEducationExam: isset($obj->{'ID_EventEducationExam'}) ? (int) $obj->{'ID_EventEducationExam'} : null,
            dateExam: isset($obj->{'DateExam'}) ? (string) $obj->{'DateExam'} : null,
            key: isset($obj->{'Key'}) ? (string) $obj->{'Key'} : null,
            idEventEducationGroup: isset($obj->{'ID_EventEducationGroup'}) ? (string) $obj->{'ID_EventEducationGroup'} : null,
            eventEducationGroup: isset($obj->{'EventEducationGroup'}) ? (string) $obj->{'EventEducationGroup'} : null,
            idQualificationType: isset($obj->{'ID_QualificationType'}) ? (int) $obj->{'ID_QualificationType'} : null,
            qualificationType: isset($obj->{'QualificationType'}) ? (string) $obj->{'QualificationType'} : null,
            idEventEducationType: isset($obj->{'ID_EventEducationType'}) ? (int) $obj->{'ID_EventEducationType'} : null,
            eventEducationType: isset($obj->{'EventEducationType'}) ? (string) $obj->{'EventEducationType'} : null,
            eventEducation: isset($obj->{'EventEducation'}) ? (string) $obj->{'EventEducation'} : null,
            organizer: isset($obj->{'Organizer'}) ? (string) $obj->{'Organizer'} : null,
            organizerRegistrationNumber: isset($obj->{'OrganizerRegistrationNumber'}) ? (string) $obj->{'OrganizerRegistrationNumber'} : null,
            isExam: isset($obj->{'IsExam'}) ? (bool) $obj->{'IsExam'} : null,
            qualificationTypeKey: isset($obj->{'QualificationTypeKey'}) ? (string) $obj->{'QualificationTypeKey'} : null,
            unitAddres: isset($obj->{'UnitAddres'}) ? (string) $obj->{'UnitAddres'} : null,
            unitICO: isset($obj->{'UnitICO'}) ? (string) $obj->{'UnitICO'} : null,
            location: isset($obj->{'Location'}) ? (string) $obj->{'Location'} : null,
            dateGenerated: isset($obj->{'DateGenerated'}) ? (string) $obj->{'DateGenerated'} : null,
        );
    }
}
