<?php

namespace Misakstvanu\LaravelSkautis\Responses\Events;

final class EventEducationAllPublicOutput
{
    public function __construct(
        public readonly ?int $id = null,
        public readonly ?string $displayName = null,
        public readonly ?string $idEventEducationState = null,
        public readonly ?string $eventEducationState = null,
        public readonly ?string $web = null,
        public readonly ?string $emailContact = null,
        public readonly ?string $phoneContact = null,
        public readonly ?string $logoFileName = null,
        public readonly ?int $idDocumentLogo = null,
        public readonly ?int $idDocumentLogoPreview = null,
        public readonly ?int $idDocumentLogoMiniature = null,
        public readonly ?string $description = null,
        public readonly ?int $idEvent = null,
        public readonly ?string $event = null,
        public readonly ?bool $loginSkautis = null,
        public readonly ?string $loginLocation = null,
        public readonly ?int $participantCount = null,
        public readonly ?int $participantSubstituteCount = null,
        public readonly ?string $firstTerm = null,
        public readonly ?string $lastTerm = null,
        public readonly ?int $duration = null,
        public readonly ?string $registrationDeadline = null,
        public readonly ?int $courseDuration = null,
        public readonly ?bool $isQualifyingExam = null,
        public readonly ?string $idEventEducationGroup = null,
        public readonly ?string $eventEducationGroup = null,
        public readonly ?int $idOccupancy = null,
        public readonly ?string $termList = null,
        public readonly ?string $occupancy = null,
        public readonly ?string $entryConditions = null,
        public readonly ?string $graduateConditions = null,
        public readonly ?float $participantFee = null,
        public readonly ?int $lastOccurrenceYear = null,
        public readonly ?int $nextOccurrenceYear = null,
        public readonly ?string $courseFrequency = null,
        public readonly ?int $idPersonLeader = null,
        public readonly ?string $personLeader = null,
        public readonly ?string $annotation = null,
        public readonly ?string $eventFocus = null,
        public readonly ?string $photoGallery = null,
        public readonly ?string $authenticationForm = null,
        public readonly ?bool $isAccredited = null,
        public readonly ?string $eventHistory = null,
        public readonly ?float $fulfilment = null,
        public readonly ?string $publicized = null,
        public readonly ?int $idUnit = null,
        public readonly ?string $unit = null,
        public readonly ?string $unitRegistrationNumber = null,
        public readonly ?string $unitFullName = null,
        public readonly ?string $loginFrom = null,
        public readonly ?string $loginTo = null,
    ) {}

    public static function fromStdClass(\stdClass $obj): self
    {
        return new self(
            id: isset($obj->{'ID'}) ? (int) $obj->{'ID'} : null,
            displayName: isset($obj->{'DisplayName'}) ? (string) $obj->{'DisplayName'} : null,
            idEventEducationState: isset($obj->{'ID_EventEducationState'}) ? (string) $obj->{'ID_EventEducationState'} : null,
            eventEducationState: isset($obj->{'EventEducationState'}) ? (string) $obj->{'EventEducationState'} : null,
            web: isset($obj->{'Web'}) ? (string) $obj->{'Web'} : null,
            emailContact: isset($obj->{'EmailContact'}) ? (string) $obj->{'EmailContact'} : null,
            phoneContact: isset($obj->{'PhoneContact'}) ? (string) $obj->{'PhoneContact'} : null,
            logoFileName: isset($obj->{'LogoFileName'}) ? (string) $obj->{'LogoFileName'} : null,
            idDocumentLogo: isset($obj->{'ID_DocumentLogo'}) ? (int) $obj->{'ID_DocumentLogo'} : null,
            idDocumentLogoPreview: isset($obj->{'ID_DocumentLogoPreview'}) ? (int) $obj->{'ID_DocumentLogoPreview'} : null,
            idDocumentLogoMiniature: isset($obj->{'ID_DocumentLogoMiniature'}) ? (int) $obj->{'ID_DocumentLogoMiniature'} : null,
            description: isset($obj->{'Description'}) ? (string) $obj->{'Description'} : null,
            idEvent: isset($obj->{'ID_Event'}) ? (int) $obj->{'ID_Event'} : null,
            event: isset($obj->{'Event'}) ? (string) $obj->{'Event'} : null,
            loginSkautis: isset($obj->{'LoginSkautis'}) ? (bool) $obj->{'LoginSkautis'} : null,
            loginLocation: isset($obj->{'LoginLocation'}) ? (string) $obj->{'LoginLocation'} : null,
            participantCount: isset($obj->{'ParticipantCount'}) ? (int) $obj->{'ParticipantCount'} : null,
            participantSubstituteCount: isset($obj->{'ParticipantSubstituteCount'}) ? (int) $obj->{'ParticipantSubstituteCount'} : null,
            firstTerm: isset($obj->{'FirstTerm'}) ? (string) $obj->{'FirstTerm'} : null,
            lastTerm: isset($obj->{'LastTerm'}) ? (string) $obj->{'LastTerm'} : null,
            duration: isset($obj->{'Duration'}) ? (int) $obj->{'Duration'} : null,
            registrationDeadline: isset($obj->{'RegistrationDeadline'}) ? (string) $obj->{'RegistrationDeadline'} : null,
            courseDuration: isset($obj->{'CourseDuration'}) ? (int) $obj->{'CourseDuration'} : null,
            isQualifyingExam: isset($obj->{'IsQualifyingExam'}) ? (bool) $obj->{'IsQualifyingExam'} : null,
            idEventEducationGroup: isset($obj->{'ID_EventEducationGroup'}) ? (string) $obj->{'ID_EventEducationGroup'} : null,
            eventEducationGroup: isset($obj->{'EventEducationGroup'}) ? (string) $obj->{'EventEducationGroup'} : null,
            idOccupancy: isset($obj->{'ID_Occupancy'}) ? (int) $obj->{'ID_Occupancy'} : null,
            termList: isset($obj->{'TermList'}) ? (string) $obj->{'TermList'} : null,
            occupancy: isset($obj->{'Occupancy'}) ? (string) $obj->{'Occupancy'} : null,
            entryConditions: isset($obj->{'EntryConditions'}) ? (string) $obj->{'EntryConditions'} : null,
            graduateConditions: isset($obj->{'GraduateConditions'}) ? (string) $obj->{'GraduateConditions'} : null,
            participantFee: isset($obj->{'ParticipantFee'}) ? (float) $obj->{'ParticipantFee'} : null,
            lastOccurrenceYear: isset($obj->{'LastOccurrenceYear'}) ? (int) $obj->{'LastOccurrenceYear'} : null,
            nextOccurrenceYear: isset($obj->{'NextOccurrenceYear'}) ? (int) $obj->{'NextOccurrenceYear'} : null,
            courseFrequency: isset($obj->{'CourseFrequency'}) ? (string) $obj->{'CourseFrequency'} : null,
            idPersonLeader: isset($obj->{'ID_PersonLeader'}) ? (int) $obj->{'ID_PersonLeader'} : null,
            personLeader: isset($obj->{'PersonLeader'}) ? (string) $obj->{'PersonLeader'} : null,
            annotation: isset($obj->{'Annotation'}) ? (string) $obj->{'Annotation'} : null,
            eventFocus: isset($obj->{'EventFocus'}) ? (string) $obj->{'EventFocus'} : null,
            photoGallery: isset($obj->{'PhotoGallery'}) ? (string) $obj->{'PhotoGallery'} : null,
            authenticationForm: isset($obj->{'AuthenticationForm'}) ? (string) $obj->{'AuthenticationForm'} : null,
            isAccredited: isset($obj->{'IsAccredited'}) ? (bool) $obj->{'IsAccredited'} : null,
            eventHistory: isset($obj->{'EventHistory'}) ? (string) $obj->{'EventHistory'} : null,
            fulfilment: isset($obj->{'Fulfilment'}) ? (float) $obj->{'Fulfilment'} : null,
            publicized: isset($obj->{'Publicized'}) ? (string) $obj->{'Publicized'} : null,
            idUnit: isset($obj->{'ID_Unit'}) ? (int) $obj->{'ID_Unit'} : null,
            unit: isset($obj->{'Unit'}) ? (string) $obj->{'Unit'} : null,
            unitRegistrationNumber: isset($obj->{'UnitRegistrationNumber'}) ? (string) $obj->{'UnitRegistrationNumber'} : null,
            unitFullName: isset($obj->{'UnitFullName'}) ? (string) $obj->{'UnitFullName'} : null,
            loginFrom: isset($obj->{'LoginFrom'}) ? (string) $obj->{'LoginFrom'} : null,
            loginTo: isset($obj->{'LoginTo'}) ? (string) $obj->{'LoginTo'} : null,
        );
    }
}
