<?php

namespace Misakstvanu\LaravelSkautis\Responses\Events;

final class EventEducationDetailEventOutput
{
    public function __construct(
        public readonly ?string $idLogin = null,
        public readonly ?int $id = null,
        public readonly ?string $idEventEducationState = null,
        public readonly ?string $eventEducationState = null,
        public readonly ?string $web = null,
        public readonly ?string $emailContact = null,
        public readonly ?string $phoneContact = null,
        public readonly ?string $dateApproved = null,
        public readonly ?float $grant = null,
        public readonly ?string $idGrantType = null,
        public readonly ?string $grantType = null,
        public readonly ?string $idGrantAdvanceType = null,
        public readonly ?string $grantAdvanceType = null,
        public readonly ?string $dateClosed = null,
        public readonly ?int $idPersonClosed = null,
        public readonly ?string $personClosed = null,
        public readonly ?string $logoFileName = null,
        public readonly ?string $propagationFileName1 = null,
        public readonly ?string $propagationFileName2 = null,
        public readonly ?string $propagationFileName3 = null,
        public readonly ?bool $loginSkautis = null,
        public readonly ?string $loginLocation = null,
        public readonly ?string $description = null,
        public readonly ?string $displayName = null,
        public readonly ?int $idUnit = null,
        public readonly ?string $startDate = null,
        public readonly ?string $endDate = null,
        public readonly ?string $location = null,
        public readonly ?int $idEventEducationType = null,
        public readonly ?string $note = null,
        public readonly ?string $unit = null,
        public readonly ?string $registrationNumber = null,
        public readonly ?int $idEvent = null,
        public readonly ?int $idPersonLeader = null,
        public readonly ?string $personLeader = null,
        public readonly ?string $leaderPhone = null,
        public readonly ?string $leaderPhoneDisplay = null,
        public readonly ?string $leaderEmail = null,
        public readonly ?string $leaderEmailDisplay = null,
        public readonly ?string $leaderNote = null,
        public readonly ?int $idPersonAssistant = null,
        public readonly ?string $assistantNote = null,
        public readonly ?int $idPersonSecretary = null,
        public readonly ?string $secretaryNote = null,
        public readonly ?int $idPersonEconomist = null,
        public readonly ?string $economistNote = null,
        public readonly ?string $registrationDeadline = null,
        public readonly ?string $logoContent = null,
        public readonly ?int $idDocumentLogo = null,
        public readonly ?int $idDocumentLogoPreview = null,
        public readonly ?int $idDocumentLogoMiniature = null,
        public readonly ?string $idTempFileLogo = null,
        public readonly ?string $idTempFileProject = null,
        public readonly ?bool $projectDelete = null,
        public readonly ?string $project = null,
        public readonly ?int $idDocumentProject = null,
        public readonly ?string $projectExtension = null,
        public readonly ?string $projectNote = null,
        public readonly ?string $projectContent = null,
        public readonly ?int $idPersonProject = null,
        public readonly ?string $personProject = null,
        public readonly ?string $projectApproved = null,
        public readonly ?string $projectUpdate = null,
        public readonly ?string $idTempFileFinalReport = null,
        public readonly ?bool $finalReportDelete = null,
        public readonly ?string $finalReport = null,
        public readonly ?int $idDocumentFinalReport = null,
        public readonly ?string $finalReportExtension = null,
        public readonly ?string $finalReportNote = null,
        public readonly ?string $finalReportContent = null,
        public readonly ?int $idPersonFinalReport = null,
        public readonly ?string $personFinalReport = null,
        public readonly ?string $finalReportUpdate = null,
        public readonly ?string $finalReportApproved = null,
        public readonly ?string $rejectionNote = null,
        public readonly ?string $disapproveNote = null,
        public readonly ?string $waterDisapproveNote = null,
        public readonly ?bool $isWaterman = null,
        public readonly ?bool $isForester = null,
        public readonly ?bool $isPossibleToGraduate = null,
        public readonly ?string $published = null,
        public readonly ?string $confirmed = null,
        public readonly ?string $approved = null,
        public readonly ?string $approvedWater = null,
        public readonly ?string $grantNew = null,
        public readonly ?string $grantApproved = null,
        public readonly ?string $grantDecisionNew = null,
        public readonly ?string $grantDecisionConfirmed = null,
        public readonly ?string $advanceSent = null,
        public readonly ?int $idGrant = null,
        public readonly ?float $fulfilment = null,
        public readonly ?string $publicized = null,
        public readonly ?string $idGrantState = null,
        public readonly ?bool $isQualifyingExam = null,
        public readonly ?bool $hasGrantRequest = null,
        public readonly ?bool $hasTermsOnlyForNextYear = null,
        public readonly ?string $lastTerm = null,
        public readonly ?bool $isCounselor = null,
        public readonly ?string $dateUnitApproved = null,
        public readonly ?bool $isProjectRequired = null,
        public readonly ?bool $isFinalReportRequired = null,
        public readonly ?bool $isConditionCheckManual = null,
        public readonly ?string $isConditionCheckManualNote = null,
        public readonly ?string $loginFrom = null,
        public readonly ?string $loginTo = null,
        public readonly ?bool $isEditable = null,
        public readonly ?int $participantSubstitute = null,
        public readonly ?int $participantEstimated = null,
        public readonly ?string $displayNameCourse = null,
        public readonly ?int $capacityCourse = null,
    ) {}

    public static function fromStdClass(\stdClass $obj): self
    {
        return new self(
            idLogin: isset($obj->{'ID_Login'}) ? (string) $obj->{'ID_Login'} : null,
            id: isset($obj->{'ID'}) ? (int) $obj->{'ID'} : null,
            idEventEducationState: isset($obj->{'ID_EventEducationState'}) ? (string) $obj->{'ID_EventEducationState'} : null,
            eventEducationState: isset($obj->{'EventEducationState'}) ? (string) $obj->{'EventEducationState'} : null,
            web: isset($obj->{'Web'}) ? (string) $obj->{'Web'} : null,
            emailContact: isset($obj->{'EmailContact'}) ? (string) $obj->{'EmailContact'} : null,
            phoneContact: isset($obj->{'PhoneContact'}) ? (string) $obj->{'PhoneContact'} : null,
            dateApproved: isset($obj->{'DateApproved'}) ? (string) $obj->{'DateApproved'} : null,
            grant: isset($obj->{'Grant'}) ? (float) $obj->{'Grant'} : null,
            idGrantType: isset($obj->{'ID_GrantType'}) ? (string) $obj->{'ID_GrantType'} : null,
            grantType: isset($obj->{'GrantType'}) ? (string) $obj->{'GrantType'} : null,
            idGrantAdvanceType: isset($obj->{'ID_GrantAdvanceType'}) ? (string) $obj->{'ID_GrantAdvanceType'} : null,
            grantAdvanceType: isset($obj->{'GrantAdvanceType'}) ? (string) $obj->{'GrantAdvanceType'} : null,
            dateClosed: isset($obj->{'DateClosed'}) ? (string) $obj->{'DateClosed'} : null,
            idPersonClosed: isset($obj->{'ID_PersonClosed'}) ? (int) $obj->{'ID_PersonClosed'} : null,
            personClosed: isset($obj->{'PersonClosed'}) ? (string) $obj->{'PersonClosed'} : null,
            logoFileName: isset($obj->{'LogoFileName'}) ? (string) $obj->{'LogoFileName'} : null,
            propagationFileName1: isset($obj->{'PropagationFileName1'}) ? (string) $obj->{'PropagationFileName1'} : null,
            propagationFileName2: isset($obj->{'PropagationFileName2'}) ? (string) $obj->{'PropagationFileName2'} : null,
            propagationFileName3: isset($obj->{'PropagationFileName3'}) ? (string) $obj->{'PropagationFileName3'} : null,
            loginSkautis: isset($obj->{'LoginSkautis'}) ? (bool) $obj->{'LoginSkautis'} : null,
            loginLocation: isset($obj->{'LoginLocation'}) ? (string) $obj->{'LoginLocation'} : null,
            description: isset($obj->{'Description'}) ? (string) $obj->{'Description'} : null,
            displayName: isset($obj->{'DisplayName'}) ? (string) $obj->{'DisplayName'} : null,
            idUnit: isset($obj->{'ID_Unit'}) ? (int) $obj->{'ID_Unit'} : null,
            startDate: isset($obj->{'StartDate'}) ? (string) $obj->{'StartDate'} : null,
            endDate: isset($obj->{'EndDate'}) ? (string) $obj->{'EndDate'} : null,
            location: isset($obj->{'Location'}) ? (string) $obj->{'Location'} : null,
            idEventEducationType: isset($obj->{'ID_EventEducationType'}) ? (int) $obj->{'ID_EventEducationType'} : null,
            note: isset($obj->{'Note'}) ? (string) $obj->{'Note'} : null,
            unit: isset($obj->{'Unit'}) ? (string) $obj->{'Unit'} : null,
            registrationNumber: isset($obj->{'RegistrationNumber'}) ? (string) $obj->{'RegistrationNumber'} : null,
            idEvent: isset($obj->{'ID_Event'}) ? (int) $obj->{'ID_Event'} : null,
            idPersonLeader: isset($obj->{'ID_PersonLeader'}) ? (int) $obj->{'ID_PersonLeader'} : null,
            personLeader: isset($obj->{'PersonLeader'}) ? (string) $obj->{'PersonLeader'} : null,
            leaderPhone: isset($obj->{'LeaderPhone'}) ? (string) $obj->{'LeaderPhone'} : null,
            leaderPhoneDisplay: isset($obj->{'LeaderPhoneDisplay'}) ? (string) $obj->{'LeaderPhoneDisplay'} : null,
            leaderEmail: isset($obj->{'LeaderEmail'}) ? (string) $obj->{'LeaderEmail'} : null,
            leaderEmailDisplay: isset($obj->{'LeaderEmailDisplay'}) ? (string) $obj->{'LeaderEmailDisplay'} : null,
            leaderNote: isset($obj->{'LeaderNote'}) ? (string) $obj->{'LeaderNote'} : null,
            idPersonAssistant: isset($obj->{'ID_PersonAssistant'}) ? (int) $obj->{'ID_PersonAssistant'} : null,
            assistantNote: isset($obj->{'AssistantNote'}) ? (string) $obj->{'AssistantNote'} : null,
            idPersonSecretary: isset($obj->{'ID_PersonSecretary'}) ? (int) $obj->{'ID_PersonSecretary'} : null,
            secretaryNote: isset($obj->{'SecretaryNote'}) ? (string) $obj->{'SecretaryNote'} : null,
            idPersonEconomist: isset($obj->{'ID_PersonEconomist'}) ? (int) $obj->{'ID_PersonEconomist'} : null,
            economistNote: isset($obj->{'EconomistNote'}) ? (string) $obj->{'EconomistNote'} : null,
            registrationDeadline: isset($obj->{'RegistrationDeadline'}) ? (string) $obj->{'RegistrationDeadline'} : null,
            logoContent: isset($obj->{'LogoContent'}) ? (string) $obj->{'LogoContent'} : null,
            idDocumentLogo: isset($obj->{'ID_DocumentLogo'}) ? (int) $obj->{'ID_DocumentLogo'} : null,
            idDocumentLogoPreview: isset($obj->{'ID_DocumentLogoPreview'}) ? (int) $obj->{'ID_DocumentLogoPreview'} : null,
            idDocumentLogoMiniature: isset($obj->{'ID_DocumentLogoMiniature'}) ? (int) $obj->{'ID_DocumentLogoMiniature'} : null,
            idTempFileLogo: isset($obj->{'ID_TempFileLogo'}) ? (string) $obj->{'ID_TempFileLogo'} : null,
            idTempFileProject: isset($obj->{'ID_TempFileProject'}) ? (string) $obj->{'ID_TempFileProject'} : null,
            projectDelete: isset($obj->{'ProjectDelete'}) ? (bool) $obj->{'ProjectDelete'} : null,
            project: isset($obj->{'Project'}) ? (string) $obj->{'Project'} : null,
            idDocumentProject: isset($obj->{'ID_DocumentProject'}) ? (int) $obj->{'ID_DocumentProject'} : null,
            projectExtension: isset($obj->{'ProjectExtension'}) ? (string) $obj->{'ProjectExtension'} : null,
            projectNote: isset($obj->{'ProjectNote'}) ? (string) $obj->{'ProjectNote'} : null,
            projectContent: isset($obj->{'ProjectContent'}) ? (string) $obj->{'ProjectContent'} : null,
            idPersonProject: isset($obj->{'ID_PersonProject'}) ? (int) $obj->{'ID_PersonProject'} : null,
            personProject: isset($obj->{'PersonProject'}) ? (string) $obj->{'PersonProject'} : null,
            projectApproved: isset($obj->{'ProjectApproved'}) ? (string) $obj->{'ProjectApproved'} : null,
            projectUpdate: isset($obj->{'ProjectUpdate'}) ? (string) $obj->{'ProjectUpdate'} : null,
            idTempFileFinalReport: isset($obj->{'ID_TempFileFinalReport'}) ? (string) $obj->{'ID_TempFileFinalReport'} : null,
            finalReportDelete: isset($obj->{'FinalReportDelete'}) ? (bool) $obj->{'FinalReportDelete'} : null,
            finalReport: isset($obj->{'FinalReport'}) ? (string) $obj->{'FinalReport'} : null,
            idDocumentFinalReport: isset($obj->{'ID_DocumentFinalReport'}) ? (int) $obj->{'ID_DocumentFinalReport'} : null,
            finalReportExtension: isset($obj->{'FinalReportExtension'}) ? (string) $obj->{'FinalReportExtension'} : null,
            finalReportNote: isset($obj->{'FinalReportNote'}) ? (string) $obj->{'FinalReportNote'} : null,
            finalReportContent: isset($obj->{'FinalReportContent'}) ? (string) $obj->{'FinalReportContent'} : null,
            idPersonFinalReport: isset($obj->{'ID_PersonFinalReport'}) ? (int) $obj->{'ID_PersonFinalReport'} : null,
            personFinalReport: isset($obj->{'PersonFinalReport'}) ? (string) $obj->{'PersonFinalReport'} : null,
            finalReportUpdate: isset($obj->{'FinalReportUpdate'}) ? (string) $obj->{'FinalReportUpdate'} : null,
            finalReportApproved: isset($obj->{'FinalReportApproved'}) ? (string) $obj->{'FinalReportApproved'} : null,
            rejectionNote: isset($obj->{'RejectionNote'}) ? (string) $obj->{'RejectionNote'} : null,
            disapproveNote: isset($obj->{'DisapproveNote'}) ? (string) $obj->{'DisapproveNote'} : null,
            waterDisapproveNote: isset($obj->{'WaterDisapproveNote'}) ? (string) $obj->{'WaterDisapproveNote'} : null,
            isWaterman: isset($obj->{'IsWaterman'}) ? (bool) $obj->{'IsWaterman'} : null,
            isForester: isset($obj->{'IsForester'}) ? (bool) $obj->{'IsForester'} : null,
            isPossibleToGraduate: isset($obj->{'IsPossibleToGraduate'}) ? (bool) $obj->{'IsPossibleToGraduate'} : null,
            published: isset($obj->{'Published'}) ? (string) $obj->{'Published'} : null,
            confirmed: isset($obj->{'Confirmed'}) ? (string) $obj->{'Confirmed'} : null,
            approved: isset($obj->{'Approved'}) ? (string) $obj->{'Approved'} : null,
            approvedWater: isset($obj->{'ApprovedWater'}) ? (string) $obj->{'ApprovedWater'} : null,
            grantNew: isset($obj->{'GrantNew'}) ? (string) $obj->{'GrantNew'} : null,
            grantApproved: isset($obj->{'GrantApproved'}) ? (string) $obj->{'GrantApproved'} : null,
            grantDecisionNew: isset($obj->{'GrantDecisionNew'}) ? (string) $obj->{'GrantDecisionNew'} : null,
            grantDecisionConfirmed: isset($obj->{'GrantDecisionConfirmed'}) ? (string) $obj->{'GrantDecisionConfirmed'} : null,
            advanceSent: isset($obj->{'AdvanceSent'}) ? (string) $obj->{'AdvanceSent'} : null,
            idGrant: isset($obj->{'ID_Grant'}) ? (int) $obj->{'ID_Grant'} : null,
            fulfilment: isset($obj->{'Fulfilment'}) ? (float) $obj->{'Fulfilment'} : null,
            publicized: isset($obj->{'Publicized'}) ? (string) $obj->{'Publicized'} : null,
            idGrantState: isset($obj->{'ID_GrantState'}) ? (string) $obj->{'ID_GrantState'} : null,
            isQualifyingExam: isset($obj->{'IsQualifyingExam'}) ? (bool) $obj->{'IsQualifyingExam'} : null,
            hasGrantRequest: isset($obj->{'HasGrantRequest'}) ? (bool) $obj->{'HasGrantRequest'} : null,
            hasTermsOnlyForNextYear: isset($obj->{'HasTermsOnlyForNextYear'}) ? (bool) $obj->{'HasTermsOnlyForNextYear'} : null,
            lastTerm: isset($obj->{'LastTerm'}) ? (string) $obj->{'LastTerm'} : null,
            isCounselor: isset($obj->{'IsCounselor'}) ? (bool) $obj->{'IsCounselor'} : null,
            dateUnitApproved: isset($obj->{'DateUnitApproved'}) ? (string) $obj->{'DateUnitApproved'} : null,
            isProjectRequired: isset($obj->{'IsProjectRequired'}) ? (bool) $obj->{'IsProjectRequired'} : null,
            isFinalReportRequired: isset($obj->{'IsFinalReportRequired'}) ? (bool) $obj->{'IsFinalReportRequired'} : null,
            isConditionCheckManual: isset($obj->{'IsConditionCheckManual'}) ? (bool) $obj->{'IsConditionCheckManual'} : null,
            isConditionCheckManualNote: isset($obj->{'IsConditionCheckManualNote'}) ? (string) $obj->{'IsConditionCheckManualNote'} : null,
            loginFrom: isset($obj->{'LoginFrom'}) ? (string) $obj->{'LoginFrom'} : null,
            loginTo: isset($obj->{'LoginTo'}) ? (string) $obj->{'LoginTo'} : null,
            isEditable: isset($obj->{'IsEditable'}) ? (bool) $obj->{'IsEditable'} : null,
            participantSubstitute: isset($obj->{'ParticipantSubstitute'}) ? (int) $obj->{'ParticipantSubstitute'} : null,
            participantEstimated: isset($obj->{'ParticipantEstimated'}) ? (int) $obj->{'ParticipantEstimated'} : null,
            displayNameCourse: isset($obj->{'DisplayNameCourse'}) ? (string) $obj->{'DisplayNameCourse'} : null,
            capacityCourse: isset($obj->{'CapacityCourse'}) ? (int) $obj->{'CapacityCourse'} : null,
        );
    }
}
