<?php

namespace Misakstvanu\LaravelSkautis\Responses\Events;

final class EventCampEnrollDetailPreviewOutput
{
    public function __construct(
        public readonly ?string $idLogin = null,
        public readonly ?int $id = null,
        public readonly ?int $idEventCamp = null,
        public readonly ?int $idPerson = null,
        public readonly ?string $person = null,
        public readonly ?string $code = null,
        public readonly ?string $validFrom = null,
        public readonly ?string $validTo = null,
        public readonly ?int $idEventCampInvitation = null,
        public readonly ?string $idCampEnrollState = null,
        public readonly ?string $campEnrollState = null,
        public readonly ?string $iconClass = null,
        public readonly ?string $icon = null,
        public readonly ?int $idAccount = null,
        public readonly ?string $accountNumber = null,
        public readonly ?string $accountPrefix = null,
        public readonly ?string $bankCode = null,
        public readonly ?float $price = null,
        public readonly ?string $paymentTerm = null,
        public readonly ?string $variableSymbol = null,
        public readonly ?string $specificSymbol = null,
        public readonly ?string $paymentNote = null,
        public readonly ?string $sPDString = null,
        public readonly ?string $eventCamp = null,
        public readonly ?string $campDate = null,
        public readonly ?string $participationTerm = null,
        public readonly ?string $location = null,
        public readonly ?string $personLeader = null,
        public readonly ?string $personAssistant = null,
        public readonly ?string $unit = null,
        public readonly ?string $registrationNumber = null,
        public readonly ?string $unitCity = null,
        public readonly ?string $unitIC = null,
        public readonly ?string $firstName = null,
        public readonly ?string $lastName = null,
        public readonly ?string $displayName = null,
        public readonly ?string $birthday = null,
        public readonly ?string $identificationCode = null,
        public readonly ?bool $isAdult = null,
        public readonly ?string $address = null,
        public readonly ?string $street = null,
        public readonly ?string $city = null,
        public readonly ?string $postcode = null,
        public readonly ?string $state = null,
        public readonly ?bool $isPostalSame = null,
        public readonly ?string $postalFirstLine = null,
        public readonly ?string $postalAddress = null,
        public readonly ?string $postalStreet = null,
        public readonly ?string $postalCity = null,
        public readonly ?string $postalPostcode = null,
        public readonly ?string $postalState = null,
        public readonly ?int $idAssurance = null,
        public readonly ?string $assurance = null,
        public readonly ?string $insuranceNumber = null,
        public readonly ?string $allergy = null,
        public readonly ?string $foodRestrictions = null,
        public readonly ?string $drugs = null,
        public readonly ?string $specialRequirements = null,
        public readonly ?string $healthLimitation = null,
        public readonly ?string $bodySkills = null,
        public readonly ?string $phone = null,
        public readonly ?string $email = null,
        public readonly ?int $idPersonParentPerson = null,
        public readonly ?int $idPersonParent = null,
        public readonly ?string $idParentType = null,
        public readonly ?string $parentType = null,
        public readonly ?string $parentTypeCustom = null,
        public readonly ?string $firstNameParent = null,
        public readonly ?string $lastNameParent = null,
        public readonly ?string $parentPersonFirstName = null,
        public readonly ?string $parentPersonLastName = null,
        public readonly ?string $emailParent = null,
        public readonly ?string $phoneParent = null,
        public readonly ?string $noteParent = null,
        public readonly ?string $parentCode = null,
        public readonly ?string $personParent = null,
        public readonly ?int $idPersonParentPerson2 = null,
        public readonly ?int $idPersonParent2 = null,
        public readonly ?string $idParentType2 = null,
        public readonly ?string $parentType2 = null,
        public readonly ?string $parentTypeCustom2 = null,
        public readonly ?string $firstNameParent2 = null,
        public readonly ?string $lastNameParent2 = null,
        public readonly ?string $parent2PersonFirstName = null,
        public readonly ?string $parent2PersonLastName = null,
        public readonly ?string $emailParent2 = null,
        public readonly ?string $phoneParent2 = null,
        public readonly ?string $noteParent2 = null,
        public readonly ?string $parentCode2 = null,
        public readonly ?string $personParent2 = null,
        public readonly ?string $phoneMainHelp = null,
        public readonly ?string $phoneMainPlaceholder = null,
        public readonly ?string $emailMainHelp = null,
        public readonly ?string $emailMainPlaceholder = null,
        public readonly ?bool $hasMembership = null,
        public readonly ?int $idDocumentCode = null,
        public readonly ?string $dateFilled = null,
        public readonly ?string $idPaymentType = null,
        public readonly ?string $paymentType = null,
        public readonly ?bool $hasParent = null,
        public readonly ?bool $haveCampLoginQuestionFile = null,
    ) {}

    public static function fromStdClass(\stdClass $obj): self
    {
        return new self(
            idLogin: isset($obj->{'ID_Login'}) ? (string) $obj->{'ID_Login'} : null,
            id: isset($obj->{'ID'}) ? (int) $obj->{'ID'} : null,
            idEventCamp: isset($obj->{'ID_EventCamp'}) ? (int) $obj->{'ID_EventCamp'} : null,
            idPerson: isset($obj->{'ID_Person'}) ? (int) $obj->{'ID_Person'} : null,
            person: isset($obj->{'Person'}) ? (string) $obj->{'Person'} : null,
            code: isset($obj->{'Code'}) ? (string) $obj->{'Code'} : null,
            validFrom: isset($obj->{'ValidFrom'}) ? (string) $obj->{'ValidFrom'} : null,
            validTo: isset($obj->{'ValidTo'}) ? (string) $obj->{'ValidTo'} : null,
            idEventCampInvitation: isset($obj->{'ID_EventCampInvitation'}) ? (int) $obj->{'ID_EventCampInvitation'} : null,
            idCampEnrollState: isset($obj->{'ID_CampEnrollState'}) ? (string) $obj->{'ID_CampEnrollState'} : null,
            campEnrollState: isset($obj->{'CampEnrollState'}) ? (string) $obj->{'CampEnrollState'} : null,
            iconClass: isset($obj->{'IconClass'}) ? (string) $obj->{'IconClass'} : null,
            icon: isset($obj->{'Icon'}) ? (string) $obj->{'Icon'} : null,
            idAccount: isset($obj->{'ID_Account'}) ? (int) $obj->{'ID_Account'} : null,
            accountNumber: isset($obj->{'AccountNumber'}) ? (string) $obj->{'AccountNumber'} : null,
            accountPrefix: isset($obj->{'AccountPrefix'}) ? (string) $obj->{'AccountPrefix'} : null,
            bankCode: isset($obj->{'BankCode'}) ? (string) $obj->{'BankCode'} : null,
            price: isset($obj->{'Price'}) ? (float) $obj->{'Price'} : null,
            paymentTerm: isset($obj->{'PaymentTerm'}) ? (string) $obj->{'PaymentTerm'} : null,
            variableSymbol: isset($obj->{'VariableSymbol'}) ? (string) $obj->{'VariableSymbol'} : null,
            specificSymbol: isset($obj->{'SpecificSymbol'}) ? (string) $obj->{'SpecificSymbol'} : null,
            paymentNote: isset($obj->{'PaymentNote'}) ? (string) $obj->{'PaymentNote'} : null,
            sPDString: isset($obj->{'SPDString'}) ? (string) $obj->{'SPDString'} : null,
            eventCamp: isset($obj->{'EventCamp'}) ? (string) $obj->{'EventCamp'} : null,
            campDate: isset($obj->{'CampDate'}) ? (string) $obj->{'CampDate'} : null,
            participationTerm: isset($obj->{'ParticipationTerm'}) ? (string) $obj->{'ParticipationTerm'} : null,
            location: isset($obj->{'Location'}) ? (string) $obj->{'Location'} : null,
            personLeader: isset($obj->{'PersonLeader'}) ? (string) $obj->{'PersonLeader'} : null,
            personAssistant: isset($obj->{'PersonAssistant'}) ? (string) $obj->{'PersonAssistant'} : null,
            unit: isset($obj->{'Unit'}) ? (string) $obj->{'Unit'} : null,
            registrationNumber: isset($obj->{'RegistrationNumber'}) ? (string) $obj->{'RegistrationNumber'} : null,
            unitCity: isset($obj->{'UnitCity'}) ? (string) $obj->{'UnitCity'} : null,
            unitIC: isset($obj->{'UnitIC'}) ? (string) $obj->{'UnitIC'} : null,
            firstName: isset($obj->{'FirstName'}) ? (string) $obj->{'FirstName'} : null,
            lastName: isset($obj->{'LastName'}) ? (string) $obj->{'LastName'} : null,
            displayName: isset($obj->{'DisplayName'}) ? (string) $obj->{'DisplayName'} : null,
            birthday: isset($obj->{'Birthday'}) ? (string) $obj->{'Birthday'} : null,
            identificationCode: isset($obj->{'IdentificationCode'}) ? (string) $obj->{'IdentificationCode'} : null,
            isAdult: isset($obj->{'IsAdult'}) ? (bool) $obj->{'IsAdult'} : null,
            address: isset($obj->{'Address'}) ? (string) $obj->{'Address'} : null,
            street: isset($obj->{'Street'}) ? (string) $obj->{'Street'} : null,
            city: isset($obj->{'City'}) ? (string) $obj->{'City'} : null,
            postcode: isset($obj->{'Postcode'}) ? (string) $obj->{'Postcode'} : null,
            state: isset($obj->{'State'}) ? (string) $obj->{'State'} : null,
            isPostalSame: isset($obj->{'IsPostalSame'}) ? (bool) $obj->{'IsPostalSame'} : null,
            postalFirstLine: isset($obj->{'PostalFirstLine'}) ? (string) $obj->{'PostalFirstLine'} : null,
            postalAddress: isset($obj->{'PostalAddress'}) ? (string) $obj->{'PostalAddress'} : null,
            postalStreet: isset($obj->{'PostalStreet'}) ? (string) $obj->{'PostalStreet'} : null,
            postalCity: isset($obj->{'PostalCity'}) ? (string) $obj->{'PostalCity'} : null,
            postalPostcode: isset($obj->{'PostalPostcode'}) ? (string) $obj->{'PostalPostcode'} : null,
            postalState: isset($obj->{'PostalState'}) ? (string) $obj->{'PostalState'} : null,
            idAssurance: isset($obj->{'ID_Assurance'}) ? (int) $obj->{'ID_Assurance'} : null,
            assurance: isset($obj->{'Assurance'}) ? (string) $obj->{'Assurance'} : null,
            insuranceNumber: isset($obj->{'InsuranceNumber'}) ? (string) $obj->{'InsuranceNumber'} : null,
            allergy: isset($obj->{'Allergy'}) ? (string) $obj->{'Allergy'} : null,
            foodRestrictions: isset($obj->{'FoodRestrictions'}) ? (string) $obj->{'FoodRestrictions'} : null,
            drugs: isset($obj->{'Drugs'}) ? (string) $obj->{'Drugs'} : null,
            specialRequirements: isset($obj->{'SpecialRequirements'}) ? (string) $obj->{'SpecialRequirements'} : null,
            healthLimitation: isset($obj->{'HealthLimitation'}) ? (string) $obj->{'HealthLimitation'} : null,
            bodySkills: isset($obj->{'BodySkills'}) ? (string) $obj->{'BodySkills'} : null,
            phone: isset($obj->{'Phone'}) ? (string) $obj->{'Phone'} : null,
            email: isset($obj->{'Email'}) ? (string) $obj->{'Email'} : null,
            idPersonParentPerson: isset($obj->{'ID_PersonParentPerson'}) ? (int) $obj->{'ID_PersonParentPerson'} : null,
            idPersonParent: isset($obj->{'ID_PersonParent'}) ? (int) $obj->{'ID_PersonParent'} : null,
            idParentType: isset($obj->{'ID_ParentType'}) ? (string) $obj->{'ID_ParentType'} : null,
            parentType: isset($obj->{'ParentType'}) ? (string) $obj->{'ParentType'} : null,
            parentTypeCustom: isset($obj->{'ParentTypeCustom'}) ? (string) $obj->{'ParentTypeCustom'} : null,
            firstNameParent: isset($obj->{'FirstNameParent'}) ? (string) $obj->{'FirstNameParent'} : null,
            lastNameParent: isset($obj->{'LastNameParent'}) ? (string) $obj->{'LastNameParent'} : null,
            parentPersonFirstName: isset($obj->{'ParentPersonFirstName'}) ? (string) $obj->{'ParentPersonFirstName'} : null,
            parentPersonLastName: isset($obj->{'ParentPersonLastName'}) ? (string) $obj->{'ParentPersonLastName'} : null,
            emailParent: isset($obj->{'EmailParent'}) ? (string) $obj->{'EmailParent'} : null,
            phoneParent: isset($obj->{'PhoneParent'}) ? (string) $obj->{'PhoneParent'} : null,
            noteParent: isset($obj->{'NoteParent'}) ? (string) $obj->{'NoteParent'} : null,
            parentCode: isset($obj->{'ParentCode'}) ? (string) $obj->{'ParentCode'} : null,
            personParent: isset($obj->{'PersonParent'}) ? (string) $obj->{'PersonParent'} : null,
            idPersonParentPerson2: isset($obj->{'ID_PersonParentPerson2'}) ? (int) $obj->{'ID_PersonParentPerson2'} : null,
            idPersonParent2: isset($obj->{'ID_PersonParent2'}) ? (int) $obj->{'ID_PersonParent2'} : null,
            idParentType2: isset($obj->{'ID_ParentType2'}) ? (string) $obj->{'ID_ParentType2'} : null,
            parentType2: isset($obj->{'ParentType2'}) ? (string) $obj->{'ParentType2'} : null,
            parentTypeCustom2: isset($obj->{'ParentTypeCustom2'}) ? (string) $obj->{'ParentTypeCustom2'} : null,
            firstNameParent2: isset($obj->{'FirstNameParent2'}) ? (string) $obj->{'FirstNameParent2'} : null,
            lastNameParent2: isset($obj->{'LastNameParent2'}) ? (string) $obj->{'LastNameParent2'} : null,
            parent2PersonFirstName: isset($obj->{'Parent2PersonFirstName'}) ? (string) $obj->{'Parent2PersonFirstName'} : null,
            parent2PersonLastName: isset($obj->{'Parent2PersonLastName'}) ? (string) $obj->{'Parent2PersonLastName'} : null,
            emailParent2: isset($obj->{'EmailParent2'}) ? (string) $obj->{'EmailParent2'} : null,
            phoneParent2: isset($obj->{'PhoneParent2'}) ? (string) $obj->{'PhoneParent2'} : null,
            noteParent2: isset($obj->{'NoteParent2'}) ? (string) $obj->{'NoteParent2'} : null,
            parentCode2: isset($obj->{'ParentCode2'}) ? (string) $obj->{'ParentCode2'} : null,
            personParent2: isset($obj->{'PersonParent2'}) ? (string) $obj->{'PersonParent2'} : null,
            phoneMainHelp: isset($obj->{'PhoneMainHelp'}) ? (string) $obj->{'PhoneMainHelp'} : null,
            phoneMainPlaceholder: isset($obj->{'PhoneMainPlaceholder'}) ? (string) $obj->{'PhoneMainPlaceholder'} : null,
            emailMainHelp: isset($obj->{'EmailMainHelp'}) ? (string) $obj->{'EmailMainHelp'} : null,
            emailMainPlaceholder: isset($obj->{'EmailMainPlaceholder'}) ? (string) $obj->{'EmailMainPlaceholder'} : null,
            hasMembership: isset($obj->{'HasMembership'}) ? (bool) $obj->{'HasMembership'} : null,
            idDocumentCode: isset($obj->{'ID_DocumentCode'}) ? (int) $obj->{'ID_DocumentCode'} : null,
            dateFilled: isset($obj->{'DateFilled'}) ? (string) $obj->{'DateFilled'} : null,
            idPaymentType: isset($obj->{'ID_PaymentType'}) ? (string) $obj->{'ID_PaymentType'} : null,
            paymentType: isset($obj->{'PaymentType'}) ? (string) $obj->{'PaymentType'} : null,
            hasParent: isset($obj->{'HasParent'}) ? (bool) $obj->{'HasParent'} : null,
            haveCampLoginQuestionFile: isset($obj->{'HaveCampLoginQuestionFile'}) ? (bool) $obj->{'HaveCampLoginQuestionFile'} : null,
        );
    }
}
