<?php

namespace Misakstvanu\LaravelSkautis\Responses\Events;

final class EventCampCapitalDataDetailOutput
{
    public function __construct(
        public readonly ?string $idLogin = null,
        public readonly ?int $id = null,
        public readonly ?int $idEventCamp = null,
        public readonly ?string $eventCamp = null,
        public readonly ?string $startDate = null,
        public readonly ?string $endDate = null,
        public readonly ?float $gpsLatitude = null,
        public readonly ?float $gpsLongitude = null,
        public readonly ?string $price = null,
        public readonly ?string $estimateDotation = null,
        public readonly ?int $estimateCount = null,
        public readonly ?bool $isAutoComputed = null,
        public readonly ?string $description = null,
        public readonly ?string $dateGenerated = null,
        public readonly ?string $personGenerated = null,
        public readonly ?string $dateSent = null,
        public readonly ?int $idPersonSent = null,
        public readonly ?string $personSent = null,
        public readonly ?int $idPersonCorrection = null,
        public readonly ?string $personCorrection = null,
        public readonly ?string $dateSentCorrection = null,
        public readonly ?string $map = null,
        public readonly ?string $projectCode = null,
        public readonly ?int $idEventCampCity = null,
        public readonly ?string $eventCampCity = null,
        public readonly ?int $cityZfoValue = null,
        public readonly ?int $idEventCampRegion = null,
        public readonly ?string $eventCampRegion = null,
        public readonly ?int $regionZfoValue = null,
        public readonly ?int $idEventCampZfoType = null,
        public readonly ?string $eventCampZfoType = null,
        public readonly ?int $zfoTypeZfoValue = null,
        public readonly ?int $idEventCampForm = null,
        public readonly ?string $eventCampForm = null,
        public readonly ?int $formZfoValue = null,
        public readonly ?int $idEventCampAccommodationForm = null,
        public readonly ?string $eventCampAccommodationForm = null,
        public readonly ?int $accommodationFormZfoValue = null,
    ) {}

    public static function fromStdClass(\stdClass $obj): self
    {
        return new self(
            idLogin: isset($obj->{'ID_Login'}) ? (string) $obj->{'ID_Login'} : null,
            id: isset($obj->{'ID'}) ? (int) $obj->{'ID'} : null,
            idEventCamp: isset($obj->{'ID_EventCamp'}) ? (int) $obj->{'ID_EventCamp'} : null,
            eventCamp: isset($obj->{'EventCamp'}) ? (string) $obj->{'EventCamp'} : null,
            startDate: isset($obj->{'StartDate'}) ? (string) $obj->{'StartDate'} : null,
            endDate: isset($obj->{'EndDate'}) ? (string) $obj->{'EndDate'} : null,
            gpsLatitude: isset($obj->{'GpsLatitude'}) ? (float) $obj->{'GpsLatitude'} : null,
            gpsLongitude: isset($obj->{'GpsLongitude'}) ? (float) $obj->{'GpsLongitude'} : null,
            price: isset($obj->{'Price'}) ? (string) $obj->{'Price'} : null,
            estimateDotation: isset($obj->{'EstimateDotation'}) ? (string) $obj->{'EstimateDotation'} : null,
            estimateCount: isset($obj->{'EstimateCount'}) ? (int) $obj->{'EstimateCount'} : null,
            isAutoComputed: isset($obj->{'IsAutoComputed'}) ? (bool) $obj->{'IsAutoComputed'} : null,
            description: isset($obj->{'Description'}) ? (string) $obj->{'Description'} : null,
            dateGenerated: isset($obj->{'DateGenerated'}) ? (string) $obj->{'DateGenerated'} : null,
            personGenerated: isset($obj->{'PersonGenerated'}) ? (string) $obj->{'PersonGenerated'} : null,
            dateSent: isset($obj->{'DateSent'}) ? (string) $obj->{'DateSent'} : null,
            idPersonSent: isset($obj->{'ID_PersonSent'}) ? (int) $obj->{'ID_PersonSent'} : null,
            personSent: isset($obj->{'PersonSent'}) ? (string) $obj->{'PersonSent'} : null,
            idPersonCorrection: isset($obj->{'ID_PersonCorrection'}) ? (int) $obj->{'ID_PersonCorrection'} : null,
            personCorrection: isset($obj->{'PersonCorrection'}) ? (string) $obj->{'PersonCorrection'} : null,
            dateSentCorrection: isset($obj->{'DateSentCorrection'}) ? (string) $obj->{'DateSentCorrection'} : null,
            map: isset($obj->{'Map'}) ? (string) $obj->{'Map'} : null,
            projectCode: isset($obj->{'ProjectCode'}) ? (string) $obj->{'ProjectCode'} : null,
            idEventCampCity: isset($obj->{'ID_EventCampCity'}) ? (int) $obj->{'ID_EventCampCity'} : null,
            eventCampCity: isset($obj->{'EventCampCity'}) ? (string) $obj->{'EventCampCity'} : null,
            cityZfoValue: isset($obj->{'CityZfoValue'}) ? (int) $obj->{'CityZfoValue'} : null,
            idEventCampRegion: isset($obj->{'ID_EventCampRegion'}) ? (int) $obj->{'ID_EventCampRegion'} : null,
            eventCampRegion: isset($obj->{'EventCampRegion'}) ? (string) $obj->{'EventCampRegion'} : null,
            regionZfoValue: isset($obj->{'RegionZfoValue'}) ? (int) $obj->{'RegionZfoValue'} : null,
            idEventCampZfoType: isset($obj->{'ID_EventCampZfoType'}) ? (int) $obj->{'ID_EventCampZfoType'} : null,
            eventCampZfoType: isset($obj->{'EventCampZfoType'}) ? (string) $obj->{'EventCampZfoType'} : null,
            zfoTypeZfoValue: isset($obj->{'ZfoTypeZfoValue'}) ? (int) $obj->{'ZfoTypeZfoValue'} : null,
            idEventCampForm: isset($obj->{'ID_EventCampForm'}) ? (int) $obj->{'ID_EventCampForm'} : null,
            eventCampForm: isset($obj->{'EventCampForm'}) ? (string) $obj->{'EventCampForm'} : null,
            formZfoValue: isset($obj->{'FormZfoValue'}) ? (int) $obj->{'FormZfoValue'} : null,
            idEventCampAccommodationForm: isset($obj->{'ID_EventCampAccommodationForm'}) ? (int) $obj->{'ID_EventCampAccommodationForm'} : null,
            eventCampAccommodationForm: isset($obj->{'EventCampAccommodationForm'}) ? (string) $obj->{'EventCampAccommodationForm'} : null,
            accommodationFormZfoValue: isset($obj->{'AccommodationFormZfoValue'}) ? (int) $obj->{'AccommodationFormZfoValue'} : null,
        );
    }
}
