<?php

namespace Misakstvanu\LaravelSkautis\Responses\Events;

final class EventCongressDetailOutput
{
    public function __construct(
        public readonly ?string $idLogin = null,
        public readonly ?int $id = null,
        public readonly ?int $idEvent = null,
        public readonly ?string $event = null,
        public readonly ?int $idUnitRegistration = null,
        public readonly ?string $unitRegistration = null,
        public readonly ?string $promulgationDeadline = null,
        public readonly ?string $commissionDeadline = null,
        public readonly ?string $candidateDeadline = null,
        public readonly ?string $idEventCongressType = null,
        public readonly ?string $eventCongressType = null,
        public readonly ?string $idEventCongressState = null,
        public readonly ?string $eventCongressState = null,
        public readonly ?int $idUnit = null,
        public readonly ?string $unit = null,
        public readonly ?string $registrationNumber = null,
        public readonly ?string $idUnitType = null,
        public readonly ?string $startDate = null,
        public readonly ?string $endDate = null,
        public readonly ?float $gpsLatitude = null,
        public readonly ?float $gpsLongitude = null,
        public readonly ?string $location = null,
        public readonly ?string $alternateStartDate = null,
        public readonly ?string $alternateEndDate = null,
        public readonly ?float $alternateGpsLatitude = null,
        public readonly ?float $alternateGpsLongitude = null,
        public readonly ?string $alternateLocation = null,
        public readonly ?string $note = null,
        public readonly ?string $protocolExtension = null,
        public readonly ?string $protocolContent = null,
        public readonly ?int $candidateAfterDeadline = null,
        public readonly ?string $arriveDeadline = null,
        public readonly ?string $departureDeadline = null,
        public readonly ?string $transportDeadline = null,
        public readonly ?string $accommodationDeadline = null,
        public readonly ?string $foodDeadline = null,
        public readonly ?float $participantFee = null,
        public readonly ?string $functionAgreementExtension = null,
        public readonly ?string $simplifiedEntryExtension = null,
        public readonly ?string $simplifiedEntryTemplateExtension = null,
        public readonly ?string $idTempFileSimplifiedEntry = null,
        public readonly ?int $delegateQuota = null,
        public readonly ?bool $isDelegateQuotaParentSet = null,
        public readonly ?int $idDocumentProtocol = null,
        public readonly ?int $idDocumentSimplifiedEntry = null,
        public readonly ?bool $statutoryFunctionNotAssigned = null,
    ) {}

    public static function fromStdClass(\stdClass $obj): self
    {
        return new self(
            idLogin: isset($obj->{'ID_Login'}) ? (string) $obj->{'ID_Login'} : null,
            id: isset($obj->{'ID'}) ? (int) $obj->{'ID'} : null,
            idEvent: isset($obj->{'ID_Event'}) ? (int) $obj->{'ID_Event'} : null,
            event: isset($obj->{'Event'}) ? (string) $obj->{'Event'} : null,
            idUnitRegistration: isset($obj->{'ID_UnitRegistration'}) ? (int) $obj->{'ID_UnitRegistration'} : null,
            unitRegistration: isset($obj->{'UnitRegistration'}) ? (string) $obj->{'UnitRegistration'} : null,
            promulgationDeadline: isset($obj->{'PromulgationDeadline'}) ? (string) $obj->{'PromulgationDeadline'} : null,
            commissionDeadline: isset($obj->{'CommissionDeadline'}) ? (string) $obj->{'CommissionDeadline'} : null,
            candidateDeadline: isset($obj->{'CandidateDeadline'}) ? (string) $obj->{'CandidateDeadline'} : null,
            idEventCongressType: isset($obj->{'ID_EventCongressType'}) ? (string) $obj->{'ID_EventCongressType'} : null,
            eventCongressType: isset($obj->{'EventCongressType'}) ? (string) $obj->{'EventCongressType'} : null,
            idEventCongressState: isset($obj->{'ID_EventCongressState'}) ? (string) $obj->{'ID_EventCongressState'} : null,
            eventCongressState: isset($obj->{'EventCongressState'}) ? (string) $obj->{'EventCongressState'} : null,
            idUnit: isset($obj->{'ID_Unit'}) ? (int) $obj->{'ID_Unit'} : null,
            unit: isset($obj->{'Unit'}) ? (string) $obj->{'Unit'} : null,
            registrationNumber: isset($obj->{'RegistrationNumber'}) ? (string) $obj->{'RegistrationNumber'} : null,
            idUnitType: isset($obj->{'ID_UnitType'}) ? (string) $obj->{'ID_UnitType'} : null,
            startDate: isset($obj->{'StartDate'}) ? (string) $obj->{'StartDate'} : null,
            endDate: isset($obj->{'EndDate'}) ? (string) $obj->{'EndDate'} : null,
            gpsLatitude: isset($obj->{'GpsLatitude'}) ? (float) $obj->{'GpsLatitude'} : null,
            gpsLongitude: isset($obj->{'GpsLongitude'}) ? (float) $obj->{'GpsLongitude'} : null,
            location: isset($obj->{'Location'}) ? (string) $obj->{'Location'} : null,
            alternateStartDate: isset($obj->{'AlternateStartDate'}) ? (string) $obj->{'AlternateStartDate'} : null,
            alternateEndDate: isset($obj->{'AlternateEndDate'}) ? (string) $obj->{'AlternateEndDate'} : null,
            alternateGpsLatitude: isset($obj->{'AlternateGpsLatitude'}) ? (float) $obj->{'AlternateGpsLatitude'} : null,
            alternateGpsLongitude: isset($obj->{'AlternateGpsLongitude'}) ? (float) $obj->{'AlternateGpsLongitude'} : null,
            alternateLocation: isset($obj->{'AlternateLocation'}) ? (string) $obj->{'AlternateLocation'} : null,
            note: isset($obj->{'Note'}) ? (string) $obj->{'Note'} : null,
            protocolExtension: isset($obj->{'ProtocolExtension'}) ? (string) $obj->{'ProtocolExtension'} : null,
            protocolContent: isset($obj->{'ProtocolContent'}) ? (string) $obj->{'ProtocolContent'} : null,
            candidateAfterDeadline: isset($obj->{'CandidateAfterDeadline'}) ? (int) $obj->{'CandidateAfterDeadline'} : null,
            arriveDeadline: isset($obj->{'ArriveDeadline'}) ? (string) $obj->{'ArriveDeadline'} : null,
            departureDeadline: isset($obj->{'DepartureDeadline'}) ? (string) $obj->{'DepartureDeadline'} : null,
            transportDeadline: isset($obj->{'TransportDeadline'}) ? (string) $obj->{'TransportDeadline'} : null,
            accommodationDeadline: isset($obj->{'AccommodationDeadline'}) ? (string) $obj->{'AccommodationDeadline'} : null,
            foodDeadline: isset($obj->{'FoodDeadline'}) ? (string) $obj->{'FoodDeadline'} : null,
            participantFee: isset($obj->{'ParticipantFee'}) ? (float) $obj->{'ParticipantFee'} : null,
            functionAgreementExtension: isset($obj->{'FunctionAgreementExtension'}) ? (string) $obj->{'FunctionAgreementExtension'} : null,
            simplifiedEntryExtension: isset($obj->{'SimplifiedEntryExtension'}) ? (string) $obj->{'SimplifiedEntryExtension'} : null,
            simplifiedEntryTemplateExtension: isset($obj->{'SimplifiedEntryTemplateExtension'}) ? (string) $obj->{'SimplifiedEntryTemplateExtension'} : null,
            idTempFileSimplifiedEntry: isset($obj->{'ID_TempFileSimplifiedEntry'}) ? (string) $obj->{'ID_TempFileSimplifiedEntry'} : null,
            delegateQuota: isset($obj->{'DelegateQuota'}) ? (int) $obj->{'DelegateQuota'} : null,
            isDelegateQuotaParentSet: isset($obj->{'IsDelegateQuotaParentSet'}) ? (bool) $obj->{'IsDelegateQuotaParentSet'} : null,
            idDocumentProtocol: isset($obj->{'ID_DocumentProtocol'}) ? (int) $obj->{'ID_DocumentProtocol'} : null,
            idDocumentSimplifiedEntry: isset($obj->{'ID_DocumentSimplifiedEntry'}) ? (int) $obj->{'ID_DocumentSimplifiedEntry'} : null,
            statutoryFunctionNotAssigned: isset($obj->{'StatutoryFunctionNotAssigned'}) ? (bool) $obj->{'StatutoryFunctionNotAssigned'} : null,
        );
    }
}
