<?php

namespace Misakstvanu\LaravelSkautis\Responses\Events;

final class EventEducationCourseDetailEnrollOutput
{
    public function __construct(
        public readonly ?string $idLogin = null,
        public readonly ?int $id = null,
        public readonly ?bool $isActive = null,
        public readonly ?int $idEventEducation = null,
        public readonly ?string $registrationDeadline = null,
        public readonly ?string $eventEducation = null,
        public readonly ?string $eventEducationCourse = null,
        public readonly ?int $idEventEducationType = null,
        public readonly ?string $eventEducationType = null,
        public readonly ?int $idUnit = null,
        public readonly ?string $unit = null,
        public readonly ?string $unitNameWithRegistrationNumber = null,
        public readonly ?string $registrationNumber = null,
        public readonly ?string $unitFullName = null,
        public readonly ?string $personDisplayName = null,
        public readonly ?string $personEmail = null,
        public readonly ?string $personPhone = null,
        public readonly ?string $address = null,
        public readonly ?string $identificationCode = null,
        public readonly ?string $firstName = null,
        public readonly ?string $lastName = null,
        public readonly ?string $nickName = null,
        public readonly ?string $street = null,
        public readonly ?string $city = null,
        public readonly ?string $postcode = null,
        public readonly ?int $idUnitMembership = null,
        public readonly ?string $unitMembership = null,
        public readonly ?string $unitMembershipWithRegistrationNumber = null,
        public readonly ?string $registrationNumberMembership = null,
        public readonly ?string $unitFullNameMembership = null,
        public readonly ?bool $isMember = null,
        public readonly ?int $idPerson = null,
        public readonly ?string $person = null,
        public readonly ?string $loginFrom = null,
        public readonly ?string $loginTo = null,
        public readonly ?bool $loginActive = null,
        public readonly ?bool $loginPassed = null,
        public readonly ?bool $loginInFuture = null,
        public readonly ?int $idParticipantEducation = null,
        public readonly ?bool $isVerdictGroupRequired = null,
        public readonly ?int $idPersonVerdictGroup = null,
        public readonly ?string $personVerdictGroup = null,
        public readonly ?string $dateVerdictGroup = null,
        public readonly ?string $verdictGroup = null,
        public readonly ?bool $isVerdictDistrictRequired = null,
        public readonly ?int $idPersonVerdictDistrict = null,
        public readonly ?string $personVerdictDistrict = null,
        public readonly ?string $dateVerdictDistrict = null,
        public readonly ?string $verdictDistrict = null,
        public readonly ?bool $isVerdictAreaRequired = null,
        public readonly ?int $idPersonVerdictArea = null,
        public readonly ?string $personVerdictArea = null,
        public readonly ?string $dateVerdictArea = null,
        public readonly ?string $verdictArea = null,
        public readonly ?bool $isVerdictHealthRequired = null,
        public readonly ?int $idDocumentVerdictHealth = null,
        public readonly ?string $personVerdictHealth = null,
        public readonly ?string $dateVerdictHealth = null,
        public readonly ?bool $agreement = null,
        public readonly ?bool $showNoticeFromPreviousExam = null,
        public readonly ?string $previousExamDisplayName = null,
        public readonly ?string $previousExamDate = null,
    ) {}

    public static function fromStdClass(\stdClass $obj): self
    {
        return new self(
            idLogin: isset($obj->{'ID_Login'}) ? (string) $obj->{'ID_Login'} : null,
            id: isset($obj->{'ID'}) ? (int) $obj->{'ID'} : null,
            isActive: isset($obj->{'IsActive'}) ? (bool) $obj->{'IsActive'} : null,
            idEventEducation: isset($obj->{'ID_EventEducation'}) ? (int) $obj->{'ID_EventEducation'} : null,
            registrationDeadline: isset($obj->{'RegistrationDeadline'}) ? (string) $obj->{'RegistrationDeadline'} : null,
            eventEducation: isset($obj->{'EventEducation'}) ? (string) $obj->{'EventEducation'} : null,
            eventEducationCourse: isset($obj->{'EventEducationCourse'}) ? (string) $obj->{'EventEducationCourse'} : null,
            idEventEducationType: isset($obj->{'ID_EventEducationType'}) ? (int) $obj->{'ID_EventEducationType'} : null,
            eventEducationType: isset($obj->{'EventEducationType'}) ? (string) $obj->{'EventEducationType'} : null,
            idUnit: isset($obj->{'ID_Unit'}) ? (int) $obj->{'ID_Unit'} : null,
            unit: isset($obj->{'Unit'}) ? (string) $obj->{'Unit'} : null,
            unitNameWithRegistrationNumber: isset($obj->{'UnitNameWithRegistrationNumber'}) ? (string) $obj->{'UnitNameWithRegistrationNumber'} : null,
            registrationNumber: isset($obj->{'RegistrationNumber'}) ? (string) $obj->{'RegistrationNumber'} : null,
            unitFullName: isset($obj->{'UnitFullName'}) ? (string) $obj->{'UnitFullName'} : null,
            personDisplayName: isset($obj->{'PersonDisplayName'}) ? (string) $obj->{'PersonDisplayName'} : null,
            personEmail: isset($obj->{'PersonEmail'}) ? (string) $obj->{'PersonEmail'} : null,
            personPhone: isset($obj->{'PersonPhone'}) ? (string) $obj->{'PersonPhone'} : null,
            address: isset($obj->{'Address'}) ? (string) $obj->{'Address'} : null,
            identificationCode: isset($obj->{'IdentificationCode'}) ? (string) $obj->{'IdentificationCode'} : null,
            firstName: isset($obj->{'FirstName'}) ? (string) $obj->{'FirstName'} : null,
            lastName: isset($obj->{'LastName'}) ? (string) $obj->{'LastName'} : null,
            nickName: isset($obj->{'NickName'}) ? (string) $obj->{'NickName'} : null,
            street: isset($obj->{'Street'}) ? (string) $obj->{'Street'} : null,
            city: isset($obj->{'City'}) ? (string) $obj->{'City'} : null,
            postcode: isset($obj->{'Postcode'}) ? (string) $obj->{'Postcode'} : null,
            idUnitMembership: isset($obj->{'ID_UnitMembership'}) ? (int) $obj->{'ID_UnitMembership'} : null,
            unitMembership: isset($obj->{'UnitMembership'}) ? (string) $obj->{'UnitMembership'} : null,
            unitMembershipWithRegistrationNumber: isset($obj->{'UnitMembershipWithRegistrationNumber'}) ? (string) $obj->{'UnitMembershipWithRegistrationNumber'} : null,
            registrationNumberMembership: isset($obj->{'RegistrationNumberMembership'}) ? (string) $obj->{'RegistrationNumberMembership'} : null,
            unitFullNameMembership: isset($obj->{'UnitFullNameMembership'}) ? (string) $obj->{'UnitFullNameMembership'} : null,
            isMember: isset($obj->{'IsMember'}) ? (bool) $obj->{'IsMember'} : null,
            idPerson: isset($obj->{'ID_Person'}) ? (int) $obj->{'ID_Person'} : null,
            person: isset($obj->{'Person'}) ? (string) $obj->{'Person'} : null,
            loginFrom: isset($obj->{'LoginFrom'}) ? (string) $obj->{'LoginFrom'} : null,
            loginTo: isset($obj->{'LoginTo'}) ? (string) $obj->{'LoginTo'} : null,
            loginActive: isset($obj->{'LoginActive'}) ? (bool) $obj->{'LoginActive'} : null,
            loginPassed: isset($obj->{'LoginPassed'}) ? (bool) $obj->{'LoginPassed'} : null,
            loginInFuture: isset($obj->{'LoginInFuture'}) ? (bool) $obj->{'LoginInFuture'} : null,
            idParticipantEducation: isset($obj->{'ID_ParticipantEducation'}) ? (int) $obj->{'ID_ParticipantEducation'} : null,
            isVerdictGroupRequired: isset($obj->{'IsVerdictGroupRequired'}) ? (bool) $obj->{'IsVerdictGroupRequired'} : null,
            idPersonVerdictGroup: isset($obj->{'ID_PersonVerdictGroup'}) ? (int) $obj->{'ID_PersonVerdictGroup'} : null,
            personVerdictGroup: isset($obj->{'PersonVerdictGroup'}) ? (string) $obj->{'PersonVerdictGroup'} : null,
            dateVerdictGroup: isset($obj->{'DateVerdictGroup'}) ? (string) $obj->{'DateVerdictGroup'} : null,
            verdictGroup: isset($obj->{'VerdictGroup'}) ? (string) $obj->{'VerdictGroup'} : null,
            isVerdictDistrictRequired: isset($obj->{'IsVerdictDistrictRequired'}) ? (bool) $obj->{'IsVerdictDistrictRequired'} : null,
            idPersonVerdictDistrict: isset($obj->{'ID_PersonVerdictDistrict'}) ? (int) $obj->{'ID_PersonVerdictDistrict'} : null,
            personVerdictDistrict: isset($obj->{'PersonVerdictDistrict'}) ? (string) $obj->{'PersonVerdictDistrict'} : null,
            dateVerdictDistrict: isset($obj->{'DateVerdictDistrict'}) ? (string) $obj->{'DateVerdictDistrict'} : null,
            verdictDistrict: isset($obj->{'VerdictDistrict'}) ? (string) $obj->{'VerdictDistrict'} : null,
            isVerdictAreaRequired: isset($obj->{'IsVerdictAreaRequired'}) ? (bool) $obj->{'IsVerdictAreaRequired'} : null,
            idPersonVerdictArea: isset($obj->{'ID_PersonVerdictArea'}) ? (int) $obj->{'ID_PersonVerdictArea'} : null,
            personVerdictArea: isset($obj->{'PersonVerdictArea'}) ? (string) $obj->{'PersonVerdictArea'} : null,
            dateVerdictArea: isset($obj->{'DateVerdictArea'}) ? (string) $obj->{'DateVerdictArea'} : null,
            verdictArea: isset($obj->{'VerdictArea'}) ? (string) $obj->{'VerdictArea'} : null,
            isVerdictHealthRequired: isset($obj->{'IsVerdictHealthRequired'}) ? (bool) $obj->{'IsVerdictHealthRequired'} : null,
            idDocumentVerdictHealth: isset($obj->{'ID_DocumentVerdictHealth'}) ? (int) $obj->{'ID_DocumentVerdictHealth'} : null,
            personVerdictHealth: isset($obj->{'PersonVerdictHealth'}) ? (string) $obj->{'PersonVerdictHealth'} : null,
            dateVerdictHealth: isset($obj->{'DateVerdictHealth'}) ? (string) $obj->{'DateVerdictHealth'} : null,
            agreement: isset($obj->{'Agreement'}) ? (bool) $obj->{'Agreement'} : null,
            showNoticeFromPreviousExam: isset($obj->{'ShowNoticeFromPreviousExam'}) ? (bool) $obj->{'ShowNoticeFromPreviousExam'} : null,
            previousExamDisplayName: isset($obj->{'PreviousExamDisplayName'}) ? (string) $obj->{'PreviousExamDisplayName'} : null,
            previousExamDate: isset($obj->{'PreviousExamDate'}) ? (string) $obj->{'PreviousExamDate'} : null,
        );
    }
}
