<?php

namespace Misakstvanu\LaravelSkautis\Responses\Events;

final class ParticipantEducationAllOutput
{
    public function __construct(
        public readonly ?int $id = null,
        public readonly ?int $idParticipant = null,
        public readonly ?int $idEventEducationCourse = null,
        public readonly ?int $idEventEducationCourseType = null,
        public readonly ?string $eventEducationCourseType = null,
        public readonly ?bool $isActive = null,
        public readonly ?bool $fillCondition = null,
        public readonly ?bool $isSubstitute = null,
        public readonly ?bool $isAccepted = null,
        public readonly ?string $graduated = null,
        public readonly ?string $signIn = null,
        public readonly ?string $signOut = null,
        public readonly ?string $signOutNote = null,
        public readonly ?string $note = null,
        public readonly ?int $idPerson = null,
        public readonly ?string $person = null,
        public readonly ?int $personAge = null,
        public readonly ?string $personBirthday = null,
        public readonly ?string $personAddress = null,
        public readonly ?string $personAddressStreet = null,
        public readonly ?string $personAddressCity = null,
        public readonly ?string $personAddressPostcode = null,
        public readonly ?string $personAddressState = null,
        public readonly ?string $personEmail = null,
        public readonly ?string $personPhone = null,
        public readonly ?int $idPersonUnit = null,
        public readonly ?string $personUnitRegistrationNumber = null,
        public readonly ?int $idPersonStredisko = null,
        public readonly ?string $personStrediskoRegistrationNumber = null,
        public readonly ?string $unfilledRequirements = null,
        public readonly ?string $unfilledObligatoryRequirements = null,
        public readonly ?bool $requirementsEditable = null,
        public readonly ?int $idEventEducationLetterRequest = null,
        public readonly ?string $eventEducationLetterRequestDate = null,
        public readonly ?string $idEventEducationLetterRequestState = null,
        public readonly ?string $eventEducationLetterRequestState = null,
        public readonly ?string $eventEducationLetterNumber = null,
        public readonly ?bool $canGenerate = null,
        public readonly ?string $dateGenerated = null,
        public readonly ?bool $isPreviousExam = null,
    ) {}

    public static function fromStdClass(\stdClass $obj): self
    {
        return new self(
            id: isset($obj->{'ID'}) ? (int) $obj->{'ID'} : null,
            idParticipant: isset($obj->{'ID_Participant'}) ? (int) $obj->{'ID_Participant'} : null,
            idEventEducationCourse: isset($obj->{'ID_EventEducationCourse'}) ? (int) $obj->{'ID_EventEducationCourse'} : null,
            idEventEducationCourseType: isset($obj->{'ID_EventEducationCourseType'}) ? (int) $obj->{'ID_EventEducationCourseType'} : null,
            eventEducationCourseType: isset($obj->{'EventEducationCourseType'}) ? (string) $obj->{'EventEducationCourseType'} : null,
            isActive: isset($obj->{'IsActive'}) ? (bool) $obj->{'IsActive'} : null,
            fillCondition: isset($obj->{'FillCondition'}) ? (bool) $obj->{'FillCondition'} : null,
            isSubstitute: isset($obj->{'IsSubstitute'}) ? (bool) $obj->{'IsSubstitute'} : null,
            isAccepted: isset($obj->{'IsAccepted'}) ? (bool) $obj->{'IsAccepted'} : null,
            graduated: isset($obj->{'Graduated'}) ? (string) $obj->{'Graduated'} : null,
            signIn: isset($obj->{'SignIn'}) ? (string) $obj->{'SignIn'} : null,
            signOut: isset($obj->{'SignOut'}) ? (string) $obj->{'SignOut'} : null,
            signOutNote: isset($obj->{'SignOutNote'}) ? (string) $obj->{'SignOutNote'} : null,
            note: isset($obj->{'Note'}) ? (string) $obj->{'Note'} : null,
            idPerson: isset($obj->{'ID_Person'}) ? (int) $obj->{'ID_Person'} : null,
            person: isset($obj->{'Person'}) ? (string) $obj->{'Person'} : null,
            personAge: isset($obj->{'PersonAge'}) ? (int) $obj->{'PersonAge'} : null,
            personBirthday: isset($obj->{'PersonBirthday'}) ? (string) $obj->{'PersonBirthday'} : null,
            personAddress: isset($obj->{'PersonAddress'}) ? (string) $obj->{'PersonAddress'} : null,
            personAddressStreet: isset($obj->{'PersonAddressStreet'}) ? (string) $obj->{'PersonAddressStreet'} : null,
            personAddressCity: isset($obj->{'PersonAddressCity'}) ? (string) $obj->{'PersonAddressCity'} : null,
            personAddressPostcode: isset($obj->{'PersonAddressPostcode'}) ? (string) $obj->{'PersonAddressPostcode'} : null,
            personAddressState: isset($obj->{'PersonAddressState'}) ? (string) $obj->{'PersonAddressState'} : null,
            personEmail: isset($obj->{'PersonEmail'}) ? (string) $obj->{'PersonEmail'} : null,
            personPhone: isset($obj->{'PersonPhone'}) ? (string) $obj->{'PersonPhone'} : null,
            idPersonUnit: isset($obj->{'ID_PersonUnit'}) ? (int) $obj->{'ID_PersonUnit'} : null,
            personUnitRegistrationNumber: isset($obj->{'PersonUnitRegistrationNumber'}) ? (string) $obj->{'PersonUnitRegistrationNumber'} : null,
            idPersonStredisko: isset($obj->{'ID_PersonStredisko'}) ? (int) $obj->{'ID_PersonStredisko'} : null,
            personStrediskoRegistrationNumber: isset($obj->{'PersonStrediskoRegistrationNumber'}) ? (string) $obj->{'PersonStrediskoRegistrationNumber'} : null,
            unfilledRequirements: isset($obj->{'UnfilledRequirements'}) ? (string) $obj->{'UnfilledRequirements'} : null,
            unfilledObligatoryRequirements: isset($obj->{'UnfilledObligatoryRequirements'}) ? (string) $obj->{'UnfilledObligatoryRequirements'} : null,
            requirementsEditable: isset($obj->{'RequirementsEditable'}) ? (bool) $obj->{'RequirementsEditable'} : null,
            idEventEducationLetterRequest: isset($obj->{'ID_EventEducationLetterRequest'}) ? (int) $obj->{'ID_EventEducationLetterRequest'} : null,
            eventEducationLetterRequestDate: isset($obj->{'EventEducationLetterRequestDate'}) ? (string) $obj->{'EventEducationLetterRequestDate'} : null,
            idEventEducationLetterRequestState: isset($obj->{'ID_EventEducationLetterRequestState'}) ? (string) $obj->{'ID_EventEducationLetterRequestState'} : null,
            eventEducationLetterRequestState: isset($obj->{'EventEducationLetterRequestState'}) ? (string) $obj->{'EventEducationLetterRequestState'} : null,
            eventEducationLetterNumber: isset($obj->{'EventEducationLetterNumber'}) ? (string) $obj->{'EventEducationLetterNumber'} : null,
            canGenerate: isset($obj->{'CanGenerate'}) ? (bool) $obj->{'CanGenerate'} : null,
            dateGenerated: isset($obj->{'DateGenerated'}) ? (string) $obj->{'DateGenerated'} : null,
            isPreviousExam: isset($obj->{'IsPreviousExam'}) ? (bool) $obj->{'IsPreviousExam'} : null,
        );
    }
}
