<?php

namespace Misakstvanu\LaravelSkautis\Requests\Material;

final class WarehouseItemInsertInput
{
    public function __construct(
        public readonly ?int $id = null,
        public readonly ?int $idUnit = null,
        public readonly ?int $idEvent = null,
        public readonly ?string $eventName = null,
        public readonly ?string $displayName = null,
        public readonly ?int $idWarehouse = null,
        public readonly ?string $warehouse = null,
        public readonly ?string $idWarehouseItemCategory = null,
        public readonly ?string $warehouseItemCategory = null,
        public readonly ?string $inventoryNumber = null,
        public readonly ?string $description = null,
        public readonly ?string $idTempFile = null,
        public readonly ?int $idDocument = null,
        public readonly ?string $fileExtension = null,
        public readonly ?string $purchaseDate = null,
        public readonly ?int $purchaseYear = null,
        public readonly ?string $idPurchaseType = null,
        public readonly ?string $purchaseType = null,
        public readonly ?string $purchaseNote = null,
        public readonly ?string $serialNumber = null,
        public readonly ?string $sails = null,
        public readonly ?string $accountNumber = null,
        public readonly ?float $purchasePrice = null,
        public readonly ?float $actualPrice = null,
        public readonly ?string $deletionDate = null,
        public readonly ?string $deletionNote = null,
        public readonly ?bool $eventRent = null,
        public readonly ?bool $unitRent = null,
        public readonly ?bool $commercialRent = null,
        public readonly ?float $rentPrice = null,
        public readonly ?string $rentNote = null,
        public readonly ?string $note = null,
        public readonly ?string $tags = null,
        public readonly ?bool $inWarehouse = null,
        public readonly ?string $warehouseRentNote = null,
        public readonly ?string $warehouseTag = null,
        public readonly ?string $inventoryDate = null,
        public readonly ?string $inventoryNote = null,
    ) {}

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(
            [
            'ID' => $this->id,
            'ID_Unit' => $this->idUnit,
            'ID_Event' => $this->idEvent,
            'EventName' => $this->eventName,
            'DisplayName' => $this->displayName,
            'ID_Warehouse' => $this->idWarehouse,
            'Warehouse' => $this->warehouse,
            'ID_WarehouseItemCategory' => $this->idWarehouseItemCategory,
            'WarehouseItemCategory' => $this->warehouseItemCategory,
            'InventoryNumber' => $this->inventoryNumber,
            'Description' => $this->description,
            'ID_TempFile' => $this->idTempFile,
            'ID_Document' => $this->idDocument,
            'FileExtension' => $this->fileExtension,
            'PurchaseDate' => $this->purchaseDate,
            'PurchaseYear' => $this->purchaseYear,
            'ID_PurchaseType' => $this->idPurchaseType,
            'PurchaseType' => $this->purchaseType,
            'PurchaseNote' => $this->purchaseNote,
            'SerialNumber' => $this->serialNumber,
            'Sails' => $this->sails,
            'AccountNumber' => $this->accountNumber,
            'PurchasePrice' => $this->purchasePrice,
            'ActualPrice' => $this->actualPrice,
            'DeletionDate' => $this->deletionDate,
            'DeletionNote' => $this->deletionNote,
            'EventRent' => $this->eventRent,
            'UnitRent' => $this->unitRent,
            'CommercialRent' => $this->commercialRent,
            'RentPrice' => $this->rentPrice,
            'RentNote' => $this->rentNote,
            'Note' => $this->note,
            'Tags' => $this->tags,
            'InWarehouse' => $this->inWarehouse,
            'WarehouseRentNote' => $this->warehouseRentNote,
            'WarehouseTag' => $this->warehouseTag,
            'InventoryDate' => $this->inventoryDate,
            'InventoryNote' => $this->inventoryNote,
            ],
            fn (mixed $v): bool => $v !== null,
        );
    }
}
