<?php

namespace Misakstvanu\LaravelSkautis\Requests\OrganizationUnit;

final class MembershipApplicationUpdateDenyInput
{
    public function __construct(
        public readonly ?int $id = null,
        public readonly ?int $idUnit = null,
        public readonly ?string $unit = null,
        public readonly ?string $unitTitle = null,
        public readonly ?string $logoExtension = null,
        public readonly ?string $registrationNumber = null,
        public readonly ?int $idPerson = null,
        public readonly ?string $idMembershipApplicationState = null,
        public readonly ?string $membershipApplicationState = null,
        public readonly ?string $validTo = null,
        public readonly ?string $accessKey = null,
        public readonly ?bool $isValid = null,
        public readonly ?string $dateCreate = null,
        public readonly ?string $lastOpened = null,
        public readonly ?string $firstName = null,
        public readonly ?string $lastName = null,
        public readonly ?string $firstNameParent = null,
        public readonly ?string $lastNameParent = null,
        public readonly ?string $noteParent = null,
        public readonly ?string $parentNote = null,
        public readonly ?string $parentType = null,
        public readonly ?string $parentTypeCustom = null,
        public readonly ?string $firstNameParent2 = null,
        public readonly ?string $lastNameParent2 = null,
        public readonly ?string $noteParent2 = null,
        public readonly ?string $parent2Note = null,
        public readonly ?string $parentType2 = null,
        public readonly ?string $parentTypeCustom2 = null,
        public readonly ?bool $isAdult = null,
        public readonly ?string $dateFilled = null,
        public readonly ?string $dateFinished = null,
        public readonly ?string $person = null,
        public readonly ?string $birthday = null,
        public readonly ?string $identificationCode = null,
        public readonly ?string $phoneMainHelp = null,
        public readonly ?string $phoneMainPlaceholder = null,
        public readonly ?string $emailMainHelp = null,
        public readonly ?string $emailMainPlaceholder = null,
        public readonly ?string $dateState = null,
        public readonly ?string $reason = null,
        public readonly ?string $idSex = null,
        public readonly ?string $sex = null,
        public readonly ?bool $isForeign = null,
        public readonly ?string $maidenName = null,
        public readonly ?string $idCitizenship = null,
        public readonly ?string $citizenship = null,
        public readonly ?string $citizenshipCustom = null,
        public readonly ?int $idDistrictBirth = null,
        public readonly ?string $birthCity = null,
        public readonly ?string $districtBirth = null,
        public readonly ?string $degrees = null,
        public readonly ?string $idDegreeType1 = null,
        public readonly ?string $idDegreeType2 = null,
        public readonly ?string $idDegreeType3 = null,
        public readonly ?string $street = null,
        public readonly ?string $city = null,
        public readonly ?string $postalFirstLine = null,
        public readonly ?string $state = null,
        public readonly ?string $postcode = null,
        public readonly ?string $postalStreet = null,
        public readonly ?string $postalState = null,
        public readonly ?string $postalPostcode = null,
        public readonly ?string $postalCity = null,
        public readonly ?string $phoneParent = null,
        public readonly ?string $emailParent = null,
        public readonly ?string $phoneParent2 = null,
        public readonly ?string $emailParent2 = null,
        public readonly ?string $phone = null,
        public readonly ?string $email = null,
        public readonly ?string $insuranceNumber = null,
        public readonly ?string $allergy = null,
        public readonly ?string $foodRestrictions = null,
        public readonly ?string $drugs = null,
        public readonly ?string $specialRequirements = null,
        public readonly ?string $healthLimitation = null,
        public readonly ?string $bodySkills = null,
        public readonly ?bool $allowDataStorage = null,
        public readonly ?bool $allowAudiovisual = null,
        public readonly ?bool $allowSocialNetwork = null,
        public readonly ?bool $allowMarketing = null,
        public readonly ?int $idAssurance = null,
        public readonly ?string $assurance = null,
    ) {}

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(
            [
            'ID' => $this->id,
            'ID_Unit' => $this->idUnit,
            'Unit' => $this->unit,
            'UnitTitle' => $this->unitTitle,
            'LogoExtension' => $this->logoExtension,
            'RegistrationNumber' => $this->registrationNumber,
            'ID_Person' => $this->idPerson,
            'ID_MembershipApplicationState' => $this->idMembershipApplicationState,
            'MembershipApplicationState' => $this->membershipApplicationState,
            'ValidTo' => $this->validTo,
            'AccessKey' => $this->accessKey,
            'IsValid' => $this->isValid,
            'DateCreate' => $this->dateCreate,
            'LastOpened' => $this->lastOpened,
            'FirstName' => $this->firstName,
            'LastName' => $this->lastName,
            'FirstNameParent' => $this->firstNameParent,
            'LastNameParent' => $this->lastNameParent,
            'NoteParent' => $this->noteParent,
            'ParentNote' => $this->parentNote,
            'ParentType' => $this->parentType,
            'ParentTypeCustom' => $this->parentTypeCustom,
            'FirstNameParent2' => $this->firstNameParent2,
            'LastNameParent2' => $this->lastNameParent2,
            'NoteParent2' => $this->noteParent2,
            'Parent2Note' => $this->parent2Note,
            'ParentType2' => $this->parentType2,
            'ParentTypeCustom2' => $this->parentTypeCustom2,
            'IsAdult' => $this->isAdult,
            'DateFilled' => $this->dateFilled,
            'DateFinished' => $this->dateFinished,
            'Person' => $this->person,
            'Birthday' => $this->birthday,
            'IdentificationCode' => $this->identificationCode,
            'PhoneMainHelp' => $this->phoneMainHelp,
            'PhoneMainPlaceholder' => $this->phoneMainPlaceholder,
            'EmailMainHelp' => $this->emailMainHelp,
            'EmailMainPlaceholder' => $this->emailMainPlaceholder,
            'DateState' => $this->dateState,
            'Reason' => $this->reason,
            'ID_Sex' => $this->idSex,
            'Sex' => $this->sex,
            'IsForeign' => $this->isForeign,
            'MaidenName' => $this->maidenName,
            'ID_Citizenship' => $this->idCitizenship,
            'Citizenship' => $this->citizenship,
            'CitizenshipCustom' => $this->citizenshipCustom,
            'ID_DistrictBirth' => $this->idDistrictBirth,
            'BirthCity' => $this->birthCity,
            'DistrictBirth' => $this->districtBirth,
            'Degrees' => $this->degrees,
            'ID_DegreeType1' => $this->idDegreeType1,
            'ID_DegreeType2' => $this->idDegreeType2,
            'ID_DegreeType3' => $this->idDegreeType3,
            'Street' => $this->street,
            'City' => $this->city,
            'PostalFirstLine' => $this->postalFirstLine,
            'State' => $this->state,
            'Postcode' => $this->postcode,
            'PostalStreet' => $this->postalStreet,
            'PostalState' => $this->postalState,
            'PostalPostcode' => $this->postalPostcode,
            'PostalCity' => $this->postalCity,
            'PhoneParent' => $this->phoneParent,
            'EmailParent' => $this->emailParent,
            'PhoneParent2' => $this->phoneParent2,
            'EmailParent2' => $this->emailParent2,
            'Phone' => $this->phone,
            'Email' => $this->email,
            'InsuranceNumber' => $this->insuranceNumber,
            'Allergy' => $this->allergy,
            'FoodRestrictions' => $this->foodRestrictions,
            'Drugs' => $this->drugs,
            'SpecialRequirements' => $this->specialRequirements,
            'HealthLimitation' => $this->healthLimitation,
            'BodySkills' => $this->bodySkills,
            'AllowDataStorage' => $this->allowDataStorage,
            'AllowAudiovisual' => $this->allowAudiovisual,
            'AllowSocialNetwork' => $this->allowSocialNetwork,
            'AllowMarketing' => $this->allowMarketing,
            'ID_Assurance' => $this->idAssurance,
            'Assurance' => $this->assurance,
            ],
            fn (mixed $v): bool => $v !== null,
        );
    }
}
