<?php

namespace Misakstvanu\LaravelSkautis\Requests\OrganizationUnit;

final class MemberCardInvoiceUpdateInput
{
    public function __construct(
        public readonly ?int $id = null,
        public readonly ?int $idUnit = null,
        public readonly ?string $unit = null,
        public readonly ?string $registrationNumber = null,
        public readonly ?string $street = null,
        public readonly ?string $city = null,
        public readonly ?string $postcode = null,
        public readonly ?string $state = null,
        public readonly ?string $stateCode = null,
        public readonly ?string $iC = null,
        public readonly ?string $dIC = null,
        public readonly ?string $displayName = null,
        public readonly ?int $sequence = null,
        public readonly ?string $maturity = null,
        public readonly ?string $dateGenerating = null,
        public readonly ?float $totalPrice = null,
        public readonly ?float $totalPriceWithVat = null,
        public readonly ?float $price = null,
        public readonly ?float $priceBase = null,
        public readonly ?float $priceFirst = null,
        public readonly ?float $priceSecond = null,
        public readonly ?float $vatBase = null,
        public readonly ?float $vatFirst = null,
        public readonly ?float $vatSecond = null,
        public readonly ?int $idMemberCardInvoiceGenerate = null,
        public readonly ?string $idMemberCardInvoiceState = null,
        public readonly ?string $memberCardInvoiceState = null,
        public readonly ?int $idInvoiceGroup = null,
        public readonly ?string $invoiceGroupContractorIC = null,
        public readonly ?string $invoiceGroupContractorDIC = null,
        public readonly ?string $invoiceGroupContractorPhone = null,
        public readonly ?string $invoiceGroupContractorEmail = null,
        public readonly ?string $invoiceGroupWeb = null,
        public readonly ?string $invoiceGroupFileReference = null,
        public readonly ?string $invoiceGroupBankAccount = null,
        public readonly ?string $invoiceGroupBankCode = null,
        public readonly ?string $invoiceGroupBank = null,
        public readonly ?string $paymentType = null,
        public readonly ?string $dateTaxableSupply = null,
        public readonly ?string $qRCodeString = null,
        public readonly ?string $invoiceGroupContractor = null,
        public readonly ?string $invoiceGroupContractorAddress = null,
        public readonly ?string $invoiceBankAccount = null,
    ) {}

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(
            [
            'ID' => $this->id,
            'ID_Unit' => $this->idUnit,
            'Unit' => $this->unit,
            'RegistrationNumber' => $this->registrationNumber,
            'Street' => $this->street,
            'City' => $this->city,
            'Postcode' => $this->postcode,
            'State' => $this->state,
            'StateCode' => $this->stateCode,
            'IC' => $this->iC,
            'DIC' => $this->dIC,
            'DisplayName' => $this->displayName,
            'Sequence' => $this->sequence,
            'Maturity' => $this->maturity,
            'DateGenerating' => $this->dateGenerating,
            'TotalPrice' => $this->totalPrice,
            'TotalPriceWithVat' => $this->totalPriceWithVat,
            'Price' => $this->price,
            'PriceBase' => $this->priceBase,
            'PriceFirst' => $this->priceFirst,
            'PriceSecond' => $this->priceSecond,
            'VatBase' => $this->vatBase,
            'VatFirst' => $this->vatFirst,
            'VatSecond' => $this->vatSecond,
            'ID_MemberCardInvoiceGenerate' => $this->idMemberCardInvoiceGenerate,
            'ID_MemberCardInvoiceState' => $this->idMemberCardInvoiceState,
            'MemberCardInvoiceState' => $this->memberCardInvoiceState,
            'ID_InvoiceGroup' => $this->idInvoiceGroup,
            'InvoiceGroupContractorIC' => $this->invoiceGroupContractorIC,
            'InvoiceGroupContractorDIC' => $this->invoiceGroupContractorDIC,
            'InvoiceGroupContractorPhone' => $this->invoiceGroupContractorPhone,
            'InvoiceGroupContractorEmail' => $this->invoiceGroupContractorEmail,
            'InvoiceGroupWeb' => $this->invoiceGroupWeb,
            'InvoiceGroupFileReference' => $this->invoiceGroupFileReference,
            'InvoiceGroupBankAccount' => $this->invoiceGroupBankAccount,
            'InvoiceGroupBankCode' => $this->invoiceGroupBankCode,
            'InvoiceGroupBank' => $this->invoiceGroupBank,
            'PaymentType' => $this->paymentType,
            'DateTaxableSupply' => $this->dateTaxableSupply,
            'QRCodeString' => $this->qRCodeString,
            'InvoiceGroupContractor' => $this->invoiceGroupContractor,
            'InvoiceGroupContractorAddress' => $this->invoiceGroupContractorAddress,
            'InvoiceBankAccount' => $this->invoiceBankAccount,
            ],
            fn (mixed $v): bool => $v !== null,
        );
    }
}
