<?php

namespace Misakstvanu\LaravelSkautis\Requests\OrganizationUnit;

final class PersonOtherUpdateInput
{
    public function __construct(
        public readonly ?int $id = null,
        public readonly ?int $idPerson = null,
        public readonly ?string $birthCity = null,
        public readonly ?string $idCitizenship = null,
        public readonly ?string $citizenship = null,
        public readonly ?string $citizenshipCustom = null,
        public readonly ?string $person = null,
        public readonly ?string $maidenName = null,
        public readonly ?int $idDistrictBirth = null,
        public readonly ?string $districtBirth = null,
        public readonly ?int $idAssurance = null,
        public readonly ?string $assurance = null,
        public readonly ?string $insuranceNumber = null,
        public readonly ?string $allergy = null,
        public readonly ?string $foodRestrictions = null,
        public readonly ?string $drugs = null,
        public readonly ?string $specialRequirements = null,
        public readonly ?string $healthLimitation = null,
        public readonly ?string $bodySkills = null,
        public readonly ?string $school = null,
        public readonly ?string $note = null,
        public readonly ?string $parentNote = null,
        public readonly ?bool $allowDataStorage = null,
        public readonly ?bool $allowAudiovisual = null,
        public readonly ?bool $allowSocialNetwork = null,
        public readonly ?bool $allowMarketing = null,
        public readonly ?string $dateChangeSocialNetwork = null,
        public readonly ?string $dateChangeMarketing = null,
        public readonly ?string $dateChangeDataStorage = null,
        public readonly ?string $dateChangeAudiovisual = null,
        public readonly ?bool $isRPS = null,
        public readonly ?bool $isEPS = null,
        public readonly ?bool $isEduParticipantExt = null,
        public readonly ?bool $onlyValidate = null,
        public readonly ?int $idEventCongress = null,
        public readonly ?string $idTempFileHealth = null,
        public readonly ?int $idDocumentHealth = null,
        public readonly ?string $idCardNumber = null,
        public readonly ?string $idCardValidTo = null,
        public readonly ?bool $isAdult = null,
        public readonly ?bool $isNonMemberWithGoogleServicesAccess = null,
        public readonly ?string $promiseChild = null,
        public readonly ?string $promiseScout = null,
        public readonly ?string $promiseOfficial = null,
        public readonly ?string $trailProgress = null,
    ) {}

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(
            [
            'ID' => $this->id,
            'ID_Person' => $this->idPerson,
            'BirthCity' => $this->birthCity,
            'ID_Citizenship' => $this->idCitizenship,
            'Citizenship' => $this->citizenship,
            'CitizenshipCustom' => $this->citizenshipCustom,
            'Person' => $this->person,
            'MaidenName' => $this->maidenName,
            'ID_DistrictBirth' => $this->idDistrictBirth,
            'DistrictBirth' => $this->districtBirth,
            'ID_Assurance' => $this->idAssurance,
            'Assurance' => $this->assurance,
            'InsuranceNumber' => $this->insuranceNumber,
            'Allergy' => $this->allergy,
            'FoodRestrictions' => $this->foodRestrictions,
            'Drugs' => $this->drugs,
            'SpecialRequirements' => $this->specialRequirements,
            'HealthLimitation' => $this->healthLimitation,
            'BodySkills' => $this->bodySkills,
            'School' => $this->school,
            'Note' => $this->note,
            'ParentNote' => $this->parentNote,
            'AllowDataStorage' => $this->allowDataStorage,
            'AllowAudiovisual' => $this->allowAudiovisual,
            'AllowSocialNetwork' => $this->allowSocialNetwork,
            'AllowMarketing' => $this->allowMarketing,
            'DateChangeSocialNetwork' => $this->dateChangeSocialNetwork,
            'DateChangeMarketing' => $this->dateChangeMarketing,
            'DateChangeDataStorage' => $this->dateChangeDataStorage,
            'DateChangeAudiovisual' => $this->dateChangeAudiovisual,
            'IsRPS' => $this->isRPS,
            'IsEPS' => $this->isEPS,
            'IsEduParticipantExt' => $this->isEduParticipantExt,
            'OnlyValidate' => $this->onlyValidate,
            'ID_EventCongress' => $this->idEventCongress,
            'ID_TempFileHealth' => $this->idTempFileHealth,
            'ID_DocumentHealth' => $this->idDocumentHealth,
            'IdCardNumber' => $this->idCardNumber,
            'IdCardValidTo' => $this->idCardValidTo,
            'IsAdult' => $this->isAdult,
            'IsNonMemberWithGoogleServicesAccess' => $this->isNonMemberWithGoogleServicesAccess,
            'PromiseChild' => $this->promiseChild,
            'PromiseScout' => $this->promiseScout,
            'PromiseOfficial' => $this->promiseOfficial,
            'TrailProgress' => $this->trailProgress,
            ],
            fn (mixed $v): bool => $v !== null,
        );
    }
}
