<?php

namespace Misakstvanu\LaravelSkautis\Requests\OrganizationUnit;

final class PersonInsertInput
{
    public function __construct(
        public readonly ?string $identificationCode = null,
        public readonly ?string $firstName = null,
        public readonly ?string $lastName = null,
        public readonly ?string $nickName = null,
        public readonly ?string $address = null,
        public readonly ?string $street = null,
        public readonly ?string $city = null,
        public readonly ?string $postcode = null,
        public readonly ?string $state = null,
        public readonly ?string $postalFirstLine = null,
        public readonly ?string $postalAddress = null,
        public readonly ?string $postalStreet = null,
        public readonly ?string $postalCity = null,
        public readonly ?string $postalPostcode = null,
        public readonly ?string $postalState = null,
        public readonly ?string $note = null,
        public readonly ?string $idSex = null,
        public readonly ?string $birthday = null,
        public readonly ?int $birthdayYear = null,
        public readonly ?bool $isForeign = null,
        public readonly ?int $yearFrom = null,
        public readonly ?string $registrationNumber = null,
        public readonly ?int $idUser = null,
        public readonly ?bool $onlyValidate = null,
        public readonly ?string $photoExtension = null,
        public readonly ?string $maidenName = null,
        public readonly ?bool $isPostalAuthenticated = null,
        public readonly ?bool $isAddressAuthenticated = null,
        public readonly ?string $addressDistrict = null,
        public readonly ?string $postalDistrict = null,
        public readonly ?string $unitEnrollExtension = null,
        public readonly ?string $unitEnroll = null,
        public readonly ?bool $allowDataStorage = null,
        public readonly ?bool $allowAudiovisual = null,
        public readonly ?bool $allowSocialNetwork = null,
        public readonly ?bool $allowMarketing = null,
        public readonly ?bool $identificationCodeForce = null,
        public readonly ?string $idUnitEnrollTempFile = null,
    ) {}

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(
            [
            'IdentificationCode' => $this->identificationCode,
            'FirstName' => $this->firstName,
            'LastName' => $this->lastName,
            'NickName' => $this->nickName,
            'Address' => $this->address,
            'Street' => $this->street,
            'City' => $this->city,
            'Postcode' => $this->postcode,
            'State' => $this->state,
            'PostalFirstLine' => $this->postalFirstLine,
            'PostalAddress' => $this->postalAddress,
            'PostalStreet' => $this->postalStreet,
            'PostalCity' => $this->postalCity,
            'PostalPostcode' => $this->postalPostcode,
            'PostalState' => $this->postalState,
            'Note' => $this->note,
            'ID_Sex' => $this->idSex,
            'Birthday' => $this->birthday,
            'BirthdayYear' => $this->birthdayYear,
            'IsForeign' => $this->isForeign,
            'YearFrom' => $this->yearFrom,
            'RegistrationNumber' => $this->registrationNumber,
            'ID_User' => $this->idUser,
            'OnlyValidate' => $this->onlyValidate,
            'PhotoExtension' => $this->photoExtension,
            'MaidenName' => $this->maidenName,
            'IsPostalAuthenticated' => $this->isPostalAuthenticated,
            'IsAddressAuthenticated' => $this->isAddressAuthenticated,
            'AddressDistrict' => $this->addressDistrict,
            'PostalDistrict' => $this->postalDistrict,
            'UnitEnrollExtension' => $this->unitEnrollExtension,
            'UnitEnroll' => $this->unitEnroll,
            'AllowDataStorage' => $this->allowDataStorage,
            'AllowAudiovisual' => $this->allowAudiovisual,
            'AllowSocialNetwork' => $this->allowSocialNetwork,
            'AllowMarketing' => $this->allowMarketing,
            'IdentificationCodeForce' => $this->identificationCodeForce,
            'ID_UnitEnrollTempFile' => $this->idUnitEnrollTempFile,
            ],
            fn (mixed $v): bool => $v !== null,
        );
    }
}
