<?php

namespace Misakstvanu\LaravelSkautis\Requests\OrganizationUnit;

final class PersonChangeUpdateInput
{
    public function __construct(
        public readonly ?string $idApplication = null,
        public readonly ?string $accessKey = null,
        public readonly ?bool $onlyValidate = null,
        public readonly ?string $firstName = null,
        public readonly ?string $lastName = null,
        public readonly ?string $idSex = null,
        public readonly ?string $birthday = null,
        public readonly ?string $identificationCode = null,
        public readonly ?bool $isForeign = null,
        public readonly ?string $address = null,
        public readonly ?string $street = null,
        public readonly ?string $city = null,
        public readonly ?string $postcode = null,
        public readonly ?string $state = null,
        public readonly ?string $postalFirstLine = null,
        public readonly ?string $postalAddress = null,
        public readonly ?string $postalStreet = null,
        public readonly ?string $postalCity = null,
        public readonly ?string $postalPostcode = null,
        public readonly ?string $postalState = null,
        public readonly ?string $phone = null,
        public readonly ?string $email = null,
        public readonly ?string $note = null,
        public readonly ?string $maidenName = null,
        public readonly ?string $idCitizenship = null,
        public readonly ?string $citizenshipCustom = null,
        public readonly ?int $idDistrictBirth = null,
        public readonly ?string $birthCity = null,
        public readonly ?int $idPersonParentPerson = null,
        public readonly ?int $idPersonParent = null,
        public readonly ?string $idParentType = null,
        public readonly ?string $parentType = null,
        public readonly ?string $parentTypeCustom = null,
        public readonly ?string $firstNameParent = null,
        public readonly ?string $lastNameParent = null,
        public readonly ?string $emailParent = null,
        public readonly ?string $phoneParent = null,
        public readonly ?string $noteParent = null,
        public readonly ?string $parentNote = null,
        public readonly ?bool $deleteParent = null,
        public readonly ?int $idPersonParentPerson2 = null,
        public readonly ?int $idPersonParent2 = null,
        public readonly ?string $idParentType2 = null,
        public readonly ?string $parentType2 = null,
        public readonly ?string $parentTypeCustom2 = null,
        public readonly ?string $firstNameParent2 = null,
        public readonly ?string $lastNameParent2 = null,
        public readonly ?string $emailParent2 = null,
        public readonly ?string $phoneParent2 = null,
        public readonly ?string $noteParent2 = null,
        public readonly ?string $parent2Note = null,
        public readonly ?bool $deleteParent2 = null,
        public readonly ?int $idAssurance = null,
        public readonly ?string $insuranceNumber = null,
        public readonly ?string $allergy = null,
        public readonly ?string $foodRestrictions = null,
        public readonly ?string $drugs = null,
        public readonly ?string $specialRequirements = null,
        public readonly ?string $healthLimitation = null,
        public readonly ?string $bodySkills = null,
        public readonly ?string $school = null,
        public readonly ?bool $checkCorrect = null,
        public readonly ?bool $isPostalSame = null,
    ) {}

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(
            [
            'ID_Application' => $this->idApplication,
            'AccessKey' => $this->accessKey,
            'OnlyValidate' => $this->onlyValidate,
            'FirstName' => $this->firstName,
            'LastName' => $this->lastName,
            'ID_Sex' => $this->idSex,
            'Birthday' => $this->birthday,
            'IdentificationCode' => $this->identificationCode,
            'IsForeign' => $this->isForeign,
            'Address' => $this->address,
            'Street' => $this->street,
            'City' => $this->city,
            'Postcode' => $this->postcode,
            'State' => $this->state,
            'PostalFirstLine' => $this->postalFirstLine,
            'PostalAddress' => $this->postalAddress,
            'PostalStreet' => $this->postalStreet,
            'PostalCity' => $this->postalCity,
            'PostalPostcode' => $this->postalPostcode,
            'PostalState' => $this->postalState,
            'Phone' => $this->phone,
            'Email' => $this->email,
            'Note' => $this->note,
            'MaidenName' => $this->maidenName,
            'ID_Citizenship' => $this->idCitizenship,
            'CitizenshipCustom' => $this->citizenshipCustom,
            'ID_DistrictBirth' => $this->idDistrictBirth,
            'BirthCity' => $this->birthCity,
            'ID_PersonParentPerson' => $this->idPersonParentPerson,
            'ID_PersonParent' => $this->idPersonParent,
            'ID_ParentType' => $this->idParentType,
            'ParentType' => $this->parentType,
            'ParentTypeCustom' => $this->parentTypeCustom,
            'FirstNameParent' => $this->firstNameParent,
            'LastNameParent' => $this->lastNameParent,
            'EmailParent' => $this->emailParent,
            'PhoneParent' => $this->phoneParent,
            'NoteParent' => $this->noteParent,
            'ParentNote' => $this->parentNote,
            'DeleteParent' => $this->deleteParent,
            'ID_PersonParentPerson2' => $this->idPersonParentPerson2,
            'ID_PersonParent2' => $this->idPersonParent2,
            'ID_ParentType2' => $this->idParentType2,
            'ParentType2' => $this->parentType2,
            'ParentTypeCustom2' => $this->parentTypeCustom2,
            'FirstNameParent2' => $this->firstNameParent2,
            'LastNameParent2' => $this->lastNameParent2,
            'EmailParent2' => $this->emailParent2,
            'PhoneParent2' => $this->phoneParent2,
            'NoteParent2' => $this->noteParent2,
            'Parent2Note' => $this->parent2Note,
            'DeleteParent2' => $this->deleteParent2,
            'ID_Assurance' => $this->idAssurance,
            'InsuranceNumber' => $this->insuranceNumber,
            'Allergy' => $this->allergy,
            'FoodRestrictions' => $this->foodRestrictions,
            'Drugs' => $this->drugs,
            'SpecialRequirements' => $this->specialRequirements,
            'HealthLimitation' => $this->healthLimitation,
            'BodySkills' => $this->bodySkills,
            'School' => $this->school,
            'CheckCorrect' => $this->checkCorrect,
            'IsPostalSame' => $this->isPostalSame,
            ],
            fn (mixed $v): bool => $v !== null,
        );
    }
}
