<?php

namespace Misakstvanu\LaravelSkautis\Requests\OrganizationUnit;

final class RealtyUpdateIsPowerInput
{
    public function __construct(
        public readonly ?int $id = null,
        public readonly ?string $displayName = null,
        public readonly ?int $idRealtyType = null,
        public readonly ?string $realtyType = null,
        public readonly ?string $street = null,
        public readonly ?string $city = null,
        public readonly ?string $postcode = null,
        public readonly ?float $gpsLatitude = null,
        public readonly ?float $gpsLongitude = null,
        public readonly ?string $description = null,
        public readonly ?string $note = null,
        public readonly ?int $idRealtyCollection = null,
        public readonly ?string $realtyCollection = null,
        public readonly ?string $idOwnerType = null,
        public readonly ?string $ownerType = null,
        public readonly ?string $ownerTypeNote = null,
        public readonly ?bool $isPower = null,
        public readonly ?string $validTo = null,
        public readonly ?bool $isActive = null,
        public readonly ?string $photoExtension = null,
        public readonly ?string $photoFileContent = null,
        public readonly ?string $idTempFilePhoto = null,
        public readonly ?string $fotogalleryUrl = null,
        public readonly ?bool $isAddressAuthenticated = null,
        public readonly ?string $district = null,
        public readonly ?string $storage = null,
        public readonly ?int $idDocument = null,
        public readonly ?string $parcelNumber = null,
        public readonly ?string $registerCity = null,
        public readonly ?string $cadastralArea = null,
        public readonly ?int $lVNumber = null,
        public readonly ?int $acreage = null,
        public readonly ?string $parcelType = null,
        public readonly ?string $landType = null,
        public readonly ?string $unit = null,
        public readonly ?string $unitRegistrationNumber = null,
        public readonly ?float $realtyGpsLatitude = null,
        public readonly ?float $realtyGpsLongitude = null,
        public readonly ?int $coordinateX = null,
        public readonly ?int $coordinateY = null,
    ) {}

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(
            [
            'ID' => $this->id,
            'DisplayName' => $this->displayName,
            'ID_RealtyType' => $this->idRealtyType,
            'RealtyType' => $this->realtyType,
            'Street' => $this->street,
            'City' => $this->city,
            'Postcode' => $this->postcode,
            'GpsLatitude' => $this->gpsLatitude,
            'GpsLongitude' => $this->gpsLongitude,
            'Description' => $this->description,
            'Note' => $this->note,
            'ID_RealtyCollection' => $this->idRealtyCollection,
            'RealtyCollection' => $this->realtyCollection,
            'ID_OwnerType' => $this->idOwnerType,
            'OwnerType' => $this->ownerType,
            'OwnerTypeNote' => $this->ownerTypeNote,
            'IsPower' => $this->isPower,
            'ValidTo' => $this->validTo,
            'IsActive' => $this->isActive,
            'PhotoExtension' => $this->photoExtension,
            'PhotoFileContent' => $this->photoFileContent,
            'ID_TempFilePhoto' => $this->idTempFilePhoto,
            'FotogalleryUrl' => $this->fotogalleryUrl,
            'IsAddressAuthenticated' => $this->isAddressAuthenticated,
            'District' => $this->district,
            'Storage' => $this->storage,
            'ID_Document' => $this->idDocument,
            'ParcelNumber' => $this->parcelNumber,
            'RegisterCity' => $this->registerCity,
            'CadastralArea' => $this->cadastralArea,
            'LVNumber' => $this->lVNumber,
            'Acreage' => $this->acreage,
            'ParcelType' => $this->parcelType,
            'LandType' => $this->landType,
            'Unit' => $this->unit,
            'UnitRegistrationNumber' => $this->unitRegistrationNumber,
            'RealtyGpsLatitude' => $this->realtyGpsLatitude,
            'RealtyGpsLongitude' => $this->realtyGpsLongitude,
            'CoordinateX' => $this->coordinateX,
            'CoordinateY' => $this->coordinateY,
            ],
            fn (mixed $v): bool => $v !== null,
        );
    }
}
