<?php

namespace Misakstvanu\LaravelSkautis\Requests\OrganizationUnit;

final class RegistrySendFunctionParentMessageInput
{
    public function __construct(
        public readonly ?int $id = null,
        public readonly ?string $displayName = null,
        public readonly ?int $sequence = null,
        public readonly ?int $idUnit = null,
        public readonly ?string $unit = null,
        public readonly ?string $registrationNumber = null,
        public readonly ?string $iC = null,
        public readonly ?string $street = null,
        public readonly ?string $city = null,
        public readonly ?string $postcode = null,
        public readonly ?bool $isPropertyOwner = null,
        public readonly ?string $propertyAgreementExtension = null,
        public readonly ?string $unitOld = null,
        public readonly ?string $streetOld = null,
        public readonly ?string $cityOld = null,
        public readonly ?string $postcodeOld = null,
        public readonly ?bool $isPropertyOwnerOld = null,
        public readonly ?string $idRegistryObject = null,
        public readonly ?string $registryObject = null,
        public readonly ?string $idRegistryType = null,
        public readonly ?string $registryType = null,
        public readonly ?string $idRegistryState = null,
        public readonly ?string $registryState = null,
        public readonly ?int $oldHistoryObjectId = null,
        public readonly ?int $newHistoryObjectId = null,
        public readonly ?int $idPersonCreate = null,
        public readonly ?string $personCreate = null,
        public readonly ?string $dateCreate = null,
        public readonly ?int $idPersonUpdate = null,
        public readonly ?string $personUpdate = null,
        public readonly ?string $dateUpdate = null,
        public readonly ?int $idPersonSent = null,
        public readonly ?string $personSent = null,
        public readonly ?string $dateSent = null,
        public readonly ?int $idPersonClosed = null,
        public readonly ?string $personClosed = null,
        public readonly ?string $dateClosed = null,
        public readonly ?int $idPersonCancel = null,
        public readonly ?string $personCancel = null,
        public readonly ?string $dateCancel = null,
        public readonly ?string $cancelDecision = null,
        public readonly ?int $idFunction = null,
        public readonly ?int $idFunctionType = null,
        public readonly ?string $functionType = null,
        public readonly ?string $personFunction = null,
        public readonly ?string $personFunctionOld = null,
        public readonly ?string $account = null,
        public readonly ?bool $newAccount = null,
        public readonly ?int $idPersonFunction = null,
        public readonly ?int $idPersonFunctionOld = null,
        public readonly ?string $note = null,
        public readonly ?int $idPersonSolving = null,
        public readonly ?string $personSolving = null,
        public readonly ?string $dateSolving = null,
        public readonly ?int $idDocument = null,
        public readonly ?int $idStatement = null,
        public readonly ?int $statementYear = null,
        public readonly ?int $idDocumentStatement = null,
        public readonly ?string $decisionSeatChangeExtension = null,
        public readonly ?int $idDocumentDecision = null,
        public readonly ?int $idDocumentPropertyAgreement = null,
    ) {}

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(
            [
            'ID' => $this->id,
            'DisplayName' => $this->displayName,
            'Sequence' => $this->sequence,
            'ID_Unit' => $this->idUnit,
            'Unit' => $this->unit,
            'RegistrationNumber' => $this->registrationNumber,
            'IC' => $this->iC,
            'Street' => $this->street,
            'City' => $this->city,
            'Postcode' => $this->postcode,
            'IsPropertyOwner' => $this->isPropertyOwner,
            'PropertyAgreementExtension' => $this->propertyAgreementExtension,
            'UnitOld' => $this->unitOld,
            'StreetOld' => $this->streetOld,
            'CityOld' => $this->cityOld,
            'PostcodeOld' => $this->postcodeOld,
            'IsPropertyOwnerOld' => $this->isPropertyOwnerOld,
            'ID_RegistryObject' => $this->idRegistryObject,
            'RegistryObject' => $this->registryObject,
            'ID_RegistryType' => $this->idRegistryType,
            'RegistryType' => $this->registryType,
            'ID_RegistryState' => $this->idRegistryState,
            'RegistryState' => $this->registryState,
            'OldHistoryObjectId' => $this->oldHistoryObjectId,
            'NewHistoryObjectId' => $this->newHistoryObjectId,
            'ID_PersonCreate' => $this->idPersonCreate,
            'PersonCreate' => $this->personCreate,
            'DateCreate' => $this->dateCreate,
            'ID_PersonUpdate' => $this->idPersonUpdate,
            'PersonUpdate' => $this->personUpdate,
            'DateUpdate' => $this->dateUpdate,
            'ID_PersonSent' => $this->idPersonSent,
            'PersonSent' => $this->personSent,
            'DateSent' => $this->dateSent,
            'ID_PersonClosed' => $this->idPersonClosed,
            'PersonClosed' => $this->personClosed,
            'DateClosed' => $this->dateClosed,
            'ID_PersonCancel' => $this->idPersonCancel,
            'PersonCancel' => $this->personCancel,
            'DateCancel' => $this->dateCancel,
            'CancelDecision' => $this->cancelDecision,
            'ID_Function' => $this->idFunction,
            'ID_FunctionType' => $this->idFunctionType,
            'FunctionType' => $this->functionType,
            'PersonFunction' => $this->personFunction,
            'PersonFunctionOld' => $this->personFunctionOld,
            'Account' => $this->account,
            'NewAccount' => $this->newAccount,
            'ID_PersonFunction' => $this->idPersonFunction,
            'ID_PersonFunctionOld' => $this->idPersonFunctionOld,
            'Note' => $this->note,
            'ID_PersonSolving' => $this->idPersonSolving,
            'PersonSolving' => $this->personSolving,
            'DateSolving' => $this->dateSolving,
            'ID_Document' => $this->idDocument,
            'ID_Statement' => $this->idStatement,
            'StatementYear' => $this->statementYear,
            'ID_DocumentStatement' => $this->idDocumentStatement,
            'DecisionSeatChangeExtension' => $this->decisionSeatChangeExtension,
            'ID_DocumentDecision' => $this->idDocumentDecision,
            'ID_DocumentPropertyAgreement' => $this->idDocumentPropertyAgreement,
            ],
            fn (mixed $v): bool => $v !== null,
        );
    }
}
