<?php

namespace Misakstvanu\LaravelSkautis\Requests\OrganizationUnit;

final class UnitUpdateJournalParentInput
{
    public function __construct(
        public readonly ?int $id = null,
        public readonly ?int $idGroup = null,
        public readonly ?int $idUnit = null,
        public readonly ?string $idUnitType = null,
        public readonly ?string $unitType = null,
        public readonly ?bool $containsMembers = null,
        public readonly ?int $commissionDeadline = null,
        public readonly ?string $displayName = null,
        public readonly ?string $sortName = null,
        public readonly ?string $registrationNumber = null,
        public readonly ?string $shortRegistrationNumber = null,
        public readonly ?string $location = null,
        public readonly ?string $locationNew = null,
        public readonly ?string $iC = null,
        public readonly ?bool $isVatPayer = null,
        public readonly ?string $dIC = null,
        public readonly ?string $fileReference = null,
        public readonly ?string $street = null,
        public readonly ?string $city = null,
        public readonly ?string $postcode = null,
        public readonly ?string $state = null,
        public readonly ?string $postalFirstLine = null,
        public readonly ?string $postalStreet = null,
        public readonly ?string $postalCity = null,
        public readonly ?string $postalPostcode = null,
        public readonly ?string $postalState = null,
        public readonly ?string $note = null,
        public readonly ?int $idTroopArt = null,
        public readonly ?string $troopArt = null,
        public readonly ?bool $canUpdateRegistrationNumber = null,
        public readonly ?string $logoContent = null,
        public readonly ?string $logoExtension = null,
        public readonly ?int $idDocumentLogo = null,
        public readonly ?bool $isUnitCancel = null,
        public readonly ?bool $journalParent = null,
        public readonly ?bool $changeFreeJournal = null,
        public readonly ?int $idUnitParent = null,
        public readonly ?bool $onlyValidate = null,
        public readonly ?bool $isPostalAuthenticated = null,
        public readonly ?bool $isAddressAuthenticated = null,
        public readonly ?string $addressDistrict = null,
        public readonly ?string $postalDistrict = null,
        public readonly ?string $newDisplayName = null,
        public readonly ?string $completeDisplayName = null,
        public readonly ?int $idPersonChangeName = null,
        public readonly ?string $personChangeName = null,
        public readonly ?string $dateChangeName = null,
        public readonly ?bool $isPropertyOwner = null,
        public readonly ?string $propertyAgreementExtension = null,
        public readonly ?string $idTempFilePropertyAgreement = null,
        public readonly ?string $propertyAgreementContent = null,
        public readonly ?string $troopArtKey = null,
        public readonly ?string $idJournalNovice = null,
        public readonly ?string $idJournalDeliveryType = null,
        public readonly ?string $fullDisplayName = null,
        public readonly ?int $idDocumentDecision = null,
        public readonly ?int $idDocumentPropertyAgreement = null,
        public readonly ?string $decisionSeatChangeExtension = null,
        public readonly ?string $shopDiscountBarcode = null,
        public readonly ?string $idTempFileSeatChange = null,
        public readonly ?string $idUnitFoundReason = null,
        public readonly ?string $unitFoundReason = null,
        public readonly ?string $unitFoundDescription = null,
        public readonly ?string $idTempFileUnitLogo = null,
    ) {}

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(
            [
            'ID' => $this->id,
            'ID_Group' => $this->idGroup,
            'ID_Unit' => $this->idUnit,
            'ID_UnitType' => $this->idUnitType,
            'UnitType' => $this->unitType,
            'ContainsMembers' => $this->containsMembers,
            'CommissionDeadline' => $this->commissionDeadline,
            'DisplayName' => $this->displayName,
            'SortName' => $this->sortName,
            'RegistrationNumber' => $this->registrationNumber,
            'ShortRegistrationNumber' => $this->shortRegistrationNumber,
            'Location' => $this->location,
            'LocationNew' => $this->locationNew,
            'IC' => $this->iC,
            'IsVatPayer' => $this->isVatPayer,
            'DIC' => $this->dIC,
            'FileReference' => $this->fileReference,
            'Street' => $this->street,
            'City' => $this->city,
            'Postcode' => $this->postcode,
            'State' => $this->state,
            'PostalFirstLine' => $this->postalFirstLine,
            'PostalStreet' => $this->postalStreet,
            'PostalCity' => $this->postalCity,
            'PostalPostcode' => $this->postalPostcode,
            'PostalState' => $this->postalState,
            'Note' => $this->note,
            'ID_TroopArt' => $this->idTroopArt,
            'TroopArt' => $this->troopArt,
            'CanUpdateRegistrationNumber' => $this->canUpdateRegistrationNumber,
            'LogoContent' => $this->logoContent,
            'LogoExtension' => $this->logoExtension,
            'ID_DocumentLogo' => $this->idDocumentLogo,
            'IsUnitCancel' => $this->isUnitCancel,
            'JournalParent' => $this->journalParent,
            'ChangeFreeJournal' => $this->changeFreeJournal,
            'ID_UnitParent' => $this->idUnitParent,
            'OnlyValidate' => $this->onlyValidate,
            'IsPostalAuthenticated' => $this->isPostalAuthenticated,
            'IsAddressAuthenticated' => $this->isAddressAuthenticated,
            'AddressDistrict' => $this->addressDistrict,
            'PostalDistrict' => $this->postalDistrict,
            'NewDisplayName' => $this->newDisplayName,
            'CompleteDisplayName' => $this->completeDisplayName,
            'ID_PersonChangeName' => $this->idPersonChangeName,
            'PersonChangeName' => $this->personChangeName,
            'DateChangeName' => $this->dateChangeName,
            'IsPropertyOwner' => $this->isPropertyOwner,
            'PropertyAgreementExtension' => $this->propertyAgreementExtension,
            'ID_TempFilePropertyAgreement' => $this->idTempFilePropertyAgreement,
            'PropertyAgreementContent' => $this->propertyAgreementContent,
            'TroopArtKey' => $this->troopArtKey,
            'ID_JournalNovice' => $this->idJournalNovice,
            'ID_JournalDeliveryType' => $this->idJournalDeliveryType,
            'FullDisplayName' => $this->fullDisplayName,
            'ID_DocumentDecision' => $this->idDocumentDecision,
            'ID_DocumentPropertyAgreement' => $this->idDocumentPropertyAgreement,
            'DecisionSeatChangeExtension' => $this->decisionSeatChangeExtension,
            'ShopDiscountBarcode' => $this->shopDiscountBarcode,
            'ID_TempFileSeatChange' => $this->idTempFileSeatChange,
            'ID_UnitFoundReason' => $this->idUnitFoundReason,
            'UnitFoundReason' => $this->unitFoundReason,
            'UnitFoundDescription' => $this->unitFoundDescription,
            'ID_TempFileUnitLogo' => $this->idTempFileUnitLogo,
            ],
            fn (mixed $v): bool => $v !== null,
        );
    }
}
