<?php

namespace Misakstvanu\LaravelSkautis\Responses\Power;

final class EnrollEnergyAllOutput
{
    public function __construct(
        public readonly ?int $id = null,
        public readonly ?string $idLogin = null,
        public readonly ?int $idUserCreate = null,
        public readonly ?int $idPersonCreate = null,
        public readonly ?string $personCreate = null,
        public readonly ?string $note = null,
        public readonly ?string $person = null,
        public readonly ?string $dateCreate = null,
        public readonly ?string $idEnrollEnergyType = null,
        public readonly ?string $phone = null,
        public readonly ?string $email = null,
        public readonly ?string $enrollEnergyType = null,
        public readonly ?int $idPerson = null,
        public readonly ?string $firstName = null,
        public readonly ?string $lastName = null,
        public readonly ?string $identificationCode = null,
        public readonly ?int $idUnit = null,
        public readonly ?string $registrationNumber = null,
        public readonly ?string $unit = null,
        public readonly ?string $unitName = null,
        public readonly ?string $company = null,
        public readonly ?string $iC = null,
        public readonly ?string $dIC = null,
        public readonly ?string $agent = null,
        public readonly ?string $function_ = null,
        public readonly ?string $street = null,
        public readonly ?string $city = null,
        public readonly ?string $postcode = null,
        public readonly ?string $energySupplier1 = null,
        public readonly ?string $energySupplier2 = null,
        public readonly ?bool $hasPermissionReadPower = null,
        public readonly ?string $accountExtension = null,
        public readonly ?string $agreementExtension = null,
        public readonly ?string $otherExtension = null,
        public readonly ?string $advanceType = null,
        public readonly ?string $idAdvanceType = null,
        public readonly ?string $advanceTypeContent = null,
        public readonly ?float $advanceAmount = null,
        public readonly ?string $invitation = null,
    ) {}

    public static function fromStdClass(\stdClass $obj): self
    {
        return new self(
            id: isset($obj->{'ID'}) ? (int) $obj->{'ID'} : null,
            idLogin: isset($obj->{'ID_Login'}) ? (string) $obj->{'ID_Login'} : null,
            idUserCreate: isset($obj->{'ID_UserCreate'}) ? (int) $obj->{'ID_UserCreate'} : null,
            idPersonCreate: isset($obj->{'ID_PersonCreate'}) ? (int) $obj->{'ID_PersonCreate'} : null,
            personCreate: isset($obj->{'PersonCreate'}) ? (string) $obj->{'PersonCreate'} : null,
            note: isset($obj->{'Note'}) ? (string) $obj->{'Note'} : null,
            person: isset($obj->{'Person'}) ? (string) $obj->{'Person'} : null,
            dateCreate: isset($obj->{'DateCreate'}) ? (string) $obj->{'DateCreate'} : null,
            idEnrollEnergyType: isset($obj->{'ID_EnrollEnergyType'}) ? (string) $obj->{'ID_EnrollEnergyType'} : null,
            phone: isset($obj->{'Phone'}) ? (string) $obj->{'Phone'} : null,
            email: isset($obj->{'Email'}) ? (string) $obj->{'Email'} : null,
            enrollEnergyType: isset($obj->{'EnrollEnergyType'}) ? (string) $obj->{'EnrollEnergyType'} : null,
            idPerson: isset($obj->{'ID_Person'}) ? (int) $obj->{'ID_Person'} : null,
            firstName: isset($obj->{'FirstName'}) ? (string) $obj->{'FirstName'} : null,
            lastName: isset($obj->{'LastName'}) ? (string) $obj->{'LastName'} : null,
            identificationCode: isset($obj->{'IdentificationCode'}) ? (string) $obj->{'IdentificationCode'} : null,
            idUnit: isset($obj->{'ID_Unit'}) ? (int) $obj->{'ID_Unit'} : null,
            registrationNumber: isset($obj->{'RegistrationNumber'}) ? (string) $obj->{'RegistrationNumber'} : null,
            unit: isset($obj->{'Unit'}) ? (string) $obj->{'Unit'} : null,
            unitName: isset($obj->{'UnitName'}) ? (string) $obj->{'UnitName'} : null,
            company: isset($obj->{'Company'}) ? (string) $obj->{'Company'} : null,
            iC: isset($obj->{'IC'}) ? (string) $obj->{'IC'} : null,
            dIC: isset($obj->{'DIC'}) ? (string) $obj->{'DIC'} : null,
            agent: isset($obj->{'Agent'}) ? (string) $obj->{'Agent'} : null,
            function_: isset($obj->{'Function'}) ? (string) $obj->{'Function'} : null,
            street: isset($obj->{'Street'}) ? (string) $obj->{'Street'} : null,
            city: isset($obj->{'City'}) ? (string) $obj->{'City'} : null,
            postcode: isset($obj->{'Postcode'}) ? (string) $obj->{'Postcode'} : null,
            energySupplier1: isset($obj->{'EnergySupplier1'}) ? (string) $obj->{'EnergySupplier1'} : null,
            energySupplier2: isset($obj->{'EnergySupplier2'}) ? (string) $obj->{'EnergySupplier2'} : null,
            hasPermissionReadPower: isset($obj->{'HasPermissionReadPower'}) ? (bool) $obj->{'HasPermissionReadPower'} : null,
            accountExtension: isset($obj->{'AccountExtension'}) ? (string) $obj->{'AccountExtension'} : null,
            agreementExtension: isset($obj->{'AgreementExtension'}) ? (string) $obj->{'AgreementExtension'} : null,
            otherExtension: isset($obj->{'OtherExtension'}) ? (string) $obj->{'OtherExtension'} : null,
            advanceType: isset($obj->{'AdvanceType'}) ? (string) $obj->{'AdvanceType'} : null,
            idAdvanceType: isset($obj->{'ID_AdvanceType'}) ? (string) $obj->{'ID_AdvanceType'} : null,
            advanceTypeContent: isset($obj->{'AdvanceTypeContent'}) ? (string) $obj->{'AdvanceTypeContent'} : null,
            advanceAmount: isset($obj->{'AdvanceAmount'}) ? (float) $obj->{'AdvanceAmount'} : null,
            invitation: isset($obj->{'Invitation'}) ? (string) $obj->{'Invitation'} : null,
        );
    }
}
