<?php

namespace Misakstvanu\LaravelSkautis\Responses\Grants;

final class GrantDetailOutput
{
    public function __construct(
        public readonly ?string $idLogin = null,
        public readonly ?int $id = null,
        public readonly ?int $idEvent = null,
        public readonly ?int $idEventEducation = null,
        public readonly ?string $event = null,
        public readonly ?string $idGrantType = null,
        public readonly ?string $grantType = null,
        public readonly ?string $code = null,
        public readonly ?int $sequence = null,
        public readonly ?string $idGrantAdvanceType = null,
        public readonly ?string $grantAdvanceType = null,
        public readonly ?string $committeeNote = null,
        public readonly ?int $idUnit = null,
        public readonly ?string $unit = null,
        public readonly ?string $registrationNumber = null,
        public readonly ?string $unitFullName = null,
        public readonly ?string $grantAdvanceNote = null,
        public readonly ?int $idEventEducationCourse = null,
        public readonly ?string $eventEducationCourse = null,
        public readonly ?string $idGrantState = null,
        public readonly ?string $grantState = null,
        public readonly ?int $idGrantDecision = null,
        public readonly ?string $idGrantDecisionState = null,
        public readonly ?string $grantDecisionState = null,
        public readonly ?bool $isApproved = null,
        public readonly ?string $denialReason = null,
        public readonly ?float $advanceSentAmount = null,
        public readonly ?string $submitted = null,
        public readonly ?int $idPersonSubmitter = null,
        public readonly ?string $personSubmitter = null,
        public readonly ?string $personSubmitterContact = null,
        public readonly ?string $confirmed = null,
        public readonly ?int $idPersonConfirmer = null,
        public readonly ?string $personConfirmer = null,
        public readonly ?string $civilNameConfirmer = null,
        public readonly ?string $personConfirmerContact = null,
        public readonly ?int $idPersonCommitte = null,
        public readonly ?string $personCommitte = null,
        public readonly ?string $civilNameCommitte = null,
        public readonly ?string $personCommitteContact = null,
        public readonly ?string $changeNote = null,
        public readonly ?int $year = null,
        public readonly ?string $specificSymbol = null,
        public readonly ?string $evaluation = null,
        public readonly ?string $evaluationDecoded = null,
        public readonly ?string $statementNote = null,
        public readonly ?string $projectName = null,
        public readonly ?int $idPersonLeader = null,
        public readonly ?string $personLeader = null,
        public readonly ?string $civilNameLeader = null,
        public readonly ?string $noteLeader = null,
        public readonly ?string $identificationCodeLeader = null,
        public readonly ?int $idPersonEconomist = null,
        public readonly ?string $personEconomist = null,
        public readonly ?string $noteEconomist = null,
        public readonly ?string $identificationCodeEconomist = null,
        public readonly ?int $idPersonResponsible = null,
        public readonly ?string $personResponsible = null,
        public readonly ?string $noteResponsible = null,
        public readonly ?string $identificationCodeResponsible = null,
        public readonly ?string $contactPhone = null,
        public readonly ?string $contactEmail = null,
        public readonly ?string $projectCharacteristic = null,
        public readonly ?string $contactPhoneEconomist = null,
        public readonly ?string $contactEmailEconomist = null,
        public readonly ?string $finalStatementNote = null,
        public readonly ?string $idTempFileFinalBudget = null,
        public readonly ?int $idDocumentFinalBudget = null,
        public readonly ?string $documentFinalBudget = null,
        public readonly ?bool $hasProject = null,
        public readonly ?int $idGrantProject = null,
        public readonly ?string $grantProjectNote = null,
        public readonly ?string $place = null,
        public readonly ?string $termFrom = null,
        public readonly ?string $termTo = null,
        public readonly ?string $contactPhoneResponsible = null,
        public readonly ?string $contactEmailResponsible = null,
        public readonly ?int $idGrantRealtyCollection = null,
        public readonly ?int $idRealtyCollection = null,
        public readonly ?string $realtyCollection = null,
        public readonly ?int $ownershipListNumber = null,
        public readonly ?string $cadastralArea = null,
        public readonly ?string $buildingOwner = null,
        public readonly ?string $parcelNumbers = null,
        public readonly ?string $parcelOwner = null,
        public readonly ?int $idPersonCommitteNote = null,
        public readonly ?float $remainingPay = null,
        public readonly ?string $leaderNote = null,
        public readonly ?float $amount = null,
        public readonly ?float $amountMax = null,
        public readonly ?float $amountMaxReal = null,
        public readonly ?float $amountMaxRatio = null,
        public readonly ?float $amountMaxRealRatio = null,
        public readonly ?float $amountMaxValid = null,
        public readonly ?float $amountMaxRealValid = null,
        public readonly ?float $amountRequested = null,
        public readonly ?float $amountReal = null,
        public readonly ?float $costs = null,
        public readonly ?float $costsReal = null,
        public readonly ?float $revenue = null,
        public readonly ?float $revenueReal = null,
        public readonly ?float $ratioMaxSettings = null,
        public readonly ?float $ratioMaxGrant = null,
        public readonly ?float $ratio = null,
        public readonly ?float $ratioReal = null,
        public readonly ?float $maximumCostsRatio = null,
        public readonly ?bool $warningAmountMaxRatio = null,
        public readonly ?bool $warningAmountMax = null,
        public readonly ?bool $warningProfit = null,
        public readonly ?bool $warningProfitNonZero = null,
        public readonly ?bool $warningAmountRatio = null,
        public readonly ?bool $warningAmountMaxRealRatio = null,
        public readonly ?bool $warningAmountRealMax = null,
        public readonly ?bool $warningProfitReal = null,
        public readonly ?bool $warningProfitRealNonZero = null,
        public readonly ?bool $isEstimation = null,
        public readonly ?float $realRequestedGrant = null,
        public readonly ?bool $isLocked = null,
        public readonly ?bool $isEstimationLocked = null,
        public readonly ?bool $hasCustomQuestions = null,
        public readonly ?bool $hasCustomEvaluationQuestions = null,
        public readonly ?string $committeeNoteDate = null,
        public readonly ?bool $isVisibleMaxAmount = null,
        public readonly ?string $realizationFrom = null,
        public readonly ?string $realizationTo = null,
        public readonly ?int $idPersonEventLeader = null,
        public readonly ?string $personEventLeader = null,
        public readonly ?string $civilNameEventLeader = null,
        public readonly ?float $amountGrant = null,
        public readonly ?float $amountStatement = null,
        public readonly ?bool $agree = null,
        public readonly ?string $eventEducation = null,
        public readonly ?string $grantConditions = null,
        public readonly ?float $grantAdvanceSupplement = null,
        public readonly ?float $grantAdvanceAmount = null,
        public readonly ?string $grantAdvanceSupplementDate = null,
        public readonly ?string $grantDecisionApproved = null,
        public readonly ?float $grantCostEvidenceTotal = null,
        public readonly ?int $idGrantProjectUniversal = null,
        public readonly ?string $lastSubmitted = null,
        public readonly ?string $grantGrantStateChangeNote = null,
    ) {}

    public static function fromStdClass(\stdClass $obj): self
    {
        return new self(
            idLogin: isset($obj->{'ID_Login'}) ? (string) $obj->{'ID_Login'} : null,
            id: isset($obj->{'ID'}) ? (int) $obj->{'ID'} : null,
            idEvent: isset($obj->{'ID_Event'}) ? (int) $obj->{'ID_Event'} : null,
            idEventEducation: isset($obj->{'ID_EventEducation'}) ? (int) $obj->{'ID_EventEducation'} : null,
            event: isset($obj->{'Event'}) ? (string) $obj->{'Event'} : null,
            idGrantType: isset($obj->{'ID_GrantType'}) ? (string) $obj->{'ID_GrantType'} : null,
            grantType: isset($obj->{'GrantType'}) ? (string) $obj->{'GrantType'} : null,
            code: isset($obj->{'Code'}) ? (string) $obj->{'Code'} : null,
            sequence: isset($obj->{'Sequence'}) ? (int) $obj->{'Sequence'} : null,
            idGrantAdvanceType: isset($obj->{'ID_GrantAdvanceType'}) ? (string) $obj->{'ID_GrantAdvanceType'} : null,
            grantAdvanceType: isset($obj->{'GrantAdvanceType'}) ? (string) $obj->{'GrantAdvanceType'} : null,
            committeeNote: isset($obj->{'CommitteeNote'}) ? (string) $obj->{'CommitteeNote'} : null,
            idUnit: isset($obj->{'ID_Unit'}) ? (int) $obj->{'ID_Unit'} : null,
            unit: isset($obj->{'Unit'}) ? (string) $obj->{'Unit'} : null,
            registrationNumber: isset($obj->{'RegistrationNumber'}) ? (string) $obj->{'RegistrationNumber'} : null,
            unitFullName: isset($obj->{'UnitFullName'}) ? (string) $obj->{'UnitFullName'} : null,
            grantAdvanceNote: isset($obj->{'GrantAdvanceNote'}) ? (string) $obj->{'GrantAdvanceNote'} : null,
            idEventEducationCourse: isset($obj->{'ID_EventEducationCourse'}) ? (int) $obj->{'ID_EventEducationCourse'} : null,
            eventEducationCourse: isset($obj->{'EventEducationCourse'}) ? (string) $obj->{'EventEducationCourse'} : null,
            idGrantState: isset($obj->{'ID_GrantState'}) ? (string) $obj->{'ID_GrantState'} : null,
            grantState: isset($obj->{'GrantState'}) ? (string) $obj->{'GrantState'} : null,
            idGrantDecision: isset($obj->{'ID_GrantDecision'}) ? (int) $obj->{'ID_GrantDecision'} : null,
            idGrantDecisionState: isset($obj->{'ID_GrantDecisionState'}) ? (string) $obj->{'ID_GrantDecisionState'} : null,
            grantDecisionState: isset($obj->{'GrantDecisionState'}) ? (string) $obj->{'GrantDecisionState'} : null,
            isApproved: isset($obj->{'IsApproved'}) ? (bool) $obj->{'IsApproved'} : null,
            denialReason: isset($obj->{'DenialReason'}) ? (string) $obj->{'DenialReason'} : null,
            advanceSentAmount: isset($obj->{'AdvanceSentAmount'}) ? (float) $obj->{'AdvanceSentAmount'} : null,
            submitted: isset($obj->{'Submitted'}) ? (string) $obj->{'Submitted'} : null,
            idPersonSubmitter: isset($obj->{'ID_PersonSubmitter'}) ? (int) $obj->{'ID_PersonSubmitter'} : null,
            personSubmitter: isset($obj->{'PersonSubmitter'}) ? (string) $obj->{'PersonSubmitter'} : null,
            personSubmitterContact: isset($obj->{'PersonSubmitterContact'}) ? (string) $obj->{'PersonSubmitterContact'} : null,
            confirmed: isset($obj->{'Confirmed'}) ? (string) $obj->{'Confirmed'} : null,
            idPersonConfirmer: isset($obj->{'ID_PersonConfirmer'}) ? (int) $obj->{'ID_PersonConfirmer'} : null,
            personConfirmer: isset($obj->{'PersonConfirmer'}) ? (string) $obj->{'PersonConfirmer'} : null,
            civilNameConfirmer: isset($obj->{'CivilNameConfirmer'}) ? (string) $obj->{'CivilNameConfirmer'} : null,
            personConfirmerContact: isset($obj->{'PersonConfirmerContact'}) ? (string) $obj->{'PersonConfirmerContact'} : null,
            idPersonCommitte: isset($obj->{'ID_PersonCommitte'}) ? (int) $obj->{'ID_PersonCommitte'} : null,
            personCommitte: isset($obj->{'PersonCommitte'}) ? (string) $obj->{'PersonCommitte'} : null,
            civilNameCommitte: isset($obj->{'CivilNameCommitte'}) ? (string) $obj->{'CivilNameCommitte'} : null,
            personCommitteContact: isset($obj->{'PersonCommitteContact'}) ? (string) $obj->{'PersonCommitteContact'} : null,
            changeNote: isset($obj->{'ChangeNote'}) ? (string) $obj->{'ChangeNote'} : null,
            year: isset($obj->{'Year'}) ? (int) $obj->{'Year'} : null,
            specificSymbol: isset($obj->{'SpecificSymbol'}) ? (string) $obj->{'SpecificSymbol'} : null,
            evaluation: isset($obj->{'Evaluation'}) ? (string) $obj->{'Evaluation'} : null,
            evaluationDecoded: isset($obj->{'EvaluationDecoded'}) ? (string) $obj->{'EvaluationDecoded'} : null,
            statementNote: isset($obj->{'StatementNote'}) ? (string) $obj->{'StatementNote'} : null,
            projectName: isset($obj->{'ProjectName'}) ? (string) $obj->{'ProjectName'} : null,
            idPersonLeader: isset($obj->{'ID_PersonLeader'}) ? (int) $obj->{'ID_PersonLeader'} : null,
            personLeader: isset($obj->{'PersonLeader'}) ? (string) $obj->{'PersonLeader'} : null,
            civilNameLeader: isset($obj->{'CivilNameLeader'}) ? (string) $obj->{'CivilNameLeader'} : null,
            noteLeader: isset($obj->{'NoteLeader'}) ? (string) $obj->{'NoteLeader'} : null,
            identificationCodeLeader: isset($obj->{'IdentificationCodeLeader'}) ? (string) $obj->{'IdentificationCodeLeader'} : null,
            idPersonEconomist: isset($obj->{'ID_PersonEconomist'}) ? (int) $obj->{'ID_PersonEconomist'} : null,
            personEconomist: isset($obj->{'PersonEconomist'}) ? (string) $obj->{'PersonEconomist'} : null,
            noteEconomist: isset($obj->{'NoteEconomist'}) ? (string) $obj->{'NoteEconomist'} : null,
            identificationCodeEconomist: isset($obj->{'IdentificationCodeEconomist'}) ? (string) $obj->{'IdentificationCodeEconomist'} : null,
            idPersonResponsible: isset($obj->{'ID_PersonResponsible'}) ? (int) $obj->{'ID_PersonResponsible'} : null,
            personResponsible: isset($obj->{'PersonResponsible'}) ? (string) $obj->{'PersonResponsible'} : null,
            noteResponsible: isset($obj->{'NoteResponsible'}) ? (string) $obj->{'NoteResponsible'} : null,
            identificationCodeResponsible: isset($obj->{'IdentificationCodeResponsible'}) ? (string) $obj->{'IdentificationCodeResponsible'} : null,
            contactPhone: isset($obj->{'ContactPhone'}) ? (string) $obj->{'ContactPhone'} : null,
            contactEmail: isset($obj->{'ContactEmail'}) ? (string) $obj->{'ContactEmail'} : null,
            projectCharacteristic: isset($obj->{'ProjectCharacteristic'}) ? (string) $obj->{'ProjectCharacteristic'} : null,
            contactPhoneEconomist: isset($obj->{'ContactPhoneEconomist'}) ? (string) $obj->{'ContactPhoneEconomist'} : null,
            contactEmailEconomist: isset($obj->{'ContactEmailEconomist'}) ? (string) $obj->{'ContactEmailEconomist'} : null,
            finalStatementNote: isset($obj->{'FinalStatementNote'}) ? (string) $obj->{'FinalStatementNote'} : null,
            idTempFileFinalBudget: isset($obj->{'ID_TempFileFinalBudget'}) ? (string) $obj->{'ID_TempFileFinalBudget'} : null,
            idDocumentFinalBudget: isset($obj->{'ID_DocumentFinalBudget'}) ? (int) $obj->{'ID_DocumentFinalBudget'} : null,
            documentFinalBudget: isset($obj->{'DocumentFinalBudget'}) ? (string) $obj->{'DocumentFinalBudget'} : null,
            hasProject: isset($obj->{'HasProject'}) ? (bool) $obj->{'HasProject'} : null,
            idGrantProject: isset($obj->{'ID_GrantProject'}) ? (int) $obj->{'ID_GrantProject'} : null,
            grantProjectNote: isset($obj->{'GrantProjectNote'}) ? (string) $obj->{'GrantProjectNote'} : null,
            place: isset($obj->{'Place'}) ? (string) $obj->{'Place'} : null,
            termFrom: isset($obj->{'TermFrom'}) ? (string) $obj->{'TermFrom'} : null,
            termTo: isset($obj->{'TermTo'}) ? (string) $obj->{'TermTo'} : null,
            contactPhoneResponsible: isset($obj->{'ContactPhoneResponsible'}) ? (string) $obj->{'ContactPhoneResponsible'} : null,
            contactEmailResponsible: isset($obj->{'ContactEmailResponsible'}) ? (string) $obj->{'ContactEmailResponsible'} : null,
            idGrantRealtyCollection: isset($obj->{'ID_GrantRealtyCollection'}) ? (int) $obj->{'ID_GrantRealtyCollection'} : null,
            idRealtyCollection: isset($obj->{'ID_RealtyCollection'}) ? (int) $obj->{'ID_RealtyCollection'} : null,
            realtyCollection: isset($obj->{'RealtyCollection'}) ? (string) $obj->{'RealtyCollection'} : null,
            ownershipListNumber: isset($obj->{'OwnershipListNumber'}) ? (int) $obj->{'OwnershipListNumber'} : null,
            cadastralArea: isset($obj->{'CadastralArea'}) ? (string) $obj->{'CadastralArea'} : null,
            buildingOwner: isset($obj->{'BuildingOwner'}) ? (string) $obj->{'BuildingOwner'} : null,
            parcelNumbers: isset($obj->{'ParcelNumbers'}) ? (string) $obj->{'ParcelNumbers'} : null,
            parcelOwner: isset($obj->{'ParcelOwner'}) ? (string) $obj->{'ParcelOwner'} : null,
            idPersonCommitteNote: isset($obj->{'ID_PersonCommitteNote'}) ? (int) $obj->{'ID_PersonCommitteNote'} : null,
            remainingPay: isset($obj->{'RemainingPay'}) ? (float) $obj->{'RemainingPay'} : null,
            leaderNote: isset($obj->{'LeaderNote'}) ? (string) $obj->{'LeaderNote'} : null,
            amount: isset($obj->{'Amount'}) ? (float) $obj->{'Amount'} : null,
            amountMax: isset($obj->{'AmountMax'}) ? (float) $obj->{'AmountMax'} : null,
            amountMaxReal: isset($obj->{'AmountMaxReal'}) ? (float) $obj->{'AmountMaxReal'} : null,
            amountMaxRatio: isset($obj->{'AmountMaxRatio'}) ? (float) $obj->{'AmountMaxRatio'} : null,
            amountMaxRealRatio: isset($obj->{'AmountMaxRealRatio'}) ? (float) $obj->{'AmountMaxRealRatio'} : null,
            amountMaxValid: isset($obj->{'AmountMaxValid'}) ? (float) $obj->{'AmountMaxValid'} : null,
            amountMaxRealValid: isset($obj->{'AmountMaxRealValid'}) ? (float) $obj->{'AmountMaxRealValid'} : null,
            amountRequested: isset($obj->{'AmountRequested'}) ? (float) $obj->{'AmountRequested'} : null,
            amountReal: isset($obj->{'AmountReal'}) ? (float) $obj->{'AmountReal'} : null,
            costs: isset($obj->{'Costs'}) ? (float) $obj->{'Costs'} : null,
            costsReal: isset($obj->{'CostsReal'}) ? (float) $obj->{'CostsReal'} : null,
            revenue: isset($obj->{'Revenue'}) ? (float) $obj->{'Revenue'} : null,
            revenueReal: isset($obj->{'RevenueReal'}) ? (float) $obj->{'RevenueReal'} : null,
            ratioMaxSettings: isset($obj->{'RatioMaxSettings'}) ? (float) $obj->{'RatioMaxSettings'} : null,
            ratioMaxGrant: isset($obj->{'RatioMaxGrant'}) ? (float) $obj->{'RatioMaxGrant'} : null,
            ratio: isset($obj->{'Ratio'}) ? (float) $obj->{'Ratio'} : null,
            ratioReal: isset($obj->{'RatioReal'}) ? (float) $obj->{'RatioReal'} : null,
            maximumCostsRatio: isset($obj->{'MaximumCostsRatio'}) ? (float) $obj->{'MaximumCostsRatio'} : null,
            warningAmountMaxRatio: isset($obj->{'WarningAmountMaxRatio'}) ? (bool) $obj->{'WarningAmountMaxRatio'} : null,
            warningAmountMax: isset($obj->{'WarningAmountMax'}) ? (bool) $obj->{'WarningAmountMax'} : null,
            warningProfit: isset($obj->{'WarningProfit'}) ? (bool) $obj->{'WarningProfit'} : null,
            warningProfitNonZero: isset($obj->{'WarningProfitNonZero'}) ? (bool) $obj->{'WarningProfitNonZero'} : null,
            warningAmountRatio: isset($obj->{'WarningAmountRatio'}) ? (bool) $obj->{'WarningAmountRatio'} : null,
            warningAmountMaxRealRatio: isset($obj->{'WarningAmountMaxRealRatio'}) ? (bool) $obj->{'WarningAmountMaxRealRatio'} : null,
            warningAmountRealMax: isset($obj->{'WarningAmountRealMax'}) ? (bool) $obj->{'WarningAmountRealMax'} : null,
            warningProfitReal: isset($obj->{'WarningProfitReal'}) ? (bool) $obj->{'WarningProfitReal'} : null,
            warningProfitRealNonZero: isset($obj->{'WarningProfitRealNonZero'}) ? (bool) $obj->{'WarningProfitRealNonZero'} : null,
            isEstimation: isset($obj->{'IsEstimation'}) ? (bool) $obj->{'IsEstimation'} : null,
            realRequestedGrant: isset($obj->{'RealRequestedGrant'}) ? (float) $obj->{'RealRequestedGrant'} : null,
            isLocked: isset($obj->{'IsLocked'}) ? (bool) $obj->{'IsLocked'} : null,
            isEstimationLocked: isset($obj->{'IsEstimationLocked'}) ? (bool) $obj->{'IsEstimationLocked'} : null,
            hasCustomQuestions: isset($obj->{'HasCustomQuestions'}) ? (bool) $obj->{'HasCustomQuestions'} : null,
            hasCustomEvaluationQuestions: isset($obj->{'HasCustomEvaluationQuestions'}) ? (bool) $obj->{'HasCustomEvaluationQuestions'} : null,
            committeeNoteDate: isset($obj->{'CommitteeNoteDate'}) ? (string) $obj->{'CommitteeNoteDate'} : null,
            isVisibleMaxAmount: isset($obj->{'IsVisibleMaxAmount'}) ? (bool) $obj->{'IsVisibleMaxAmount'} : null,
            realizationFrom: isset($obj->{'RealizationFrom'}) ? (string) $obj->{'RealizationFrom'} : null,
            realizationTo: isset($obj->{'RealizationTo'}) ? (string) $obj->{'RealizationTo'} : null,
            idPersonEventLeader: isset($obj->{'ID_PersonEventLeader'}) ? (int) $obj->{'ID_PersonEventLeader'} : null,
            personEventLeader: isset($obj->{'PersonEventLeader'}) ? (string) $obj->{'PersonEventLeader'} : null,
            civilNameEventLeader: isset($obj->{'CivilNameEventLeader'}) ? (string) $obj->{'CivilNameEventLeader'} : null,
            amountGrant: isset($obj->{'AmountGrant'}) ? (float) $obj->{'AmountGrant'} : null,
            amountStatement: isset($obj->{'AmountStatement'}) ? (float) $obj->{'AmountStatement'} : null,
            agree: isset($obj->{'Agree'}) ? (bool) $obj->{'Agree'} : null,
            eventEducation: isset($obj->{'EventEducation'}) ? (string) $obj->{'EventEducation'} : null,
            grantConditions: isset($obj->{'GrantConditions'}) ? (string) $obj->{'GrantConditions'} : null,
            grantAdvanceSupplement: isset($obj->{'GrantAdvanceSupplement'}) ? (float) $obj->{'GrantAdvanceSupplement'} : null,
            grantAdvanceAmount: isset($obj->{'GrantAdvanceAmount'}) ? (float) $obj->{'GrantAdvanceAmount'} : null,
            grantAdvanceSupplementDate: isset($obj->{'GrantAdvanceSupplementDate'}) ? (string) $obj->{'GrantAdvanceSupplementDate'} : null,
            grantDecisionApproved: isset($obj->{'GrantDecisionApproved'}) ? (string) $obj->{'GrantDecisionApproved'} : null,
            grantCostEvidenceTotal: isset($obj->{'GrantCostEvidenceTotal'}) ? (float) $obj->{'GrantCostEvidenceTotal'} : null,
            idGrantProjectUniversal: isset($obj->{'ID_GrantProjectUniversal'}) ? (int) $obj->{'ID_GrantProjectUniversal'} : null,
            lastSubmitted: isset($obj->{'LastSubmitted'}) ? (string) $obj->{'LastSubmitted'} : null,
            grantGrantStateChangeNote: isset($obj->{'GrantGrantStateChangeNote'}) ? (string) $obj->{'GrantGrantStateChangeNote'} : null,
        );
    }
}
