<?php

namespace Misakstvanu\LaravelSkautis\Requests\Events;

final class CandidateInsertInput
{
    public function __construct(
        public readonly ?int $id = null,
        public readonly ?string $displayName = null,
        public readonly ?int $idEventCongress = null,
        public readonly ?string $eventCongress = null,
        public readonly ?string $idCandidateState = null,
        public readonly ?string $candidateState = null,
        public readonly ?string $stateDecision = null,
        public readonly ?int $idUserCreate = null,
        public readonly ?int $idPersonCreate = null,
        public readonly ?string $personCreate = null,
        public readonly ?string $dateCreate = null,
        public readonly ?int $idPerson = null,
        public readonly ?string $person = null,
        public readonly ?int $idCandidateWith = null,
        public readonly ?string $personWith = null,
        public readonly ?int $idEventCongressFunction = null,
        public readonly ?string $eventCongressFunction = null,
        public readonly ?string $functionType = null,
        public readonly ?bool $isCandidateWith = null,
        public readonly ?string $idTempFile = null,
        public readonly ?int $idDocument = null,
        public readonly ?string $additionalExperience = null,
        public readonly ?string $attachmentExtension = null,
        public readonly ?string $attachmentContent = null,
        public readonly ?string $career = null,
        public readonly ?string $suggesterName = null,
        public readonly ?string $suggesterFunction = null,
        public readonly ?string $suggesterDescription = null,
        public readonly ?string $presentation = null,
        public readonly ?string $success = null,
        public readonly ?string $agenda = null,
        public readonly ?string $problems = null,
        public readonly ?string $mainTask = null,
        public readonly ?int $votesCount = null,
        public readonly ?int $order = null,
        public readonly ?bool $isElected = null,
        public readonly ?string $unit = null,
        public readonly ?string $idUnitType = null,
        public readonly ?int $idPersonContact = null,
        public readonly ?int $idEducationSeminary = null,
        public readonly ?int $idFunction = null,
        public readonly ?int $idQualification = null,
        public readonly ?string $relation = null,
        public readonly ?string $description = null,
        public readonly ?int $yearFrom = null,
        public readonly ?int $yearTo = null,
    ) {}

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(
            [
            'ID' => $this->id,
            'DisplayName' => $this->displayName,
            'ID_EventCongress' => $this->idEventCongress,
            'EventCongress' => $this->eventCongress,
            'ID_CandidateState' => $this->idCandidateState,
            'CandidateState' => $this->candidateState,
            'StateDecision' => $this->stateDecision,
            'ID_UserCreate' => $this->idUserCreate,
            'ID_PersonCreate' => $this->idPersonCreate,
            'PersonCreate' => $this->personCreate,
            'DateCreate' => $this->dateCreate,
            'ID_Person' => $this->idPerson,
            'Person' => $this->person,
            'ID_CandidateWith' => $this->idCandidateWith,
            'PersonWith' => $this->personWith,
            'ID_EventCongressFunction' => $this->idEventCongressFunction,
            'EventCongressFunction' => $this->eventCongressFunction,
            'FunctionType' => $this->functionType,
            'IsCandidateWith' => $this->isCandidateWith,
            'ID_TempFile' => $this->idTempFile,
            'ID_Document' => $this->idDocument,
            'AdditionalExperience' => $this->additionalExperience,
            'AttachmentExtension' => $this->attachmentExtension,
            'AttachmentContent' => $this->attachmentContent,
            'Career' => $this->career,
            'SuggesterName' => $this->suggesterName,
            'SuggesterFunction' => $this->suggesterFunction,
            'SuggesterDescription' => $this->suggesterDescription,
            'Presentation' => $this->presentation,
            'Success' => $this->success,
            'Agenda' => $this->agenda,
            'Problems' => $this->problems,
            'MainTask' => $this->mainTask,
            'VotesCount' => $this->votesCount,
            'Order' => $this->order,
            'IsElected' => $this->isElected,
            'Unit' => $this->unit,
            'ID_UnitType' => $this->idUnitType,
            'ID_PersonContact' => $this->idPersonContact,
            'ID_EducationSeminary' => $this->idEducationSeminary,
            'ID_Function' => $this->idFunction,
            'ID_Qualification' => $this->idQualification,
            'Relation' => $this->relation,
            'Description' => $this->description,
            'YearFrom' => $this->yearFrom,
            'YearTo' => $this->yearTo,
            ],
            fn (mixed $v): bool => $v !== null,
        );
    }
}
