<?php

namespace Misakstvanu\LaravelSkautis\Requests\Events;

final class EventCongressUpdateSimplifiedEntryInput
{
    public function __construct(
        public readonly ?int $id = null,
        public readonly ?int $idEvent = null,
        public readonly ?string $event = null,
        public readonly ?int $idUnitRegistration = null,
        public readonly ?string $unitRegistration = null,
        public readonly ?string $promulgationDeadline = null,
        public readonly ?string $commissionDeadline = null,
        public readonly ?string $candidateDeadline = null,
        public readonly ?string $idEventCongressType = null,
        public readonly ?string $eventCongressType = null,
        public readonly ?string $idEventCongressState = null,
        public readonly ?string $eventCongressState = null,
        public readonly ?int $idUnit = null,
        public readonly ?string $unit = null,
        public readonly ?string $registrationNumber = null,
        public readonly ?string $idUnitType = null,
        public readonly ?string $startDate = null,
        public readonly ?string $endDate = null,
        public readonly ?float $gpsLatitude = null,
        public readonly ?float $gpsLongitude = null,
        public readonly ?string $location = null,
        public readonly ?string $alternateStartDate = null,
        public readonly ?string $alternateEndDate = null,
        public readonly ?float $alternateGpsLatitude = null,
        public readonly ?float $alternateGpsLongitude = null,
        public readonly ?string $alternateLocation = null,
        public readonly ?string $note = null,
        public readonly ?string $protocolExtension = null,
        public readonly ?string $protocolContent = null,
        public readonly ?int $candidateAfterDeadline = null,
        public readonly ?string $arriveDeadline = null,
        public readonly ?string $departureDeadline = null,
        public readonly ?string $transportDeadline = null,
        public readonly ?string $accommodationDeadline = null,
        public readonly ?string $foodDeadline = null,
        public readonly ?float $participantFee = null,
        public readonly ?string $functionAgreementExtension = null,
        public readonly ?string $simplifiedEntryExtension = null,
        public readonly ?string $simplifiedEntryTemplateExtension = null,
        public readonly ?string $idTempFileSimplifiedEntry = null,
        public readonly ?int $delegateQuota = null,
        public readonly ?bool $isDelegateQuotaParentSet = null,
        public readonly ?int $idDocumentProtocol = null,
        public readonly ?int $idDocumentSimplifiedEntry = null,
        public readonly ?bool $statutoryFunctionNotAssigned = null,
    ) {}

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(
            [
            'ID' => $this->id,
            'ID_Event' => $this->idEvent,
            'Event' => $this->event,
            'ID_UnitRegistration' => $this->idUnitRegistration,
            'UnitRegistration' => $this->unitRegistration,
            'PromulgationDeadline' => $this->promulgationDeadline,
            'CommissionDeadline' => $this->commissionDeadline,
            'CandidateDeadline' => $this->candidateDeadline,
            'ID_EventCongressType' => $this->idEventCongressType,
            'EventCongressType' => $this->eventCongressType,
            'ID_EventCongressState' => $this->idEventCongressState,
            'EventCongressState' => $this->eventCongressState,
            'ID_Unit' => $this->idUnit,
            'Unit' => $this->unit,
            'RegistrationNumber' => $this->registrationNumber,
            'ID_UnitType' => $this->idUnitType,
            'StartDate' => $this->startDate,
            'EndDate' => $this->endDate,
            'GpsLatitude' => $this->gpsLatitude,
            'GpsLongitude' => $this->gpsLongitude,
            'Location' => $this->location,
            'AlternateStartDate' => $this->alternateStartDate,
            'AlternateEndDate' => $this->alternateEndDate,
            'AlternateGpsLatitude' => $this->alternateGpsLatitude,
            'AlternateGpsLongitude' => $this->alternateGpsLongitude,
            'AlternateLocation' => $this->alternateLocation,
            'Note' => $this->note,
            'ProtocolExtension' => $this->protocolExtension,
            'ProtocolContent' => $this->protocolContent,
            'CandidateAfterDeadline' => $this->candidateAfterDeadline,
            'ArriveDeadline' => $this->arriveDeadline,
            'DepartureDeadline' => $this->departureDeadline,
            'TransportDeadline' => $this->transportDeadline,
            'AccommodationDeadline' => $this->accommodationDeadline,
            'FoodDeadline' => $this->foodDeadline,
            'ParticipantFee' => $this->participantFee,
            'FunctionAgreementExtension' => $this->functionAgreementExtension,
            'SimplifiedEntryExtension' => $this->simplifiedEntryExtension,
            'SimplifiedEntryTemplateExtension' => $this->simplifiedEntryTemplateExtension,
            'ID_TempFileSimplifiedEntry' => $this->idTempFileSimplifiedEntry,
            'DelegateQuota' => $this->delegateQuota,
            'IsDelegateQuotaParentSet' => $this->isDelegateQuotaParentSet,
            'ID_DocumentProtocol' => $this->idDocumentProtocol,
            'ID_DocumentSimplifiedEntry' => $this->idDocumentSimplifiedEntry,
            'StatutoryFunctionNotAssigned' => $this->statutoryFunctionNotAssigned,
            ],
            fn (mixed $v): bool => $v !== null,
        );
    }
}
