<?php

namespace Misakstvanu\LaravelSkautis\Requests\Events;

final class EventGeneralUpdateOpenInput
{
    public function __construct(
        public readonly ?int $id = null,
        public readonly ?int $idGroup = null,
        public readonly ?string $idEventType = null,
        public readonly ?int $idUserCreate = null,
        public readonly ?string $dateCreate = null,
        public readonly ?string $displayName = null,
        public readonly ?int $idUnit = null,
        public readonly ?string $unit = null,
        public readonly ?string $registrationNumber = null,
        public readonly ?string $startDate = null,
        public readonly ?string $endDate = null,
        public readonly ?int $totalDays = null,
        public readonly ?float $gpsLatitude = null,
        public readonly ?string $gpsLatitudeText = null,
        public readonly ?float $gpsLongitude = null,
        public readonly ?string $gpsLongitudeText = null,
        public readonly ?string $location = null,
        public readonly ?string $note = null,
        public readonly ?string $cancelDecision = null,
        public readonly ?int $idEvent = null,
        public readonly ?string $event = null,
        public readonly ?string $idEventGeneralState = null,
        public readonly ?string $eventGeneralState = null,
        public readonly ?int $idUnitEducative = null,
        public readonly ?string $unitEducative = null,
        public readonly ?string $unitEducativeRegistrationNumber = null,
        public readonly ?int $idEventGeneralType = null,
        public readonly ?string $eventGeneralType = null,
        public readonly ?int $idEventGeneralScope = null,
        public readonly ?string $eventGeneralScope = null,
        public readonly ?string $street = null,
        public readonly ?string $postcode = null,
        public readonly ?string $region = null,
        public readonly ?string $state = null,
        public readonly ?int $foreignParticipants = null,
        public readonly ?int $leaderParticipants = null,
        public readonly ?int $assistantParticipants = null,
        public readonly ?bool $isStatisticAutoComputed = null,
        public readonly ?int $childDays = null,
        public readonly ?int $personDays = null,
        public readonly ?string $target = null,
        public readonly ?string $program = null,
        public readonly ?int $idPersonClosed = null,
        public readonly ?string $personClosed = null,
        public readonly ?string $dateClosed = null,
        public readonly ?int $int = null,
        public readonly ?string $eventSpecificationType = null,
        public readonly ?bool $isAutoComputedDays = null,
        public readonly ?int $totalParticipants = null,
    ) {}

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(
            [
            'ID' => $this->id,
            'ID_Group' => $this->idGroup,
            'ID_EventType' => $this->idEventType,
            'ID_UserCreate' => $this->idUserCreate,
            'DateCreate' => $this->dateCreate,
            'DisplayName' => $this->displayName,
            'ID_Unit' => $this->idUnit,
            'Unit' => $this->unit,
            'RegistrationNumber' => $this->registrationNumber,
            'StartDate' => $this->startDate,
            'EndDate' => $this->endDate,
            'TotalDays' => $this->totalDays,
            'GpsLatitude' => $this->gpsLatitude,
            'GpsLatitudeText' => $this->gpsLatitudeText,
            'GpsLongitude' => $this->gpsLongitude,
            'GpsLongitudeText' => $this->gpsLongitudeText,
            'Location' => $this->location,
            'Note' => $this->note,
            'CancelDecision' => $this->cancelDecision,
            'ID_Event' => $this->idEvent,
            'Event' => $this->event,
            'ID_EventGeneralState' => $this->idEventGeneralState,
            'EventGeneralState' => $this->eventGeneralState,
            'ID_UnitEducative' => $this->idUnitEducative,
            'UnitEducative' => $this->unitEducative,
            'UnitEducativeRegistrationNumber' => $this->unitEducativeRegistrationNumber,
            'ID_EventGeneralType' => $this->idEventGeneralType,
            'EventGeneralType' => $this->eventGeneralType,
            'ID_EventGeneralScope' => $this->idEventGeneralScope,
            'EventGeneralScope' => $this->eventGeneralScope,
            'Street' => $this->street,
            'Postcode' => $this->postcode,
            'Region' => $this->region,
            'State' => $this->state,
            'ForeignParticipants' => $this->foreignParticipants,
            'LeaderParticipants' => $this->leaderParticipants,
            'AssistantParticipants' => $this->assistantParticipants,
            'IsStatisticAutoComputed' => $this->isStatisticAutoComputed,
            'ChildDays' => $this->childDays,
            'PersonDays' => $this->personDays,
            'Target' => $this->target,
            'Program' => $this->program,
            'ID_PersonClosed' => $this->idPersonClosed,
            'PersonClosed' => $this->personClosed,
            'DateClosed' => $this->dateClosed,
            'int' => $this->int,
            'EventSpecificationType' => $this->eventSpecificationType,
            'IsAutoComputedDays' => $this->isAutoComputedDays,
            'TotalParticipants' => $this->totalParticipants,
            ],
            fn (mixed $v): bool => $v !== null,
        );
    }
}
