<?php

namespace Misakstvanu\LaravelSkautis\Requests\Events;

final class EventCampUpdateCancelRealInput
{
    public function __construct(
        public readonly ?int $id = null,
        public readonly ?int $idGroup = null,
        public readonly ?string $idEventType = null,
        public readonly ?int $idUserCreate = null,
        public readonly ?string $dateCreate = null,
        public readonly ?string $displayName = null,
        public readonly ?int $idUnit = null,
        public readonly ?string $unit = null,
        public readonly ?string $registrationNumber = null,
        public readonly ?string $startDate = null,
        public readonly ?string $endDate = null,
        public readonly ?float $gpsLatitude = null,
        public readonly ?string $gpsLatitudeText = null,
        public readonly ?float $gpsLongitude = null,
        public readonly ?string $gpsLongitudeText = null,
        public readonly ?string $location = null,
        public readonly ?string $note = null,
        public readonly ?string $cancelDecision = null,
        public readonly ?int $idEvent = null,
        public readonly ?string $idEventCampState = null,
        public readonly ?string $eventCampState = null,
        public readonly ?string $mobileContact = null,
        public readonly ?string $mobileContactDisplay = null,
        public readonly ?string $registrationDeadline = null,
        public readonly ?int $idRegion = null,
        public readonly ?string $region = null,
        public readonly ?string $postcode = null,
        public readonly ?bool $isFloodArea = null,
        public readonly ?bool $isAutoComputed = null,
        public readonly ?int $idPersonApproved = null,
        public readonly ?string $personApproved = null,
        public readonly ?string $dateApproved = null,
        public readonly ?int $idPersonApprovedParent = null,
        public readonly ?string $personApprovedParent = null,
        public readonly ?string $dateApprovedParent = null,
        public readonly ?string $dateApprovedExecutive = null,
        public readonly ?int $totalDays = null,
        public readonly ?bool $isRecovering = null,
        public readonly ?string $campType = null,
        public readonly ?string $string = null,
        public readonly ?string $units = null,
        public readonly ?int $estimateChild = null,
        public readonly ?int $estimateAdult = null,
        public readonly ?int $estimateAdultYoung = null,
        public readonly ?int $estimateCount = null,
        public readonly ?int $estimateChildDays = null,
        public readonly ?int $estimatePersonDays = null,
        public readonly ?bool $isAutoComputedDays = null,
        public readonly ?float $realTotalCost = null,
        public readonly ?bool $isRealTotalCostAutoComputed = null,
        public readonly ?bool $isRealAutoComputed = null,
        public readonly ?bool $isRealAutoComputedDays = null,
        public readonly ?int $idPersonReal = null,
        public readonly ?string $personReal = null,
        public readonly ?string $dateReal = null,
        public readonly ?int $realAdult = null,
        public readonly ?int $realAdultYoung = null,
        public readonly ?int $realChild = null,
        public readonly ?int $realCount = null,
        public readonly ?int $realChildDays = null,
        public readonly ?int $realPersonDays = null,
        public readonly ?bool $hasEstimateStatement = null,
        public readonly ?int $idPersonLeader = null,
        public readonly ?string $personLeader = null,
        public readonly ?string $personLeaderFirstName = null,
        public readonly ?string $personLeaderLastName = null,
        public readonly ?string $personLeaderCivilName = null,
        public readonly ?string $leaderPhone = null,
        public readonly ?string $leaderPhoneDisplay = null,
        public readonly ?string $leaderEmail = null,
        public readonly ?string $leaderEmailDisplay = null,
        public readonly ?string $leaderCity = null,
        public readonly ?string $unitLocation = null,
        public readonly ?string $personStatutory = null,
        public readonly ?float $profit = null,
        public readonly ?float $profitComputed = null,
        public readonly ?float $profitComputedEstimation = null,
        public readonly ?int $idCampPlace = null,
        public readonly ?string $campPlace = null,
        public readonly ?bool $isOnlineLogin = null,
        public readonly ?bool $canUpdate = null,
        public readonly ?bool $canUpdateReal = null,
        public readonly ?int $adultYoung = null,
        public readonly ?bool $isRealVisible = null,
    ) {}

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(
            [
            'ID' => $this->id,
            'ID_Group' => $this->idGroup,
            'ID_EventType' => $this->idEventType,
            'ID_UserCreate' => $this->idUserCreate,
            'DateCreate' => $this->dateCreate,
            'DisplayName' => $this->displayName,
            'ID_Unit' => $this->idUnit,
            'Unit' => $this->unit,
            'RegistrationNumber' => $this->registrationNumber,
            'StartDate' => $this->startDate,
            'EndDate' => $this->endDate,
            'GpsLatitude' => $this->gpsLatitude,
            'GpsLatitudeText' => $this->gpsLatitudeText,
            'GpsLongitude' => $this->gpsLongitude,
            'GpsLongitudeText' => $this->gpsLongitudeText,
            'Location' => $this->location,
            'Note' => $this->note,
            'CancelDecision' => $this->cancelDecision,
            'ID_Event' => $this->idEvent,
            'ID_EventCampState' => $this->idEventCampState,
            'EventCampState' => $this->eventCampState,
            'MobileContact' => $this->mobileContact,
            'MobileContactDisplay' => $this->mobileContactDisplay,
            'RegistrationDeadline' => $this->registrationDeadline,
            'ID_Region' => $this->idRegion,
            'Region' => $this->region,
            'Postcode' => $this->postcode,
            'IsFloodArea' => $this->isFloodArea,
            'IsAutoComputed' => $this->isAutoComputed,
            'ID_PersonApproved' => $this->idPersonApproved,
            'PersonApproved' => $this->personApproved,
            'DateApproved' => $this->dateApproved,
            'ID_PersonApprovedParent' => $this->idPersonApprovedParent,
            'PersonApprovedParent' => $this->personApprovedParent,
            'DateApprovedParent' => $this->dateApprovedParent,
            'DateApprovedExecutive' => $this->dateApprovedExecutive,
            'TotalDays' => $this->totalDays,
            'IsRecovering' => $this->isRecovering,
            'CampType' => $this->campType,
            'string' => $this->string,
            'Units' => $this->units,
            'EstimateChild' => $this->estimateChild,
            'EstimateAdult' => $this->estimateAdult,
            'EstimateAdultYoung' => $this->estimateAdultYoung,
            'EstimateCount' => $this->estimateCount,
            'EstimateChildDays' => $this->estimateChildDays,
            'EstimatePersonDays' => $this->estimatePersonDays,
            'IsAutoComputedDays' => $this->isAutoComputedDays,
            'RealTotalCost' => $this->realTotalCost,
            'IsRealTotalCostAutoComputed' => $this->isRealTotalCostAutoComputed,
            'IsRealAutoComputed' => $this->isRealAutoComputed,
            'IsRealAutoComputedDays' => $this->isRealAutoComputedDays,
            'ID_PersonReal' => $this->idPersonReal,
            'PersonReal' => $this->personReal,
            'DateReal' => $this->dateReal,
            'RealAdult' => $this->realAdult,
            'RealAdultYoung' => $this->realAdultYoung,
            'RealChild' => $this->realChild,
            'RealCount' => $this->realCount,
            'RealChildDays' => $this->realChildDays,
            'RealPersonDays' => $this->realPersonDays,
            'HasEstimateStatement' => $this->hasEstimateStatement,
            'ID_PersonLeader' => $this->idPersonLeader,
            'PersonLeader' => $this->personLeader,
            'PersonLeaderFirstName' => $this->personLeaderFirstName,
            'PersonLeaderLastName' => $this->personLeaderLastName,
            'PersonLeaderCivilName' => $this->personLeaderCivilName,
            'LeaderPhone' => $this->leaderPhone,
            'LeaderPhoneDisplay' => $this->leaderPhoneDisplay,
            'LeaderEmail' => $this->leaderEmail,
            'LeaderEmailDisplay' => $this->leaderEmailDisplay,
            'LeaderCity' => $this->leaderCity,
            'UnitLocation' => $this->unitLocation,
            'PersonStatutory' => $this->personStatutory,
            'Profit' => $this->profit,
            'ProfitComputed' => $this->profitComputed,
            'ProfitComputedEstimation' => $this->profitComputedEstimation,
            'ID_CampPlace' => $this->idCampPlace,
            'CampPlace' => $this->campPlace,
            'IsOnlineLogin' => $this->isOnlineLogin,
            'CanUpdate' => $this->canUpdate,
            'CanUpdateReal' => $this->canUpdateReal,
            'AdultYoung' => $this->adultYoung,
            'IsRealVisible' => $this->isRealVisible,
            ],
            fn (mixed $v): bool => $v !== null,
        );
    }
}
