<?php

namespace Misakstvanu\LaravelSkautis\Responses\Summary;

final class ExportPersonAllOutput
{
    public function __construct(
        public readonly ?int $id = null,
        public readonly ?int $idPerson = null,
        public readonly ?string $person = null,
        public readonly ?string $displayName = null,
        public readonly ?string $listName = null,
        public readonly ?int $registrationYear = null,
        public readonly ?bool $functionFilter = null,
        public readonly ?bool $functionAnd = null,
        public readonly ?bool $qualificationAnd = null,
        public readonly ?int $ageFrom = null,
        public readonly ?int $ageTo = null,
        public readonly ?bool $viewDisplayName = null,
        public readonly ?bool $firstName = null,
        public readonly ?bool $lastName = null,
        public readonly ?bool $nickName = null,
        public readonly ?bool $maidenName = null,
        public readonly ?bool $birthday = null,
        public readonly ?bool $identificationNumber = null,
        public readonly ?bool $identificationNumberStart = null,
        public readonly ?bool $age = null,
        public readonly ?bool $sex = null,
        public readonly ?bool $isForeign = null,
        public readonly ?bool $street = null,
        public readonly ?bool $city = null,
        public readonly ?bool $postcode = null,
        public readonly ?bool $state = null,
        public readonly ?bool $postalFirstLine = null,
        public readonly ?bool $postalStreet = null,
        public readonly ?bool $postalCity = null,
        public readonly ?bool $postalPostcode = null,
        public readonly ?bool $postalState = null,
        public readonly ?bool $assurance = null,
        public readonly ?bool $assuranceCard = null,
        public readonly ?bool $allergy = null,
        public readonly ?bool $foodRestrictions = null,
        public readonly ?bool $drugs = null,
        public readonly ?bool $specialRequirements = null,
        public readonly ?bool $healthLimitation = null,
        public readonly ?bool $bodySkills = null,
        public readonly ?bool $idCardValidTo = null,
        public readonly ?bool $idCardNumber = null,
        public readonly ?bool $functionOneColumn = null,
        public readonly ?bool $qualificationOneColumn = null,
        public readonly ?bool $membership = null,
        public readonly ?bool $membershipOneColumn = null,
        public readonly ?bool $username = null,
        public readonly ?bool $catalog = null,
        public readonly ?bool $journal = null,
        public readonly ?bool $journalRegistration = null,
        public readonly ?bool $journalAttachment = null,
        public readonly ?bool $note = null,
        public readonly ?bool $parentNote = null,
        public readonly ?bool $registrationNumber = null,
        public readonly ?bool $yearFrom = null,
        public readonly ?bool $parentFatherFirstName = null,
        public readonly ?bool $parentFatherLastName = null,
        public readonly ?bool $parentFatherPhone = null,
        public readonly ?bool $parentFatherMail = null,
        public readonly ?bool $parentFatherNote = null,
        public readonly ?bool $parentMotherFirstName = null,
        public readonly ?bool $parentMotherLastName = null,
        public readonly ?bool $parentMotherMail = null,
        public readonly ?bool $parentMotherPhone = null,
        public readonly ?bool $parentMotherNote = null,
        public readonly ?bool $parentOtherFirstName = null,
        public readonly ?bool $parentOtherLastName = null,
        public readonly ?bool $parentOtherMail = null,
        public readonly ?bool $parentOtherPhone = null,
        public readonly ?bool $parentOtherNote = null,
        public readonly ?bool $parentOtherParentType = null,
        public readonly ?bool $promiseChild = null,
        public readonly ?bool $promiseScout = null,
        public readonly ?bool $promiseOfficial = null,
        public readonly ?bool $trailProgress = null,
    ) {}

    public static function fromStdClass(\stdClass $obj): self
    {
        return new self(
            id: isset($obj->{'ID'}) ? (int) $obj->{'ID'} : null,
            idPerson: isset($obj->{'ID_Person'}) ? (int) $obj->{'ID_Person'} : null,
            person: isset($obj->{'Person'}) ? (string) $obj->{'Person'} : null,
            displayName: isset($obj->{'DisplayName'}) ? (string) $obj->{'DisplayName'} : null,
            listName: isset($obj->{'ListName'}) ? (string) $obj->{'ListName'} : null,
            registrationYear: isset($obj->{'RegistrationYear'}) ? (int) $obj->{'RegistrationYear'} : null,
            functionFilter: isset($obj->{'FunctionFilter'}) ? (bool) $obj->{'FunctionFilter'} : null,
            functionAnd: isset($obj->{'FunctionAnd'}) ? (bool) $obj->{'FunctionAnd'} : null,
            qualificationAnd: isset($obj->{'QualificationAnd'}) ? (bool) $obj->{'QualificationAnd'} : null,
            ageFrom: isset($obj->{'AgeFrom'}) ? (int) $obj->{'AgeFrom'} : null,
            ageTo: isset($obj->{'AgeTo'}) ? (int) $obj->{'AgeTo'} : null,
            viewDisplayName: isset($obj->{'ViewDisplayName'}) ? (bool) $obj->{'ViewDisplayName'} : null,
            firstName: isset($obj->{'FirstName'}) ? (bool) $obj->{'FirstName'} : null,
            lastName: isset($obj->{'LastName'}) ? (bool) $obj->{'LastName'} : null,
            nickName: isset($obj->{'NickName'}) ? (bool) $obj->{'NickName'} : null,
            maidenName: isset($obj->{'MaidenName'}) ? (bool) $obj->{'MaidenName'} : null,
            birthday: isset($obj->{'Birthday'}) ? (bool) $obj->{'Birthday'} : null,
            identificationNumber: isset($obj->{'IdentificationNumber'}) ? (bool) $obj->{'IdentificationNumber'} : null,
            identificationNumberStart: isset($obj->{'IdentificationNumberStart'}) ? (bool) $obj->{'IdentificationNumberStart'} : null,
            age: isset($obj->{'Age'}) ? (bool) $obj->{'Age'} : null,
            sex: isset($obj->{'Sex'}) ? (bool) $obj->{'Sex'} : null,
            isForeign: isset($obj->{'IsForeign'}) ? (bool) $obj->{'IsForeign'} : null,
            street: isset($obj->{'Street'}) ? (bool) $obj->{'Street'} : null,
            city: isset($obj->{'City'}) ? (bool) $obj->{'City'} : null,
            postcode: isset($obj->{'Postcode'}) ? (bool) $obj->{'Postcode'} : null,
            state: isset($obj->{'State'}) ? (bool) $obj->{'State'} : null,
            postalFirstLine: isset($obj->{'PostalFirstLine'}) ? (bool) $obj->{'PostalFirstLine'} : null,
            postalStreet: isset($obj->{'PostalStreet'}) ? (bool) $obj->{'PostalStreet'} : null,
            postalCity: isset($obj->{'PostalCity'}) ? (bool) $obj->{'PostalCity'} : null,
            postalPostcode: isset($obj->{'PostalPostcode'}) ? (bool) $obj->{'PostalPostcode'} : null,
            postalState: isset($obj->{'PostalState'}) ? (bool) $obj->{'PostalState'} : null,
            assurance: isset($obj->{'Assurance'}) ? (bool) $obj->{'Assurance'} : null,
            assuranceCard: isset($obj->{'AssuranceCard'}) ? (bool) $obj->{'AssuranceCard'} : null,
            allergy: isset($obj->{'Allergy'}) ? (bool) $obj->{'Allergy'} : null,
            foodRestrictions: isset($obj->{'FoodRestrictions'}) ? (bool) $obj->{'FoodRestrictions'} : null,
            drugs: isset($obj->{'Drugs'}) ? (bool) $obj->{'Drugs'} : null,
            specialRequirements: isset($obj->{'SpecialRequirements'}) ? (bool) $obj->{'SpecialRequirements'} : null,
            healthLimitation: isset($obj->{'HealthLimitation'}) ? (bool) $obj->{'HealthLimitation'} : null,
            bodySkills: isset($obj->{'BodySkills'}) ? (bool) $obj->{'BodySkills'} : null,
            idCardValidTo: isset($obj->{'IdCardValidTo'}) ? (bool) $obj->{'IdCardValidTo'} : null,
            idCardNumber: isset($obj->{'IdCardNumber'}) ? (bool) $obj->{'IdCardNumber'} : null,
            functionOneColumn: isset($obj->{'FunctionOneColumn'}) ? (bool) $obj->{'FunctionOneColumn'} : null,
            qualificationOneColumn: isset($obj->{'QualificationOneColumn'}) ? (bool) $obj->{'QualificationOneColumn'} : null,
            membership: isset($obj->{'Membership'}) ? (bool) $obj->{'Membership'} : null,
            membershipOneColumn: isset($obj->{'MembershipOneColumn'}) ? (bool) $obj->{'MembershipOneColumn'} : null,
            username: isset($obj->{'Username'}) ? (bool) $obj->{'Username'} : null,
            catalog: isset($obj->{'Catalog'}) ? (bool) $obj->{'Catalog'} : null,
            journal: isset($obj->{'Journal'}) ? (bool) $obj->{'Journal'} : null,
            journalRegistration: isset($obj->{'JournalRegistration'}) ? (bool) $obj->{'JournalRegistration'} : null,
            journalAttachment: isset($obj->{'JournalAttachment'}) ? (bool) $obj->{'JournalAttachment'} : null,
            note: isset($obj->{'Note'}) ? (bool) $obj->{'Note'} : null,
            parentNote: isset($obj->{'ParentNote'}) ? (bool) $obj->{'ParentNote'} : null,
            registrationNumber: isset($obj->{'RegistrationNumber'}) ? (bool) $obj->{'RegistrationNumber'} : null,
            yearFrom: isset($obj->{'YearFrom'}) ? (bool) $obj->{'YearFrom'} : null,
            parentFatherFirstName: isset($obj->{'ParentFatherFirstName'}) ? (bool) $obj->{'ParentFatherFirstName'} : null,
            parentFatherLastName: isset($obj->{'ParentFatherLastName'}) ? (bool) $obj->{'ParentFatherLastName'} : null,
            parentFatherPhone: isset($obj->{'ParentFatherPhone'}) ? (bool) $obj->{'ParentFatherPhone'} : null,
            parentFatherMail: isset($obj->{'ParentFatherMail'}) ? (bool) $obj->{'ParentFatherMail'} : null,
            parentFatherNote: isset($obj->{'ParentFatherNote'}) ? (bool) $obj->{'ParentFatherNote'} : null,
            parentMotherFirstName: isset($obj->{'ParentMotherFirstName'}) ? (bool) $obj->{'ParentMotherFirstName'} : null,
            parentMotherLastName: isset($obj->{'ParentMotherLastName'}) ? (bool) $obj->{'ParentMotherLastName'} : null,
            parentMotherMail: isset($obj->{'ParentMotherMail'}) ? (bool) $obj->{'ParentMotherMail'} : null,
            parentMotherPhone: isset($obj->{'ParentMotherPhone'}) ? (bool) $obj->{'ParentMotherPhone'} : null,
            parentMotherNote: isset($obj->{'ParentMotherNote'}) ? (bool) $obj->{'ParentMotherNote'} : null,
            parentOtherFirstName: isset($obj->{'ParentOtherFirstName'}) ? (bool) $obj->{'ParentOtherFirstName'} : null,
            parentOtherLastName: isset($obj->{'ParentOtherLastName'}) ? (bool) $obj->{'ParentOtherLastName'} : null,
            parentOtherMail: isset($obj->{'ParentOtherMail'}) ? (bool) $obj->{'ParentOtherMail'} : null,
            parentOtherPhone: isset($obj->{'ParentOtherPhone'}) ? (bool) $obj->{'ParentOtherPhone'} : null,
            parentOtherNote: isset($obj->{'ParentOtherNote'}) ? (bool) $obj->{'ParentOtherNote'} : null,
            parentOtherParentType: isset($obj->{'ParentOtherParentType'}) ? (bool) $obj->{'ParentOtherParentType'} : null,
            promiseChild: isset($obj->{'PromiseChild'}) ? (bool) $obj->{'PromiseChild'} : null,
            promiseScout: isset($obj->{'PromiseScout'}) ? (bool) $obj->{'PromiseScout'} : null,
            promiseOfficial: isset($obj->{'PromiseOfficial'}) ? (bool) $obj->{'PromiseOfficial'} : null,
            trailProgress: isset($obj->{'TrailProgress'}) ? (bool) $obj->{'TrailProgress'} : null,
        );
    }
}
